// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/providers/home_feed_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:ui' as _i7;

import 'package:likes_repository/likes_repository.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:models/models.dart' as _i5;
import 'package:nostr_client/nostr_client.dart' as _i2;
import 'package:nostr_sdk/event.dart' as _i11;
import 'package:nostr_sdk/filter.dart' as _i14;
import 'package:nostr_sdk/nostr_sdk.dart' as _i15;
import 'package:openvine/services/age_verification_service.dart' as _i9;
import 'package:openvine/services/analytics_api_service.dart' as _i3;
import 'package:openvine/services/content_blocklist_service.dart' as _i8;
import 'package:openvine/services/subscription_manager.dart' as _i16;
import 'package:openvine/services/video_event_service.dart' as _i4;
import 'package:openvine/services/video_filter_builder.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCountResult_0 extends _i1.SmartFake implements _i2.CountResult {
  _FakeCountResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHomeFeedResult_1 extends _i1.SmartFake
    implements _i3.HomeFeedResult {
  _FakeHomeFeedResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecommendationsResult_2 extends _i1.SmartFake
    implements _i3.RecommendationsResult {
  _FakeRecommendationsResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [VideoEventService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoEventService extends _i1.Mock implements _i4.VideoEventService {
  MockVideoEventService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get shouldFilterAdultContent =>
      (super.noSuchMethod(
            Invocation.getter(#shouldFilterAdultContent),
            returnValue: false,
          )
          as bool);

  @override
  List<_i5.VideoEvent> get homeFeedVideos =>
      (super.noSuchMethod(
            Invocation.getter(#homeFeedVideos),
            returnValue: <_i5.VideoEvent>[],
          )
          as List<_i5.VideoEvent>);

  @override
  List<_i5.VideoEvent> get discoveryVideos =>
      (super.noSuchMethod(
            Invocation.getter(#discoveryVideos),
            returnValue: <_i5.VideoEvent>[],
          )
          as List<_i5.VideoEvent>);

  @override
  List<_i5.VideoEvent> get profileVideos =>
      (super.noSuchMethod(
            Invocation.getter(#profileVideos),
            returnValue: <_i5.VideoEvent>[],
          )
          as List<_i5.VideoEvent>);

  @override
  List<_i5.VideoEvent> get editorialVideos =>
      (super.noSuchMethod(
            Invocation.getter(#editorialVideos),
            returnValue: <_i5.VideoEvent>[],
          )
          as List<_i5.VideoEvent>);

  @override
  List<_i5.VideoEvent> get popularNowVideos =>
      (super.noSuchMethod(
            Invocation.getter(#popularNowVideos),
            returnValue: <_i5.VideoEvent>[],
          )
          as List<_i5.VideoEvent>);

  @override
  List<_i5.VideoEvent> get trendingVideos =>
      (super.noSuchMethod(
            Invocation.getter(#trendingVideos),
            returnValue: <_i5.VideoEvent>[],
          )
          as List<_i5.VideoEvent>);

  @override
  List<_i5.VideoEvent> get allHashtagVideos =>
      (super.noSuchMethod(
            Invocation.getter(#allHashtagVideos),
            returnValue: <_i5.VideoEvent>[],
          )
          as List<_i5.VideoEvent>);

  @override
  List<_i5.VideoEvent> get searchResults =>
      (super.noSuchMethod(
            Invocation.getter(#searchResults),
            returnValue: <_i5.VideoEvent>[],
          )
          as List<_i5.VideoEvent>);

  @override
  List<_i5.VideoEvent> get videoEvents =>
      (super.noSuchMethod(
            Invocation.getter(#videoEvents),
            returnValue: <_i5.VideoEvent>[],
          )
          as List<_i5.VideoEvent>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  String get classicVinesPubkey =>
      (super.noSuchMethod(
            Invocation.getter(#classicVinesPubkey),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#classicVinesPubkey),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.VoidCallback addVideoUpdateListener(
    void Function(_i5.VideoEvent)? callback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addVideoUpdateListener, [callback]),
            returnValue: () {},
          )
          as _i7.VoidCallback);

  @override
  _i7.VoidCallback addNewVideoListener(
    void Function(_i5.VideoEvent, String)? callback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addNewVideoListener, [callback]),
            returnValue: () {},
          )
          as _i7.VoidCallback);

  @override
  void removeVideoUpdateListener(void Function(_i5.VideoEvent)? callback) =>
      super.noSuchMethod(
        Invocation.method(#removeVideoUpdateListener, [callback]),
        returnValueForMissingStub: null,
      );

  @override
  void setBlocklistService(_i8.ContentBlocklistService? blocklistService) =>
      super.noSuchMethod(
        Invocation.method(#setBlocklistService, [blocklistService]),
        returnValueForMissingStub: null,
      );

  @override
  void setAgeVerificationService(
    _i9.AgeVerificationService? ageVerificationService,
  ) => super.noSuchMethod(
    Invocation.method(#setAgeVerificationService, [ageVerificationService]),
    returnValueForMissingStub: null,
  );

  @override
  void setLikesRepository(_i10.LikesRepository? likesRepository) =>
      super.noSuchMethod(
        Invocation.method(#setLikesRepository, [likesRepository]),
        returnValueForMissingStub: null,
      );

  @override
  bool shouldFilterEvent(_i11.Event? event) =>
      (super.noSuchMethod(
            Invocation.method(#shouldFilterEvent, [event]),
            returnValue: false,
          )
          as bool);

  @override
  int filterAdultContentFromExistingVideos() =>
      (super.noSuchMethod(
            Invocation.method(#filterAdultContentFromExistingVideos, []),
            returnValue: 0,
          )
          as int);

  @override
  List<_i5.VideoEvent> getVideos(_i4.SubscriptionType? type) =>
      (super.noSuchMethod(
            Invocation.method(#getVideos, [type]),
            returnValue: <_i5.VideoEvent>[],
          )
          as List<_i5.VideoEvent>);

  @override
  List<_i5.VideoEvent> hashtagVideos(String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#hashtagVideos, [tag]),
            returnValue: <_i5.VideoEvent>[],
          )
          as List<_i5.VideoEvent>);

  @override
  void debugDumpCdnDivineVideoThumbnails() => super.noSuchMethod(
    Invocation.method(#debugDumpCdnDivineVideoThumbnails, []),
    returnValueForMissingStub: null,
  );

  @override
  List<_i5.VideoEvent> authorVideos(String? pubkeyHex) =>
      (super.noSuchMethod(
            Invocation.method(#authorVideos, [pubkeyHex]),
            returnValue: <_i5.VideoEvent>[],
          )
          as List<_i5.VideoEvent>);

  @override
  bool isLoadingForSubscription(_i4.SubscriptionType? subscriptionType) =>
      (super.noSuchMethod(
            Invocation.method(#isLoadingForSubscription, [subscriptionType]),
            returnValue: false,
          )
          as bool);

  @override
  bool hasEvents(_i4.SubscriptionType? type) =>
      (super.noSuchMethod(
            Invocation.method(#hasEvents, [type]),
            returnValue: false,
          )
          as bool);

  @override
  int getEventCount(_i4.SubscriptionType? type) =>
      (super.noSuchMethod(
            Invocation.method(#getEventCount, [type]),
            returnValue: 0,
          )
          as int);

  @override
  _i5.VideoEvent? getVideoById(String? eventId) =>
      (super.noSuchMethod(Invocation.method(#getVideoById, [eventId]))
          as _i5.VideoEvent?);

  @override
  bool isSubscribed(_i4.SubscriptionType? type) =>
      (super.noSuchMethod(
            Invocation.method(#isSubscribed, [type]),
            returnValue: false,
          )
          as bool);

  @override
  List<_i5.VideoEvent> getVideosByAuthor(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getVideosByAuthor, [pubkey]),
            returnValue: <_i5.VideoEvent>[],
          )
          as List<_i5.VideoEvent>);

  @override
  void removeVideoFromAuthorList(String? authorPubkey, String? videoId) =>
      super.noSuchMethod(
        Invocation.method(#removeVideoFromAuthorList, [authorPubkey, videoId]),
        returnValueForMissingStub: null,
      );

  @override
  bool isVideoLocallyDeleted(String? videoId) =>
      (super.noSuchMethod(
            Invocation.method(#isVideoLocallyDeleted, [videoId]),
            returnValue: false,
          )
          as bool);

  @override
  _i12.Future<List<String>> getRepostersForVideo(String? videoId) =>
      (super.noSuchMethod(
            Invocation.method(#getRepostersForVideo, [videoId]),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<void> subscribeToVideoFeed({
    required _i4.SubscriptionType? subscriptionType,
    List<String>? authors,
    List<String>? hashtags,
    String? group,
    int? since,
    int? until,
    int? limit = 200,
    bool? replace = true,
    bool? includeReposts = false,
    _i13.VideoSortField? sortBy,
    _i13.NIP50SortMode? nip50Sort,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToVideoFeed, [], {
              #subscriptionType: subscriptionType,
              #authors: authors,
              #hashtags: hashtags,
              #group: group,
              #since: since,
              #until: until,
              #limit: limit,
              #replace: replace,
              #includeReposts: includeReposts,
              #sortBy: sortBy,
              #nip50Sort: nip50Sort,
              #force: force,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> subscribeToUserVideos(String? pubkey, {int? limit = 50}) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribeToUserVideos,
              [pubkey],
              {#limit: limit},
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> queryHistoricalUserVideos(
    String? pubkey, {
    int? until,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queryHistoricalUserVideos,
              [pubkey],
              {#until: until, #limit: limit},
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> subscribeToHashtagVideos(
    List<String>? hashtags, {
    int? limit = 100,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribeToHashtagVideos,
              [hashtags],
              {#limit: limit, #force: force},
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> subscribeToHomeFeed(
    List<String>? followingPubkeys, {
    int? limit = 100,
    _i13.VideoSortField? sortBy,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribeToHomeFeed,
              [followingPubkeys],
              {#limit: limit, #sortBy: sortBy, #force: force},
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void seedHomeFeedFromDiscoveryCache(List<String>? followingPubkeys) =>
      super.noSuchMethod(
        Invocation.method(#seedHomeFeedFromDiscoveryCache, [followingPubkeys]),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> seedHomeFeedFromFollowedUsers(
    List<String>? followingPubkeys, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #seedHomeFeedFromFollowedUsers,
              [followingPubkeys],
              {#limit: limit},
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> subscribeToDiscovery({
    int? limit = 100,
    _i13.VideoSortField? sortBy,
    _i13.NIP50SortMode? nip50Sort,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToDiscovery, [], {
              #limit: limit,
              #sortBy: sortBy,
              #nip50Sort: nip50Sort,
              #force: force,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> subscribeToGroupVideos(
    String? group, {
    List<String>? authors,
    int? since,
    int? until,
    int? limit = 200,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribeToGroupVideos,
              [group],
              {#authors: authors, #since: since, #until: until, #limit: limit},
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  List<_i5.VideoEvent> getVideoEventsByGroup(String? group) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoEventsByGroup, [group]),
            returnValue: <_i5.VideoEvent>[],
          )
          as List<_i5.VideoEvent>);

  @override
  _i12.Future<void> refreshVideoFeed() =>
      (super.noSuchMethod(
            Invocation.method(#refreshVideoFeed, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> resetAndResubscribeAll() =>
      (super.noSuchMethod(
            Invocation.method(#resetAndResubscribeAll, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> loadMoreVideos({int? limit = 100}) =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreVideos, [], {#limit: limit}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> loadMoreEvents(
    _i4.SubscriptionType? subscriptionType, {
    int? limit = 500,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #loadMoreEvents,
              [subscriptionType],
              {#limit: limit},
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void resetPaginationState(_i4.SubscriptionType? subscriptionType) =>
      super.noSuchMethod(
        Invocation.method(#resetPaginationState, [subscriptionType]),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> loadMoreContentUnlimited({
    _i4.SubscriptionType? subscriptionType = _i4.SubscriptionType.discovery,
    int? limit = 300,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreContentUnlimited, [], {
              #subscriptionType: subscriptionType,
              #limit: limit,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i5.VideoEvent? getVideoEventById(String? eventId) =>
      (super.noSuchMethod(Invocation.method(#getVideoEventById, [eventId]))
          as _i5.VideoEvent?);

  @override
  _i5.VideoEvent? getVideoEventByVineId(String? vineId) =>
      (super.noSuchMethod(Invocation.method(#getVideoEventByVineId, [vineId]))
          as _i5.VideoEvent?);

  @override
  _i12.Future<_i5.VideoEvent?> queryVideoByVineId(String? vineId) =>
      (super.noSuchMethod(
            Invocation.method(#queryVideoByVineId, [vineId]),
            returnValue: _i12.Future<_i5.VideoEvent?>.value(),
          )
          as _i12.Future<_i5.VideoEvent?>);

  @override
  List<_i5.VideoEvent> getVideoEventsByAuthor(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoEventsByAuthor, [pubkey]),
            returnValue: <_i5.VideoEvent>[],
          )
          as List<_i5.VideoEvent>);

  @override
  List<_i5.VideoEvent> getVideoEventsByHashtags(List<String>? hashtags) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoEventsByHashtags, [hashtags]),
            returnValue: <_i5.VideoEvent>[],
          )
          as List<_i5.VideoEvent>);

  @override
  void clearVideoEvents() => super.noSuchMethod(
    Invocation.method(#clearVideoEvents, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> unsubscribeFromVideoFeed() =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeFromVideoFeed, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  List<_i5.VideoEvent> getVideoEventsByEngagement() =>
      (super.noSuchMethod(
            Invocation.method(#getVideoEventsByEngagement, []),
            returnValue: <_i5.VideoEvent>[],
          )
          as List<_i5.VideoEvent>);

  @override
  List<_i5.VideoEvent> getRecentVideoEvents({int? hours = 24}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentVideoEvents, [], {#hours: hours}),
            returnValue: <_i5.VideoEvent>[],
          )
          as List<_i5.VideoEvent>);

  @override
  Set<String> getUniqueAuthors() =>
      (super.noSuchMethod(
            Invocation.method(#getUniqueAuthors, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Set<String> getAllHashtags() =>
      (super.noSuchMethod(
            Invocation.method(#getAllHashtags, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Map<String, int> getVideoCountByAuthor() =>
      (super.noSuchMethod(
            Invocation.method(#getVideoCountByAuthor, []),
            returnValue: <String, int>{},
          )
          as Map<String, int>);

  @override
  Map<String, dynamic> getConnectionStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getConnectionStatus, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i12.Future<void> retrySubscription() =>
      (super.noSuchMethod(
            Invocation.method(#retrySubscription, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void shuffleForDiscovery() => super.noSuchMethod(
    Invocation.method(#shuffleForDiscovery, []),
    returnValueForMissingStub: null,
  );

  @override
  void addVideoEvent(_i5.VideoEvent? videoEvent) => super.noSuchMethod(
    Invocation.method(#addVideoEvent, [videoEvent]),
    returnValueForMissingStub: null,
  );

  @override
  void updateVideoEvent(_i5.VideoEvent? updatedVideo) => super.noSuchMethod(
    Invocation.method(#updateVideoEvent, [updatedVideo]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> searchVideos(
    String? query, {
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchVideos,
              [query],
              {#authors: authors, #since: since, #until: until, #limit: limit},
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> searchVideosByHashtag(String? hashtag) =>
      (super.noSuchMethod(
            Invocation.method(#searchVideosByHashtag, [hashtag]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> searchVideosWithFilters({
    required String? query,
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchVideosWithFilters, [], {
              #query: query,
              #authors: authors,
              #since: since,
              #until: until,
              #limit: limit,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void clearSearchResults() => super.noSuchMethod(
    Invocation.method(#clearSearchResults, []),
    returnValueForMissingStub: null,
  );

  @override
  List<_i5.VideoEvent> processSearchResults(List<_i11.Event>? events) =>
      (super.noSuchMethod(
            Invocation.method(#processSearchResults, [events]),
            returnValue: <_i5.VideoEvent>[],
          )
          as List<_i5.VideoEvent>);

  @override
  List<_i5.VideoEvent> deduplicateSearchResults(
    List<_i5.VideoEvent>? results,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deduplicateSearchResults, [results]),
            returnValue: <_i5.VideoEvent>[],
          )
          as List<_i5.VideoEvent>);

  @override
  _i12.Future<void> searchVideosWithTimeRange({
    required String? query,
    required DateTime? since,
    required DateTime? until,
    List<String>? authors,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchVideosWithTimeRange, [], {
              #query: query,
              #since: since,
              #until: until,
              #authors: authors,
              #limit: limit,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> searchVideosWithExtensions(String? queryWithExtensions) =>
      (super.noSuchMethod(
            Invocation.method(#searchVideosWithExtensions, [
              queryWithExtensions,
            ]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  Map<_i4.SubscriptionType, _i4.PaginationState>
  getPaginationStatesForTesting() =>
      (super.noSuchMethod(
            Invocation.method(#getPaginationStatesForTesting, []),
            returnValue: <_i4.SubscriptionType, _i4.PaginationState>{},
          )
          as Map<_i4.SubscriptionType, _i4.PaginationState>);

  @override
  void addVideoEventForTesting(
    _i5.VideoEvent? event,
    _i4.SubscriptionType? type, {
    required bool? isHistorical,
  }) => super.noSuchMethod(
    Invocation.method(
      #addVideoEventForTesting,
      [event, type],
      {#isHistorical: isHistorical},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void injectTestVideos(List<_i5.VideoEvent>? videos) => super.noSuchMethod(
    Invocation.method(#injectTestVideos, [videos]),
    returnValueForMissingStub: null,
  );

  @override
  void handleEventForTesting(_i11.Event? event, _i4.SubscriptionType? type) =>
      super.noSuchMethod(
        Invocation.method(#handleEventForTesting, [event, type]),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NostrClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockNostrClient extends _i1.Mock implements _i2.NostrClient {
  MockNostrClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get publicKey =>
      (super.noSuchMethod(
            Invocation.getter(#publicKey),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#publicKey),
            ),
          )
          as String);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);

  @override
  bool get hasKeys =>
      (super.noSuchMethod(Invocation.getter(#hasKeys), returnValue: false)
          as bool);

  @override
  List<String> get configuredRelays =>
      (super.noSuchMethod(
            Invocation.getter(#configuredRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get connectedRelays =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  int get connectedRelayCount =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelayCount),
            returnValue: 0,
          )
          as int);

  @override
  int get configuredRelayCount =>
      (super.noSuchMethod(
            Invocation.getter(#configuredRelayCount),
            returnValue: 0,
          )
          as int);

  @override
  Map<String, _i2.RelayConnectionStatus> get relayStatuses =>
      (super.noSuchMethod(
            Invocation.getter(#relayStatuses),
            returnValue: <String, _i2.RelayConnectionStatus>{},
          )
          as Map<String, _i2.RelayConnectionStatus>);

  @override
  _i12.Stream<Map<String, _i2.RelayConnectionStatus>> get relayStatusStream =>
      (super.noSuchMethod(
            Invocation.getter(#relayStatusStream),
            returnValue:
                _i12.Stream<Map<String, _i2.RelayConnectionStatus>>.empty(),
          )
          as _i12.Stream<Map<String, _i2.RelayConnectionStatus>>);

  @override
  String get primaryRelay =>
      (super.noSuchMethod(
            Invocation.getter(#primaryRelay),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#primaryRelay),
            ),
          )
          as String);

  @override
  _i12.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i11.Event?> publishEvent(
    _i11.Event? event, {
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #publishEvent,
              [event],
              {#targetRelays: targetRelays},
            ),
            returnValue: _i12.Future<_i11.Event?>.value(),
          )
          as _i12.Future<_i11.Event?>);

  @override
  _i12.Future<List<_i11.Event>> queryEvents(
    List<_i14.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    bool? sendAfterAuth = false,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queryEvents,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #relayTypes: relayTypes,
                #sendAfterAuth: sendAfterAuth,
                #useCache: useCache,
              },
            ),
            returnValue: _i12.Future<List<_i11.Event>>.value(<_i11.Event>[]),
          )
          as _i12.Future<List<_i11.Event>>);

  @override
  _i12.Future<_i2.CountResult> countEvents(
    List<_i14.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #countEvents,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #relayTypes: relayTypes,
                #timeout: timeout,
              },
            ),
            returnValue: _i12.Future<_i2.CountResult>.value(
              _FakeCountResult_0(
                this,
                Invocation.method(
                  #countEvents,
                  [filters],
                  {
                    #subscriptionId: subscriptionId,
                    #tempRelays: tempRelays,
                    #relayTypes: relayTypes,
                    #timeout: timeout,
                  },
                ),
              ),
            ),
          )
          as _i12.Future<_i2.CountResult>);

  @override
  _i12.Future<_i11.Event?> fetchEventById(
    String? eventId, {
    String? relayUrl,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchEventById,
              [eventId],
              {#relayUrl: relayUrl, #useCache: useCache},
            ),
            returnValue: _i12.Future<_i11.Event?>.value(),
          )
          as _i12.Future<_i11.Event?>);

  @override
  _i12.Future<_i11.Event?> fetchProfile(
    String? pubkey, {
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProfile, [pubkey], {#useCache: useCache}),
            returnValue: _i12.Future<_i11.Event?>.value(),
          )
          as _i12.Future<_i11.Event?>);

  @override
  _i12.Stream<_i11.Event> subscribe(
    List<_i14.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<String>? targetRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    bool? sendAfterAuth = false,
    void Function()? onEose,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribe,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
                #relayTypes: relayTypes,
                #sendAfterAuth: sendAfterAuth,
                #onEose: onEose,
              },
            ),
            returnValue: _i12.Stream<_i11.Event>.empty(),
          )
          as _i12.Stream<_i11.Event>);

  @override
  _i12.Future<void> unsubscribe(String? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [subscriptionId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> closeAllSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#closeAllSubscriptions, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<bool> addRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#addRelay, [relayUrl]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<int> addRelays(List<String>? relayUrls) =>
      (super.noSuchMethod(
            Invocation.method(#addRelays, [relayUrls]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<bool> removeRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#removeRelay, [relayUrl]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<Map<String, dynamic>?> getRelayStats() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStats, []),
            returnValue: _i12.Future<Map<String, dynamic>?>.value(),
          )
          as _i12.Future<Map<String, dynamic>?>);

  @override
  _i12.Future<void> retryDisconnectedRelays() =>
      (super.noSuchMethod(
            Invocation.method(#retryDisconnectedRelays, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> forceReconnectAll() =>
      (super.noSuchMethod(
            Invocation.method(#forceReconnectAll, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  Map<String, bool> getRelayStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStatus, []),
            returnValue: <String, bool>{},
          )
          as Map<String, bool>);

  @override
  _i12.Future<_i11.Event?> sendLike(
    String? eventId, {
    String? content,
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendLike,
              [eventId],
              {
                #content: content,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
              },
            ),
            returnValue: _i12.Future<_i11.Event?>.value(),
          )
          as _i12.Future<_i11.Event?>);

  @override
  _i12.Future<_i11.Event?> sendProfile({
    required Map<String, dynamic>? profileContent,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendProfile, [], {
              #profileContent: profileContent,
            }),
            returnValue: _i12.Future<_i11.Event?>.value(),
          )
          as _i12.Future<_i11.Event?>);

  @override
  _i12.Future<_i11.Event?> sendRepost(
    String? eventId, {
    String? relayAddr,
    String? content = '',
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendRepost,
              [eventId],
              {
                #relayAddr: relayAddr,
                #content: content,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
              },
            ),
            returnValue: _i12.Future<_i11.Event?>.value(),
          )
          as _i12.Future<_i11.Event?>);

  @override
  _i12.Future<_i11.Event?> sendGenericRepost({
    required String? addressableId,
    required int? targetKind,
    required String? authorPubkey,
    String? eventId,
    String? content = '',
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendGenericRepost, [], {
              #addressableId: addressableId,
              #targetKind: targetKind,
              #authorPubkey: authorPubkey,
              #eventId: eventId,
              #content: content,
              #tempRelays: tempRelays,
              #targetRelays: targetRelays,
            }),
            returnValue: _i12.Future<_i11.Event?>.value(),
          )
          as _i12.Future<_i11.Event?>);

  @override
  _i12.Future<_i11.Event?> deleteEvent(
    String? eventId, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteEvent,
              [eventId],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i12.Future<_i11.Event?>.value(),
          )
          as _i12.Future<_i11.Event?>);

  @override
  _i12.Future<_i11.Event?> deleteEvents(
    List<String>? eventIds, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteEvents,
              [eventIds],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i12.Future<_i11.Event?>.value(),
          )
          as _i12.Future<_i11.Event?>);

  @override
  _i12.Future<_i11.Event?> sendContactList(
    _i15.ContactList? contacts,
    String? content, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendContactList,
              [contacts, content],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i12.Future<_i11.Event?>.value(),
          )
          as _i12.Future<_i11.Event?>);

  @override
  _i12.Stream<_i11.Event> searchVideos(
    String? query, {
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchVideos,
              [query],
              {#authors: authors, #since: since, #until: until, #limit: limit},
            ),
            returnValue: _i12.Stream<_i11.Event>.empty(),
          )
          as _i12.Stream<_i11.Event>);

  @override
  _i12.Stream<_i11.Event> searchUsers(String? query, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query], {#limit: limit}),
            returnValue: _i12.Stream<_i11.Event>.empty(),
          )
          as _i12.Stream<_i11.Event>);

  @override
  _i12.Future<String?> createNip98AuthHeader({
    required String? url,
    required String? method,
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createNip98AuthHeader, [], {
              #url: url,
              #method: method,
              #payload: payload,
            }),
            returnValue: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [SubscriptionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionManager extends _i1.Mock
    implements _i16.SubscriptionManager {
  MockSubscriptionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> get activeSubscriptionIds =>
      (super.noSuchMethod(
            Invocation.getter(#activeSubscriptionIds),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  int get activeSubscriptionCount =>
      (super.noSuchMethod(
            Invocation.getter(#activeSubscriptionCount),
            returnValue: 0,
          )
          as int);

  @override
  void setCacheLookup({
    _i11.Event? Function(String)? getCachedEvent,
    bool Function(String)? hasProfileCached,
  }) => super.noSuchMethod(
    Invocation.method(#setCacheLookup, [], {
      #getCachedEvent: getCachedEvent,
      #hasProfileCached: hasProfileCached,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<String> createSubscription({
    required String? name,
    required List<_i14.Filter>? filters,
    required dynamic Function(_i11.Event)? onEvent,
    dynamic Function(dynamic)? onError,
    dynamic Function()? onComplete,
    Duration? timeout,
    int? priority = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSubscription, [], {
              #name: name,
              #filters: filters,
              #onEvent: onEvent,
              #onError: onError,
              #onComplete: onComplete,
              #timeout: timeout,
              #priority: priority,
            }),
            returnValue: _i12.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#createSubscription, [], {
                  #name: name,
                  #filters: filters,
                  #onEvent: onEvent,
                  #onError: onError,
                  #onComplete: onComplete,
                  #timeout: timeout,
                  #priority: priority,
                }),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<void> cancelSubscription(String? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelSubscription, [subscriptionId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> cancelAllSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllSubscriptions, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  bool isSubscriptionActive(String? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#isSubscriptionActive, [subscriptionId]),
            returnValue: false,
          )
          as bool);

  @override
  _i12.Future<void> cancelSubscriptionsByName(String? namePattern) =>
      (super.noSuchMethod(
            Invocation.method(#cancelSubscriptionsByName, [namePattern]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [AnalyticsApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsApiService extends _i1.Mock
    implements _i3.AnalyticsApiService {
  MockAnalyticsApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAvailable =>
      (super.noSuchMethod(Invocation.getter(#isAvailable), returnValue: false)
          as bool);

  @override
  _i12.Future<List<_i5.VideoEvent>> getTrendingVideos({
    int? limit = 50,
    int? before,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTrendingVideos, [], {
              #limit: limit,
              #before: before,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i12.Future<List<_i5.VideoEvent>>.value(
              <_i5.VideoEvent>[],
            ),
          )
          as _i12.Future<List<_i5.VideoEvent>>);

  @override
  _i12.Future<List<_i5.VideoEvent>> getVideosByLoops({
    int? limit = 50,
    int? before,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getVideosByLoops, [], {
              #limit: limit,
              #before: before,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i12.Future<List<_i5.VideoEvent>>.value(
              <_i5.VideoEvent>[],
            ),
          )
          as _i12.Future<List<_i5.VideoEvent>>);

  @override
  _i12.Future<List<_i5.VideoEvent>> getRecentVideos({
    int? limit = 50,
    int? before,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentVideos, [], {
              #limit: limit,
              #before: before,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i12.Future<List<_i5.VideoEvent>>.value(
              <_i5.VideoEvent>[],
            ),
          )
          as _i12.Future<List<_i5.VideoEvent>>);

  @override
  _i12.Future<List<_i5.VideoEvent>> getVideosByHashtag({
    required String? hashtag,
    int? limit = 50,
    int? before,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getVideosByHashtag, [], {
              #hashtag: hashtag,
              #limit: limit,
              #before: before,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i12.Future<List<_i5.VideoEvent>>.value(
              <_i5.VideoEvent>[],
            ),
          )
          as _i12.Future<List<_i5.VideoEvent>>);

  @override
  _i12.Future<List<_i5.VideoEvent>> searchVideos({
    required String? query,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchVideos, [], {
              #query: query,
              #limit: limit,
            }),
            returnValue: _i12.Future<List<_i5.VideoEvent>>.value(
              <_i5.VideoEvent>[],
            ),
          )
          as _i12.Future<List<_i5.VideoEvent>>);

  @override
  _i12.Future<_i3.VideoStats?> getVideoStats(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoStats, [eventId]),
            returnValue: _i12.Future<_i3.VideoStats?>.value(),
          )
          as _i12.Future<_i3.VideoStats?>);

  @override
  _i12.Future<List<_i5.VideoEvent>> getVideosByAuthor({
    required String? pubkey,
    int? limit = 50,
    int? before,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getVideosByAuthor, [], {
              #pubkey: pubkey,
              #limit: limit,
              #before: before,
            }),
            returnValue: _i12.Future<List<_i5.VideoEvent>>.value(
              <_i5.VideoEvent>[],
            ),
          )
          as _i12.Future<List<_i5.VideoEvent>>);

  @override
  _i12.Future<Map<String, dynamic>?> getUserProfile(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [pubkey]),
            returnValue: _i12.Future<Map<String, dynamic>?>.value(),
          )
          as _i12.Future<Map<String, dynamic>?>);

  @override
  _i12.Future<_i3.HomeFeedResult> getHomeFeed({
    required String? pubkey,
    int? limit = 50,
    String? sort = 'recent',
    int? before,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getHomeFeed, [], {
              #pubkey: pubkey,
              #limit: limit,
              #sort: sort,
              #before: before,
            }),
            returnValue: _i12.Future<_i3.HomeFeedResult>.value(
              _FakeHomeFeedResult_1(
                this,
                Invocation.method(#getHomeFeed, [], {
                  #pubkey: pubkey,
                  #limit: limit,
                  #sort: sort,
                  #before: before,
                }),
              ),
            ),
          )
          as _i12.Future<_i3.HomeFeedResult>);

  @override
  _i12.Future<List<_i5.VideoEvent>> getClassicVines({
    int? limit = 50,
    int? before,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getClassicVines, [], {
              #limit: limit,
              #before: before,
            }),
            returnValue: _i12.Future<List<_i5.VideoEvent>>.value(
              <_i5.VideoEvent>[],
            ),
          )
          as _i12.Future<List<_i5.VideoEvent>>);

  @override
  _i12.Future<List<_i3.TrendingHashtag>> fetchTrendingHashtags({
    int? limit = 20,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTrendingHashtags, [], {
              #limit: limit,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i12.Future<List<_i3.TrendingHashtag>>.value(
              <_i3.TrendingHashtag>[],
            ),
          )
          as _i12.Future<List<_i3.TrendingHashtag>>);

  @override
  List<_i3.TrendingHashtag> getTrendingHashtags({int? limit = 25}) =>
      (super.noSuchMethod(
            Invocation.method(#getTrendingHashtags, [], {#limit: limit}),
            returnValue: <_i3.TrendingHashtag>[],
          )
          as List<_i3.TrendingHashtag>);

  @override
  _i12.Future<_i3.RecommendationsResult> getRecommendations({
    required String? pubkey,
    int? limit = 20,
    String? fallback = 'popular',
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecommendations, [], {
              #pubkey: pubkey,
              #limit: limit,
              #fallback: fallback,
              #category: category,
            }),
            returnValue: _i12.Future<_i3.RecommendationsResult>.value(
              _FakeRecommendationsResult_2(
                this,
                Invocation.method(#getRecommendations, [], {
                  #pubkey: pubkey,
                  #limit: limit,
                  #fallback: fallback,
                  #category: category,
                }),
              ),
            ),
          )
          as _i12.Future<_i3.RecommendationsResult>);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
