name: profile_repository
description: Repository for managing user profiles (Kind 0 metadata) with Nostr.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.11.0

resolution: workspace

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

dependencies:
  flutter:
    sdk: flutter
  db_client:
  equatable: ^2.0.8
  funnelcake_api_client:
  http: ^1.2.2
  models:
  nostr_client:
  nostr_sdk:
