// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'video_event.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Map<String, dynamic> _$VideoEventToJson(VideoEvent instance) =>
    <String, dynamic>{
      'id': instance.id,
      'pubkey': instance.pubkey,
      'createdAt': instance.createdAt,
      'content': instance.content,
      'title': instance.title,
      'videoUrl': instance.videoUrl,
      'thumbnailUrl': instance.thumbnailUrl,
      'duration': instance.duration,
      'dimensions': instance.dimensions,
      'mimeType': instance.mimeType,
      'sha256': instance.sha256,
      'fileSize': instance.fileSize,
      'hashtags': instance.hashtags,
      'timestamp': instance.timestamp.toIso8601String(),
      'publishedAt': instance.publishedAt,
      'rawTags': instance.rawTags,
      'vineId': instance.vineId,
      'stableId': instance.stableId,
      'group': instance.group,
      'altText': instance.altText,
      'blurhash': instance.blurhash,
      'isRepost': instance.isRepost,
      'reposterId': instance.reposterId,
      'reposterPubkey': instance.reposterPubkey,
      'reposterPubkeys': instance.reposterPubkeys,
      'repostedAt': instance.repostedAt?.toIso8601String(),
      'isFlaggedContent': instance.isFlaggedContent,
      'moderationStatus': instance.moderationStatus,
      'originalLoops': instance.originalLoops,
      'originalLikes': instance.originalLikes,
      'originalComments': instance.originalComments,
      'originalReposts': instance.originalReposts,
      'expirationTimestamp': instance.expirationTimestamp,
      'audioEventId': instance.audioEventId,
      'audioEventRelay': instance.audioEventRelay,
      'nostrLikeCount': instance.nostrLikeCount,
      'totalLikes': instance.totalLikes,
      'hasAudioReference': instance.hasAudioReference,
      'isExpired': instance.isExpired,
      'proofModeVerificationLevel': instance.proofModeVerificationLevel,
      'proofModeManifest': instance.proofModeManifest,
      'proofModeDeviceAttestation': instance.proofModeDeviceAttestation,
      'proofModePgpFingerprint': instance.proofModePgpFingerprint,
      'hasProofMode': instance.hasProofMode,
      'isVerifiedMobile': instance.isVerifiedMobile,
      'isVerifiedWeb': instance.isVerifiedWeb,
      'hasBasicProof': instance.hasBasicProof,
      'isOriginalVine': instance.isOriginalVine,
      'isOriginalContent': instance.isOriginalContent,
      'isFromDivineServer': instance.isFromDivineServer,
      'shouldShowNotDivineBadge': instance.shouldShowNotDivineBadge,
      'width': instance.width,
      'height': instance.height,
      'isPortrait': instance.isPortrait,
      'fileSizeMB': instance.fileSizeMB,
      'formattedDuration': instance.formattedDuration,
      'relativeTime': instance.relativeTime,
      'displayPubkey': instance.displayPubkey,
      'hasVideo': instance.hasVideo,
      'effectiveThumbnailUrl': instance.effectiveThumbnailUrl,
      'isGif': instance.isGif,
      'isMp4': instance.isMp4,
      'isWebM': instance.isWebM,
      'isSupportedOnCurrentPlatform': instance.isSupportedOnCurrentPlatform,
      'hashCode': instance.hashCode,
    };
