name: time_formatter
description: Utility for formatting timestamps into human-readable strings.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  intl: ">=0.19.0 <1.0.0"

dev_dependencies:
  test: ^1.26.3
  very_good_analysis: ^10.0.0
