// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/services/curated_list_service_initialization_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:keycast_flutter/keycast_flutter.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:nostr_client/nostr_client.dart' as _i5;
import 'package:nostr_client/src/models/models.dart' as _i2;
import 'package:nostr_sdk/nostr_sdk.dart' as _i4;
import 'package:openvine/services/auth_service.dart' as _i3;
import 'package:openvine/services/blossom_server_discovery_service.dart' as _i9;
import 'package:openvine/services/relay_discovery_service.dart' as _i8;
import 'package:openvine/services/user_profile_service.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCountResult_0 extends _i1.SmartFake implements _i2.CountResult {
  _FakeCountResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResult_1 extends _i1.SmartFake implements _i3.AuthResult {
  _FakeAuthResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNostrConnectSession_2 extends _i1.SmartFake
    implements _i4.NostrConnectSession {
  _FakeNostrConnectSession_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NostrClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockNostrClient extends _i1.Mock implements _i5.NostrClient {
  MockNostrClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get publicKey =>
      (super.noSuchMethod(
            Invocation.getter(#publicKey),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#publicKey),
            ),
          )
          as String);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);

  @override
  bool get hasKeys =>
      (super.noSuchMethod(Invocation.getter(#hasKeys), returnValue: false)
          as bool);

  @override
  List<String> get configuredRelays =>
      (super.noSuchMethod(
            Invocation.getter(#configuredRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get connectedRelays =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  int get connectedRelayCount =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelayCount),
            returnValue: 0,
          )
          as int);

  @override
  int get configuredRelayCount =>
      (super.noSuchMethod(
            Invocation.getter(#configuredRelayCount),
            returnValue: 0,
          )
          as int);

  @override
  Map<String, _i2.RelayConnectionStatus> get relayStatuses =>
      (super.noSuchMethod(
            Invocation.getter(#relayStatuses),
            returnValue: <String, _i2.RelayConnectionStatus>{},
          )
          as Map<String, _i2.RelayConnectionStatus>);

  @override
  _i7.Stream<Map<String, _i2.RelayConnectionStatus>> get relayStatusStream =>
      (super.noSuchMethod(
            Invocation.getter(#relayStatusStream),
            returnValue:
                _i7.Stream<Map<String, _i2.RelayConnectionStatus>>.empty(),
          )
          as _i7.Stream<Map<String, _i2.RelayConnectionStatus>>);

  @override
  String get primaryRelay =>
      (super.noSuchMethod(
            Invocation.getter(#primaryRelay),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#primaryRelay),
            ),
          )
          as String);

  @override
  _i7.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i4.Event?> publishEvent(
    _i4.Event? event, {
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #publishEvent,
              [event],
              {#targetRelays: targetRelays},
            ),
            returnValue: _i7.Future<_i4.Event?>.value(),
          )
          as _i7.Future<_i4.Event?>);

  @override
  _i7.Future<List<_i4.Event>> queryEvents(
    List<_i4.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    bool? sendAfterAuth = false,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queryEvents,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #relayTypes: relayTypes,
                #sendAfterAuth: sendAfterAuth,
                #useCache: useCache,
              },
            ),
            returnValue: _i7.Future<List<_i4.Event>>.value(<_i4.Event>[]),
          )
          as _i7.Future<List<_i4.Event>>);

  @override
  _i7.Future<_i2.CountResult> countEvents(
    List<_i4.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #countEvents,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #relayTypes: relayTypes,
                #timeout: timeout,
              },
            ),
            returnValue: _i7.Future<_i2.CountResult>.value(
              _FakeCountResult_0(
                this,
                Invocation.method(
                  #countEvents,
                  [filters],
                  {
                    #subscriptionId: subscriptionId,
                    #tempRelays: tempRelays,
                    #relayTypes: relayTypes,
                    #timeout: timeout,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i2.CountResult>);

  @override
  _i7.Future<_i4.Event?> fetchEventById(
    String? eventId, {
    String? relayUrl,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchEventById,
              [eventId],
              {#relayUrl: relayUrl, #useCache: useCache},
            ),
            returnValue: _i7.Future<_i4.Event?>.value(),
          )
          as _i7.Future<_i4.Event?>);

  @override
  _i7.Future<_i4.Event?> fetchProfile(
    String? pubkey, {
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProfile, [pubkey], {#useCache: useCache}),
            returnValue: _i7.Future<_i4.Event?>.value(),
          )
          as _i7.Future<_i4.Event?>);

  @override
  _i7.Stream<_i4.Event> subscribe(
    List<_i4.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<String>? targetRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    bool? sendAfterAuth = false,
    void Function()? onEose,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribe,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
                #relayTypes: relayTypes,
                #sendAfterAuth: sendAfterAuth,
                #onEose: onEose,
              },
            ),
            returnValue: _i7.Stream<_i4.Event>.empty(),
          )
          as _i7.Stream<_i4.Event>);

  @override
  _i7.Future<void> unsubscribe(String? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [subscriptionId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> closeAllSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#closeAllSubscriptions, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> addRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#addRelay, [relayUrl]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<int> addRelays(List<String>? relayUrls) =>
      (super.noSuchMethod(
            Invocation.method(#addRelays, [relayUrls]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<bool> removeRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#removeRelay, [relayUrl]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<Map<String, dynamic>?> getRelayStats() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStats, []),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<void> retryDisconnectedRelays() =>
      (super.noSuchMethod(
            Invocation.method(#retryDisconnectedRelays, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> forceReconnectAll() =>
      (super.noSuchMethod(
            Invocation.method(#forceReconnectAll, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  Map<String, bool> getRelayStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStatus, []),
            returnValue: <String, bool>{},
          )
          as Map<String, bool>);

  @override
  _i7.Future<_i4.Event?> sendLike(
    String? eventId, {
    String? content,
    String? addressableId,
    String? targetAuthorPubkey,
    int? targetKind,
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendLike,
              [eventId],
              {
                #content: content,
                #addressableId: addressableId,
                #targetAuthorPubkey: targetAuthorPubkey,
                #targetKind: targetKind,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
              },
            ),
            returnValue: _i7.Future<_i4.Event?>.value(),
          )
          as _i7.Future<_i4.Event?>);

  @override
  _i7.Future<_i4.Event?> sendProfile({
    required Map<String, dynamic>? profileContent,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendProfile, [], {
              #profileContent: profileContent,
            }),
            returnValue: _i7.Future<_i4.Event?>.value(),
          )
          as _i7.Future<_i4.Event?>);

  @override
  _i7.Future<_i4.Event?> sendRepost(
    String? eventId, {
    String? relayAddr,
    String? content = '',
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendRepost,
              [eventId],
              {
                #relayAddr: relayAddr,
                #content: content,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
              },
            ),
            returnValue: _i7.Future<_i4.Event?>.value(),
          )
          as _i7.Future<_i4.Event?>);

  @override
  _i7.Future<_i4.Event?> sendGenericRepost({
    required String? addressableId,
    required int? targetKind,
    required String? authorPubkey,
    String? eventId,
    String? content = '',
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendGenericRepost, [], {
              #addressableId: addressableId,
              #targetKind: targetKind,
              #authorPubkey: authorPubkey,
              #eventId: eventId,
              #content: content,
              #tempRelays: tempRelays,
              #targetRelays: targetRelays,
            }),
            returnValue: _i7.Future<_i4.Event?>.value(),
          )
          as _i7.Future<_i4.Event?>);

  @override
  _i7.Future<_i4.Event?> deleteEvent(
    String? eventId, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteEvent,
              [eventId],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i7.Future<_i4.Event?>.value(),
          )
          as _i7.Future<_i4.Event?>);

  @override
  _i7.Future<_i4.Event?> deleteEvents(
    List<String>? eventIds, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteEvents,
              [eventIds],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i7.Future<_i4.Event?>.value(),
          )
          as _i7.Future<_i4.Event?>);

  @override
  _i7.Future<_i4.Event?> sendContactList(
    _i4.ContactList? contacts,
    String? content, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendContactList,
              [contacts, content],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i7.Future<_i4.Event?>.value(),
          )
          as _i7.Future<_i4.Event?>);

  @override
  _i7.Stream<_i4.Event> searchVideos(
    String? query, {
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchVideos,
              [query],
              {#authors: authors, #since: since, #until: until, #limit: limit},
            ),
            returnValue: _i7.Stream<_i4.Event>.empty(),
          )
          as _i7.Stream<_i4.Event>);

  @override
  _i7.Stream<_i4.Event> searchUsers(String? query, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query], {#limit: limit}),
            returnValue: _i7.Stream<_i4.Event>.empty(),
          )
          as _i7.Stream<_i4.Event>);

  @override
  _i7.Future<List<_i4.Event>> queryUsers(String? query, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#queryUsers, [query], {#limit: limit}),
            returnValue: _i7.Future<List<_i4.Event>>.value(<_i4.Event>[]),
          )
          as _i7.Future<List<_i4.Event>>);

  @override
  _i7.Future<String?> createNip98AuthHeader({
    required String? url,
    required String? method,
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createNip98AuthHeader, [], {
              #url: url,
              #method: method,
              #payload: payload,
            }),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AuthState get authState =>
      (super.noSuchMethod(
            Invocation.getter(#authState),
            returnValue: _i3.AuthState.unauthenticated,
          )
          as _i3.AuthState);

  @override
  _i7.Stream<_i3.AuthState> get authStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#authStateStream),
            returnValue: _i7.Stream<_i3.AuthState>.empty(),
          )
          as _i7.Stream<_i3.AuthState>);

  @override
  _i7.Stream<_i3.UserProfile?> get profileStream =>
      (super.noSuchMethod(
            Invocation.getter(#profileStream),
            returnValue: _i7.Stream<_i3.UserProfile?>.empty(),
          )
          as _i7.Stream<_i3.UserProfile?>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i3.AuthenticationSource get authenticationSource =>
      (super.noSuchMethod(
            Invocation.getter(#authenticationSource),
            returnValue: _i3.AuthenticationSource.none,
          )
          as _i3.AuthenticationSource);

  @override
  bool get isRegistered =>
      (super.noSuchMethod(Invocation.getter(#isRegistered), returnValue: false)
          as bool);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false)
          as bool);

  @override
  List<_i8.DiscoveredRelay> get userRelays =>
      (super.noSuchMethod(
            Invocation.getter(#userRelays),
            returnValue: <_i8.DiscoveredRelay>[],
          )
          as List<_i8.DiscoveredRelay>);

  @override
  bool get hasExistingProfile =>
      (super.noSuchMethod(
            Invocation.getter(#hasExistingProfile),
            returnValue: false,
          )
          as bool);

  @override
  List<_i9.DiscoveredBlossomServer> get userBlossomServers =>
      (super.noSuchMethod(
            Invocation.getter(#userBlossomServers),
            returnValue: <_i9.DiscoveredBlossomServer>[],
          )
          as List<_i9.DiscoveredBlossomServer>);

  @override
  bool get hasUserBlossomServers =>
      (super.noSuchMethod(
            Invocation.getter(#hasUserBlossomServers),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, dynamic> get userStats =>
      (super.noSuchMethod(
            Invocation.getter(#userStats),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  String get serviceName =>
      (super.noSuchMethod(
            Invocation.getter(#serviceName),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#serviceName),
            ),
          )
          as String);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<bool> hasSavedKeys() =>
      (super.noSuchMethod(
            Invocation.method(#hasSavedKeys, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<String?> getSavedNpub() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedNpub, []),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i3.AuthResult> createNewIdentity({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#createNewIdentity, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i7.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#createNewIdentity, [], {
                  #biometricPrompt: biometricPrompt,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.AuthResult>);

  @override
  _i7.Future<_i3.AuthResult> connectWithAmber() =>
      (super.noSuchMethod(
            Invocation.method(#connectWithAmber, []),
            returnValue: _i7.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(this, Invocation.method(#connectWithAmber, [])),
            ),
          )
          as _i7.Future<_i3.AuthResult>);

  @override
  _i7.Future<_i3.AuthResult> importFromNsec(
    String? nsec, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importFromNsec,
              [nsec],
              {#biometricPrompt: biometricPrompt},
            ),
            returnValue: _i7.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(
                  #importFromNsec,
                  [nsec],
                  {#biometricPrompt: biometricPrompt},
                ),
              ),
            ),
          )
          as _i7.Future<_i3.AuthResult>);

  @override
  _i7.Future<_i3.AuthResult> importFromHex(
    String? privateKeyHex, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importFromHex,
              [privateKeyHex],
              {#biometricPrompt: biometricPrompt},
            ),
            returnValue: _i7.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(
                  #importFromHex,
                  [privateKeyHex],
                  {#biometricPrompt: biometricPrompt},
                ),
              ),
            ),
          )
          as _i7.Future<_i3.AuthResult>);

  @override
  _i7.Future<_i3.AuthResult> connectWithBunker(String? bunkerUrl) =>
      (super.noSuchMethod(
            Invocation.method(#connectWithBunker, [bunkerUrl]),
            returnValue: _i7.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#connectWithBunker, [bunkerUrl]),
              ),
            ),
          )
          as _i7.Future<_i3.AuthResult>);

  @override
  _i7.Future<_i4.NostrConnectSession> initiateNostrConnect({
    List<String>? customRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initiateNostrConnect, [], {
              #customRelays: customRelays,
            }),
            returnValue: _i7.Future<_i4.NostrConnectSession>.value(
              _FakeNostrConnectSession_2(
                this,
                Invocation.method(#initiateNostrConnect, [], {
                  #customRelays: customRelays,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.NostrConnectSession>);

  @override
  _i7.Future<_i3.AuthResult> waitForNostrConnectResponse({
    Duration? timeout = const Duration(minutes: 2),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#waitForNostrConnectResponse, [], {
              #timeout: timeout,
            }),
            returnValue: _i7.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#waitForNostrConnectResponse, [], {
                  #timeout: timeout,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.AuthResult>);

  @override
  void cancelNostrConnect() => super.noSuchMethod(
    Invocation.method(#cancelNostrConnect, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> refreshCurrentProfile(
    _i10.UserProfileService? userProfileService,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refreshCurrentProfile, [userProfileService]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> signInAutomatically() =>
      (super.noSuchMethod(
            Invocation.method(#signInAutomatically, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> signInWithDivineOAuth(_i11.KeycastSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithDivineOAuth, [session]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<(bool, String?)> deleteKeycastAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteKeycastAccount, []),
            returnValue: _i7.Future<(bool, String?)>.value((false, null)),
          )
          as _i7.Future<(bool, String?)>);

  @override
  _i7.Future<void> signOut({bool? deleteKeys = false}) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [], {#deleteKeys: deleteKeys}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String?> getPrivateKeyForSigning({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#getPrivateKeyForSigning, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<String?> exportNsec({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#exportNsec, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<_i4.Event?> createAndSignEvent({
    required int? kind,
    required String? content,
    List<List<String>>? tags,
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAndSignEvent, [], {
              #kind: kind,
              #content: content,
              #tags: tags,
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i7.Future<_i4.Event?>.value(),
          )
          as _i7.Future<_i4.Event?>);

  @override
  _i7.Future<void> acceptTerms() =>
      (super.noSuchMethod(
            Invocation.method(#acceptTerms, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onAppBackgrounded() => super.noSuchMethod(
    Invocation.method(#onAppBackgrounded, []),
    returnValueForMissingStub: null,
  );

  @override
  void onAppResumed() => super.noSuchMethod(
    Invocation.method(#onAppResumed, []),
    returnValueForMissingStub: null,
  );

  @override
  void onExtendedBackground() => super.noSuchMethod(
    Invocation.method(#onExtendedBackground, []),
    returnValueForMissingStub: null,
  );

  @override
  void onPeriodicCleanup() => super.noSuchMethod(
    Invocation.method(#onPeriodicCleanup, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
