// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/screens/welcome_screen_auth_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:keycast_flutter/keycast_flutter.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:nostr_sdk/nostr_sdk.dart' as _i3;
import 'package:openvine/models/known_account.dart' as _i7;
import 'package:openvine/services/auth_service.dart' as _i2;
import 'package:openvine/services/relay_discovery_service.dart' as _i5;
import 'package:openvine/services/user_profile_service.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthResult_0 extends _i1.SmartFake implements _i2.AuthResult {
  _FakeAuthResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNostrConnectSession_1 extends _i1.SmartFake
    implements _i3.NostrConnectSession {
  _FakeNostrConnectSession_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthState get authState =>
      (super.noSuchMethod(
            Invocation.getter(#authState),
            returnValue: _i2.AuthState.unauthenticated,
          )
          as _i2.AuthState);

  @override
  _i4.Stream<_i2.AuthState> get authStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#authStateStream),
            returnValue: _i4.Stream<_i2.AuthState>.empty(),
          )
          as _i4.Stream<_i2.AuthState>);

  @override
  _i4.Stream<_i2.UserProfile?> get profileStream =>
      (super.noSuchMethod(
            Invocation.getter(#profileStream),
            returnValue: _i4.Stream<_i2.UserProfile?>.empty(),
          )
          as _i4.Stream<_i2.UserProfile?>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i2.AuthenticationSource get authenticationSource =>
      (super.noSuchMethod(
            Invocation.getter(#authenticationSource),
            returnValue: _i2.AuthenticationSource.none,
          )
          as _i2.AuthenticationSource);

  @override
  bool get isRegistered =>
      (super.noSuchMethod(Invocation.getter(#isRegistered), returnValue: false)
          as bool);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false)
          as bool);

  @override
  List<_i5.DiscoveredRelay> get userRelays =>
      (super.noSuchMethod(
            Invocation.getter(#userRelays),
            returnValue: <_i5.DiscoveredRelay>[],
          )
          as List<_i5.DiscoveredRelay>);

  @override
  bool get hasExistingProfile =>
      (super.noSuchMethod(
            Invocation.getter(#hasExistingProfile),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, dynamic> get userStats =>
      (super.noSuchMethod(
            Invocation.getter(#userStats),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  String get serviceName =>
      (super.noSuchMethod(
            Invocation.getter(#serviceName),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#serviceName),
            ),
          )
          as String);

  @override
  void registerUserRelaysDiscoveredCallback(
    _i2.UserRelaysDiscoveredCallback? callback,
  ) => super.noSuchMethod(
    Invocation.method(#registerUserRelaysDiscoveredCallback, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<bool> hasSavedKeys() =>
      (super.noSuchMethod(
            Invocation.method(#hasSavedKeys, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String?> getSavedNpub() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedNpub, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.AuthResult> createNewIdentity({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#createNewIdentity, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i4.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(#createNewIdentity, [], {
                  #biometricPrompt: biometricPrompt,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<void> createAnonymousAccount() =>
      (super.noSuchMethod(
            Invocation.method(#createAnonymousAccount, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.KnownAccount>> getKnownAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#getKnownAccounts, []),
            returnValue: _i4.Future<List<_i7.KnownAccount>>.value(
              <_i7.KnownAccount>[],
            ),
          )
          as _i4.Future<List<_i7.KnownAccount>>);

  @override
  _i4.Future<void> removeKnownAccount(String? pubkeyHex) =>
      (super.noSuchMethod(
            Invocation.method(#removeKnownAccount, [pubkeyHex]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> signInForAccount(
    String? pubkeyHex,
    _i2.AuthenticationSource? authSource,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInForAccount, [pubkeyHex, authSource]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.AuthResult> connectWithAmber() =>
      (super.noSuchMethod(
            Invocation.method(#connectWithAmber, []),
            returnValue: _i4.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(this, Invocation.method(#connectWithAmber, [])),
            ),
          )
          as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<_i2.AuthResult> importFromNsec(
    String? nsec, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importFromNsec,
              [nsec],
              {#biometricPrompt: biometricPrompt},
            ),
            returnValue: _i4.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(
                  #importFromNsec,
                  [nsec],
                  {#biometricPrompt: biometricPrompt},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<_i2.AuthResult> importFromHex(
    String? privateKeyHex, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importFromHex,
              [privateKeyHex],
              {#biometricPrompt: biometricPrompt},
            ),
            returnValue: _i4.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(
                  #importFromHex,
                  [privateKeyHex],
                  {#biometricPrompt: biometricPrompt},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<_i2.AuthResult> connectWithBunker(String? bunkerUrl) =>
      (super.noSuchMethod(
            Invocation.method(#connectWithBunker, [bunkerUrl]),
            returnValue: _i4.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(#connectWithBunker, [bunkerUrl]),
              ),
            ),
          )
          as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<_i3.NostrConnectSession> initiateNostrConnect({
    List<String>? customRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initiateNostrConnect, [], {
              #customRelays: customRelays,
            }),
            returnValue: _i4.Future<_i3.NostrConnectSession>.value(
              _FakeNostrConnectSession_1(
                this,
                Invocation.method(#initiateNostrConnect, [], {
                  #customRelays: customRelays,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.NostrConnectSession>);

  @override
  _i4.Future<_i2.AuthResult> waitForNostrConnectResponse({
    Duration? timeout = const Duration(minutes: 2),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#waitForNostrConnectResponse, [], {
              #timeout: timeout,
            }),
            returnValue: _i4.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(#waitForNostrConnectResponse, [], {
                  #timeout: timeout,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.AuthResult>);

  @override
  void cancelNostrConnect() => super.noSuchMethod(
    Invocation.method(#cancelNostrConnect, []),
    returnValueForMissingStub: null,
  );

  @override
  void onSignerCallbackReceived() => super.noSuchMethod(
    Invocation.method(#onSignerCallbackReceived, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> refreshCurrentProfile(
    _i8.UserProfileService? userProfileService,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refreshCurrentProfile, [userProfileService]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> signInWithDivineOAuth(_i9.KeycastSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithDivineOAuth, [session]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<(bool, String?)> deleteKeycastAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteKeycastAccount, []),
            returnValue: _i4.Future<(bool, String?)>.value((false, null)),
          )
          as _i4.Future<(bool, String?)>);

  @override
  _i4.Future<void> signOut({bool? deleteKeys = false}) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [], {#deleteKeys: deleteKeys}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getPrivateKeyForSigning({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#getPrivateKeyForSigning, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> exportNsec({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#exportNsec, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<_i3.Event?> createAndSignEvent({
    required int? kind,
    required String? content,
    List<List<String>>? tags,
    String? biometricPrompt,
    int? createdAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAndSignEvent, [], {
              #kind: kind,
              #content: content,
              #tags: tags,
              #biometricPrompt: biometricPrompt,
              #createdAt: createdAt,
            }),
            returnValue: _i4.Future<_i3.Event?>.value(),
          )
          as _i4.Future<_i3.Event?>);

  @override
  _i4.Future<void> acceptTerms() =>
      (super.noSuchMethod(
            Invocation.method(#acceptTerms, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void onAppBackgrounded() => super.noSuchMethod(
    Invocation.method(#onAppBackgrounded, []),
    returnValueForMissingStub: null,
  );

  @override
  void onAppResumed() => super.noSuchMethod(
    Invocation.method(#onAppResumed, []),
    returnValueForMissingStub: null,
  );

  @override
  void onExtendedBackground() => super.noSuchMethod(
    Invocation.method(#onExtendedBackground, []),
    returnValueForMissingStub: null,
  );

  @override
  void onPeriodicCleanup() => super.noSuchMethod(
    Invocation.method(#onPeriodicCleanup, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
