name: people_lists_repository
description: Repository for managing NIP-51 kind 30000 people lists.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  equatable: ^2.0.5
  hive_ce:
  models:
  nostr_client:
  nostr_sdk:
  rxdart: ^0.28.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.29.0
  very_good_analysis: ^10.2.0
