#!/usr/bin/env bash
# Raw-Icons ceiling ratchet (#4803, epic #4339): every Dart file under mobile/lib
# that still uses raw Material `Icons.*` is frozen at its current raw-icon count
# in scripts/baseline/raw_icons.txt, which acts as a per-file CEILING. A ceiling
# may only ever DECREASE. CI fails if:
#   • a baselined file GAINS raw icons past its recorded ceiling,
#   • a NEW file introduces raw Icons.* (not in the baseline),
#   • the in-branch baseline RAISES a ceiling or ADDS a file vs the base ref
#     (closes the bypass where a PR adds icons then reruns UPDATE_BASELINE).
# This freezes the deferred APPROX/NONE/param residue (#4803) so the migration
# can only shrink: new UI must use DivineIcon(icon: DivineIconName.X) from
# divine_ui, never raw Material Icons.* (rule: ui_theming.md → "Icons").
#
# Like check_raw_textstyle_ceiling.sh, this is a per-key NUMERIC ceiling driven by
# lib/numeric_ratchet.sh (not a LIST ratchet): a file may drop raw icons freely
# while staying above zero without churning the baseline; only growth / a new
# file / a raised ceiling / a drop-to-zero (STALE) fails.
#
# Counting EXCLUDES full-line comments (^//, ^///) so the two dartdoc references
# (circular_icon_button.dart, rounded_icon_button.dart) don't count, and EXCLUDES
# generated code by PATH (mobile/lib/l10n/generated/) and by suffix
# (*.g.dart/*.freezed.dart/*.gr.dart/*.config.dart/*.mocks.dart). Scans mobile/lib
# only, so divine_ui's sanctioned MaterialIconSource escape hatch + its own
# Icons.refresh are out of scope by construction.
#
# Regenerate after MIGRATING raw icons to DivineIcon (never to raise a ceiling —
# that is what CI blocks):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_raw_icons_ceiling.sh
# Run (from repo root or mobile/): bash mobile/scripts/check_raw_icons_ceiling.sh

set -euo pipefail

# Byte-wise, locale-independent ordering so sort/join agree across macOS (local)
# and Linux (CI); otherwise the baseline diff can falsely flag NEW/GROWTH.
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TAB="$(printf '\t')"

RATCHET_LABEL="raw_icons_ceiling"
SCAN_DIR="${RAW_ICONS_SCAN_DIR:-$MOBILE_DIR/lib}"
PATH_PREFIX="${RAW_ICONS_PATH_PREFIX:-$MOBILE_DIR}"
BASELINE_FILE="${RAW_ICONS_BASELINE_FILE:-$SCRIPT_DIR/baseline/raw_icons.txt}"
# Repo-relative path of the baseline as seen on the base ref, used by the
# anti-bypass check. Overridable so tests can diff against an already-committed
# baseline-format file.
BASELINE_REPO_PATH="${RAW_ICONS_BASELINE_REPO_PATH:-mobile/scripts/baseline/raw_icons.txt}"
BASE_REF="${RAW_ICONS_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${RAW_ICONS_CEILING_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="RAW_ICONS_CEILING_ALLOW_NO_BASE"

NEW_HINT="Don't add raw Material Icons.* — use DivineIcon(icon: DivineIconName.X) from divine_ui (ui_theming.md → Icons, #4803). If no glyph exists, the icon is blocked on #4833."
STALE_HINT="A file dropped raw Icons.* (migrated to DivineIcon or removed)."
FOOTER="Raw Material Icons.* counts under mobile/lib are frozen and may only
decrease. Migrate to DivineIcon(icon: DivineIconName.X) rather than adding more.
See tasks/plan_4803.md and epics #4803 / #4339."

# Print "relpath<TAB>count" for every non-generated Dart file under SCAN_DIR that
# uses raw Icons.* (outside full-line comments), sorted by path (field 1) so
# join/comm behave deterministically.
emit_current() {
  find "$SCAN_DIR" \
    -type f -name '*.dart' \
    -not -path '*/l10n/generated/*' \
    -not -path '*/.dart_tool/*' \
    -not -path '*/build/*' \
    ! -name '*.g.dart' ! -name '*.freezed.dart' ! -name '*.gr.dart' \
    ! -name '*.config.dart' ! -name '*.mocks.dart' \
    -print0 2>/dev/null \
  | while IFS= read -r -d '' f; do
      count="$(grep -vE '^[[:space:]]*//' "$f" 2>/dev/null \
        | grep -oE 'Icons\.[A-Za-z_][A-Za-z0-9_]*' \
        | grep -c . || true)"
      count="${count//[[:space:]]/}"
      if [[ "${count:-0}" -gt 0 ]]; then
        printf '%s\t%s\n' "${f#"$PATH_PREFIX"/}" "$count"
      fi
    done \
  | LC_ALL=C sort -t "$TAB" -k1,1
}

print_baseline_header() {
  cat <<EOF
# Frozen baseline: Dart files under mobile/lib using raw Material Icons.*, each
# with its current raw-icon count as a CEILING (format: relpath<TAB>count).
# Generated by scripts/check_raw_icons_ceiling.sh. A ceiling may only SHRINK;
# more raw icons, a new file, or a raised ceiling fails CI vs ${BASE_REF}.
# Issues: #4803 (migration), #4339 (epic). Full-line comments are not counted.
# Regenerate after migrating: UPDATE_BASELINE=1 bash scripts/check_raw_icons_ceiling.sh
EOF
}

# shellcheck source=lib/numeric_ratchet.sh
source "$SCRIPT_DIR/lib/numeric_ratchet.sh"
run_numeric_ratchet
