#!/usr/bin/env bash
# Implicit-Font-color ceiling ratchet (#6404): a VineTheme.*Font(...) call that
# passes no `color:` takes its color from the ambient DefaultTextStyle. Until
# the light-mode migration, `color` DEFAULTED to VineTheme.whiteText, and 266
# call sites relied on that default — every one of them became white text on a
# white surface the moment the light palette reached the UI. The default was
# removed (color is now `Color?`), which fixes the failure mode but does not
# prevent it: `VineTheme.bodyMediumFont()` still compiles and still inherits
# whatever style happens to be in scope, which is not guaranteed to be right in
# either palette.
#
# This guard freezes the count at its post-migration value — zero — so the
# invariant is enforced rather than asserted. The baseline is EMPTY: any file
# that introduces an implicit-color Font call fails as a NEW key.
#
# Detector: `VineTheme.<name>Font(` whose balanced-paren argument list contains
# no `color:` (see lib/implicit_font_color.awk), in code only — comments and
# string literals are stripped first by lib/dart_code_only.awk, so a Font( in a
# doc comment never counts. Both mobile/lib and packages/divine_ui/lib are
# scanned; divine_ui is where the helpers are DEFINED, and a definition is not
# a call, so only real call sites count.
#
# Fix, don't baseline: pass the color the site actually wants —
# `context.vineColors.<token>` for palette-driven text, or an explicit fixed
# color (with a comment saying why) for text layered on video, camera preview
# or a photo thumbnail. See ui_theming.md → Typography.
#
# Regenerate ONLY after an intentional, reviewed change:
#   UPDATE_BASELINE=1 bash mobile/scripts/check_implicit_font_color_ceiling.sh
# Run (from repo root or mobile/):
#   bash mobile/scripts/check_implicit_font_color_ceiling.sh

set -euo pipefail
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TAB="$(printf '\t')"

RATCHET_LABEL="implicit_font_color_ceiling"
PATH_PREFIX="${IMPLICIT_FONT_COLOR_PATH_PREFIX:-$MOBILE_DIR}"
BASELINE_FILE="${IMPLICIT_FONT_COLOR_BASELINE_FILE:-$SCRIPT_DIR/baseline/implicit_font_color.txt}"
BASELINE_REPO_PATH="${IMPLICIT_FONT_COLOR_BASELINE_REPO_PATH:-mobile/scripts/baseline/implicit_font_color.txt}"
BASE_REF="${IMPLICIT_FONT_COLOR_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${IMPLICIT_FONT_COLOR_CEILING_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="IMPLICIT_FONT_COLOR_CEILING_ALLOW_NO_BASE"

# Space-separated roots (the sibling ratchets scan one; the invariant holds in
# divine_ui too, where the Font helpers are defined). Overridable for the
# self-test, which reuses the shared design-system detector harness.
SCAN_DIR="${IMPLICIT_FONT_COLOR_SCAN_DIR:-$MOBILE_DIR/lib $MOBILE_DIR/packages/divine_ui/lib}"

NEW_HINT="A VineTheme.*Font(...) call without color: inherits the ambient text style — the exact shape that rendered 266 call sites white-on-white when light mode landed. Pass context.vineColors.<token>, or a fixed color with a comment when the text is layered on media. ui_theming.md → Typography; #6404."
STALE_HINT="A file dropped its implicit-color Font call (a color was passed, or the call was removed)."
FOOTER="Implicit-color VineTheme.*Font( calls are frozen at zero.
Give the call the color it means instead of inheriting one.
See ui_theming.md (Typography) and #6404."

emit_current() {
  # shellcheck disable=SC2086
  find $SCAN_DIR \
    -type f -name '*.dart' \
    -not -path '*/l10n/generated/*' \
    -not -path '*/.dart_tool/*' \
    -not -path '*/build/*' \
    ! -name '*.g.dart' ! -name '*.freezed.dart' ! -name '*.gr.dart' \
    ! -name '*.config.dart' ! -name '*.mocks.dart' \
    -print0 2>/dev/null \
  | while IFS= read -r -d '' f; do
      count="$(awk -f "$SCRIPT_DIR/lib/dart_code_only.awk" "$f" 2>/dev/null \
        | awk -f "$SCRIPT_DIR/lib/implicit_font_color.awk" 2>/dev/null \
        | grep -c . || true)"
      count="${count//[[:space:]]/}"
      if [[ "${count:-0}" -gt 0 ]]; then
        printf '%s\t%s\n' "${f#"$PATH_PREFIX"/}" "$count"
      fi
    done \
  | LC_ALL=C sort -t "$TAB" -k1,1
}

print_baseline_header() {
  cat <<EOF
# Frozen baseline: Dart files under mobile/lib and packages/divine_ui/lib that
# call VineTheme.*Font(...) WITHOUT a color: argument, each with its count as a
# CEILING (format: relpath<TAB>count). The list is intentionally EMPTY — the
# light-mode migration removed the whiteText default and closed every implicit
# call site, so any entry here is a regression.
# Generated by scripts/check_implicit_font_color_ceiling.sh. Fix the call site
# rather than regenerating this file.
# Issue: #6404.
EOF
}

# shellcheck source=lib/numeric_ratchet.sh
source "$SCRIPT_DIR/lib/numeric_ratchet.sh"
run_numeric_ratchet
