#!/usr/bin/env bash
# Orphaned-ARB-key floor ratchet (#3630): the set of app_en.arb keys that
# nothing under lib/ renders is frozen in
# scripts/baseline/orphaned_arb_keys.txt and may only ever SHRINK. See
# lib/list_ratchet.sh for the NEW/STALE/GROWTH semantics.
#
# Why this exists: an orphaned key costs real money and never fails anything. It
# is translated into 21 locales by a paid pass, ships in every app_*.arb, and
# compiles into AppLocalizations for the life of the repo — while the string it
# was written for usually sits hardcoded in a widget, still broken for every
# non-English user. No other guard sees it: arb_consistency_test proves a key
# exists in every locale (an orphan passes trivially, in all 22), gen-l10n has
# no notion of an unused message, and `flutter analyze` cannot report an unused
# public getter on a generated class. The set grew 94 -> 276 in the four months
# #3630 sat open, which is what an unguarded cleanup gets you.
#
# Detector: scripts/lib/orphaned_arb_key_detector.dart — an analyzer AST pass,
# not a grep. It counts a key as referenced only where the name appears as CODE,
# so a `// TODO wire up feedSkip`, a `Log.info('feedSkip')`, or an unrelated
# enum constant of the same name (the real `uploadFailed` case) does not keep a
# dead key alive.
#
# It scans lib/ ONLY. A test cannot make a key rendered, and counting test
# references hid 9 product-orphans — four of them propped up by a
# `find.text(l10n.x), findsNothing` assertion, which is a test PROVING the
# string is not on screen. Those carry a '# test-only' reason below.
#
# BASELINE ENTRIES ARE A WORKLIST, NOT AN EXEMPTION. Each carries a trailing
# '# reason' in one of two shapes:
#   • `# wire: <path>:<line>` — a live widget renders this string hardcoded.
#     The key is right, the call site is wrong. Fixing it is a real l10n bug fix
#     for 21 locales, not a cleanup.
#   • `# staged: <why>` — deliberately ahead of its call site (a sibling set
#     whose other keys are live, an in-flight feature).
#   • `# test-only: <where>` — nothing in lib/ renders it; only a test names it.
#     Resolving one means editing that test too, so it is tracked in #7968
#     rather than swept here.
# A key with no live counterpart at all does NOT belong here — delete it from
# app_en.arb and every app_*.arb locale instead.
#
# List the current orphans (add --detail for the English value):
#   cd mobile && dart run scripts/lib/orphaned_arb_key_detector.dart --detail
# Regenerate after deleting or wiring up keys (never to excuse a new orphan):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_orphaned_arb_key_floor.sh
# Usage (from the repo root or mobile/): bash mobile/scripts/check_orphaned_arb_key_floor.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

RATCHET_LABEL="orphaned_arb_key_floor"
BASELINE_FILE="$SCRIPT_DIR/baseline/orphaned_arb_keys.txt"
BASELINE_REPO_PATH="mobile/scripts/baseline/orphaned_arb_keys.txt"
BASE_REF="${ORPHANED_ARB_KEY_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${ORPHANED_ARB_KEY_FLOOR_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="ORPHANED_ARB_KEY_FLOOR_ALLOW_NO_BASE"
NEW_HINT="An app_en.arb key is rendered by nothing under lib/, so it will be translated into 21 locales and never shown. A reference from test/ does not count — a test cannot render a string, and a findsNothing assertion is evidence the key is DEAD. Add the key in the SAME change that reads it through context.l10n — not ahead of it. If the string is already on screen hardcoded, wire that call site up instead. Only if the key is genuinely staged should it enter the baseline, with a trailing '# staged: <why>'. See #3630."
STALE_HINT="A baselined key is now referenced, or was deleted from app_en.arb."
FOOTER="Orphaned ARB keys are frozen and may only decrease. Wire the key up at
its call site, or delete it from app_en.arb AND every app_*.arb locale. Adding
it to the baseline is for a key that is genuinely staged ahead of its call site;
say so with a trailing '# staged: <why>'. See #3630 and
.claude/rules/localization.md."

emit_current() {
  (cd "$MOBILE_DIR" && dart run scripts/lib/orphaned_arb_key_detector.dart \
    2>/dev/null | LC_ALL=C sort -u) || true
}

print_baseline_header() {
  cat <<'EOF'
# Frozen baseline: mobile/lib/l10n/app_en.arb keys that nothing under lib/
# renders. Generated by scripts/check_orphaned_arb_key_floor.sh. The set may
# only SHRINK (growth fails CI vs origin/main).
#
# An orphaned key is translated into 21 locales and compiled into
# AppLocalizations, yet never rendered — while the string it was written for is
# usually still hardcoded in a widget, broken for every non-English user.
#
# This list is a WORKLIST, not a set of exemptions. Every entry carries a
# trailing reason:
#   '# wire: <path>:<line>'  a live widget renders this string hardcoded.
#   '# staged: <why>'        deliberately ahead of its call site.
#   '# test-only: <where>'   only a test names it; nothing in lib/ renders it.
#                            Resolving one means editing that test too (#7968).
# A key in none of those categories — delete it from app_en.arb and every
# app_*.arb locale. Issue: #3630.
#
# The minorAccountReview* block is one decision, not eleven: sections of the
# under-16 flow (#3531) that were authored alongside the screens and never
# placed. 90 of that flow's 101 keys render across lib/screens/
# minor_account_review*.dart. This is reviewed, legally-sensitive copy already
# translated into 21 locales, so it is staged rather than deleted — build the
# sections or have product retire them; do not drop them silently.
EOF
}

# shellcheck source=lib/list_ratchet.sh
source "$SCRIPT_DIR/lib/list_ratchet.sh"
run_list_ratchet
