#!/usr/bin/env bash
# Uncancellable timer-wait ratchet (#8457, epic #4339): a `Timer(...)` whose
# value is DISCARDED and whose callback completes a `Completer` is frozen at
# ZERO across mobile/lib and mobile/packages/*/lib, in
# scripts/baseline/uncancellable_timer_wait.txt.
#
# Why: that pair is a wall-clock wait with no owner.
#
#     final completer = Completer<void>();
#     Timer(delay, completer.complete);
#     await completer.future;
#
# Nothing holds the timer, so nothing can cancel it, so `dispose()` cannot stop
# it — the awaiting code resumes into a torn-down owner once the delay elapses.
# Measured on PendingActionService's production config, disposing mid-backoff
# let the retried operation run five more times across a 62-second window, and
# the continuation then resurrected a sync timer dispose() had just cancelled.
#
# This is the PRODUCTION `Future.delayed` rule wearing a different spelling.
# check_future_delayed_production_ceiling.sh detects `Future.delayed` call sites,
# so it cannot see this shape at all — which is the whole complaint in #8457:
# moving a call site into a Timer+Completer helper turned that ratchet green
# while making lifecycle ownership strictly worse. This guard closes that hole,
# so the two are deliberately separate baselines. Do not conflate them.
#
# The fix is AsyncScope in lib/utils/async_utils.dart, which owns every timer it
# creates and cancels them on cancelAll()/dispose(). For a timeout racing a
# stream, holding the Timer in a local and cancelling it wherever the completer
# is already settled is enough.
#
# NOT counted: a timer whose value is kept (`_timer = Timer(...)`,
# `timers.add(Timer(...))`) — that is cancellable by whoever holds it; and a
# discarded timer that completes no Completer, which is ordinary
# fire-and-forget deferral and cannot strand an awaiting caller.
#
# Inspect the sites with:
#   cd mobile && dart run scripts/lib/uncancellable_timer_wait_detector.dart \
#     lib packages --path-prefix . --detail
#
# Frozen at zero: fix the call site rather than regenerating the baseline.
# Usage:
#   bash mobile/scripts/check_uncancellable_timer_wait.sh
#   (cd mobile && bash scripts/check_uncancellable_timer_wait.sh)

set -euo pipefail
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TAB="$(printf '\t')"

RATCHET_LABEL="uncancellable_timer_wait"
BASELINE_FILE="${UNCANCELLABLE_TIMER_WAIT_BASELINE_FILE:-$SCRIPT_DIR/baseline/uncancellable_timer_wait.txt}"
BASELINE_REPO_PATH="${UNCANCELLABLE_TIMER_WAIT_BASELINE_REPO_PATH:-mobile/scripts/baseline/uncancellable_timer_wait.txt}"
BASE_REF="${UNCANCELLABLE_TIMER_WAIT_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${UNCANCELLABLE_TIMER_WAIT_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="UNCANCELLABLE_TIMER_WAIT_ALLOW_NO_BASE"
DART_BIN="${UNCANCELLABLE_TIMER_WAIT_DART:-dart}"

# Scan roots, relative to MOBILE_DIR.
SCAN_DIRS="${UNCANCELLABLE_TIMER_WAIT_SCAN_DIRS:-lib packages}"

NEW_HINT="Don't await a Completer settled by a Timer nobody holds — dispose() cannot cancel it, so the awaiting code resumes into a torn-down owner. Use AsyncScope from lib/utils/async_utils.dart, which owns its timers and cancels them on dispose(); for a timeout racing a stream, hold the Timer in a local and cancel it wherever the completer is already settled. See #8457 and epic #4339."
STALE_HINT="A file stopped carrying an uncancellable timer-backed wait."
FOOTER="Uncancellable timer-backed waits are frozen at zero.
This is Future.delayed with the ratchet-visible name filed off; see
check_future_delayed_production_ceiling.sh, #8457 and epic #4339.
Inspect the sites with:
  cd mobile && dart run scripts/lib/uncancellable_timer_wait_detector.dart lib packages --path-prefix . --detail"

# Print "relpath<TAB>count" for every file with at least one site. Runs from
# MOBILE_DIR so the detector resolves package:analyzer from the app's config.
emit_current() {
  (
    cd "$MOBILE_DIR"
    # shellcheck disable=SC2086
    "$DART_BIN" run scripts/lib/uncancellable_timer_wait_detector.dart \
      $SCAN_DIRS --path-prefix "$MOBILE_DIR"
  ) | LC_ALL=C sort -t "$TAB" -k1,1
}

print_baseline_header() {
  cat <<'EOF'
# Frozen baseline: Dart files under mobile/lib and mobile/packages/*/lib holding
# a discarded Timer whose callback completes a Completer — a wall-clock wait no
# owner can cancel (format: relpath<TAB>count). Generated by
# scripts/check_uncancellable_timer_wait.sh from
# scripts/lib/uncancellable_timer_wait_detector.dart.
#
# Frozen at ZERO (#8457). Any entry here is a regression: fix the call site with
# AsyncScope (lib/utils/async_utils.dart) rather than regenerating the baseline.
EOF
}

# shellcheck source=lib/numeric_ratchet.sh
source "$SCRIPT_DIR/lib/numeric_ratchet.sh"
run_numeric_ratchet
