#!/usr/bin/env bash
# divine_ui semantic-label ceiling ratchet (#7901): app call sites that can
# render a control while relying on that public widget's English semantic-label
# default are frozen at their current per-file count. The count may only
# decrease.
#
# The detector is a real Dart AST because labels are conditional and supported
# APIs include both constructors and static helpers. A password label matters
# only when obscureText can be true; bottom-sheet labels matter only when
# onComplete can be non-null and the header can render; similar trigger and
# precedence rules apply to custom app-bar and snackbar controls. Comments,
# strings, unrelated methods, and controls proven absent are never counted.
#
# Regenerate after localizing existing call sites (never to raise):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_divine_ui_semantic_label_defaults.sh
# Run (from repo root or mobile/):
#   bash mobile/scripts/check_divine_ui_semantic_label_defaults.sh
# List individual omissions:
#   dart run scripts/lib/divine_ui_semantic_label_detector.dart lib --detail

set -euo pipefail
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TAB="$(printf '\t')"

RATCHET_LABEL="divine_ui_semantic_label_defaults"
SCAN_DIR="${DIVINE_UI_SEMANTIC_LABEL_SCAN_DIR:-$MOBILE_DIR/lib}"
PATH_PREFIX="${DIVINE_UI_SEMANTIC_LABEL_PATH_PREFIX:-$MOBILE_DIR}"
BASELINE_FILE="${DIVINE_UI_SEMANTIC_LABEL_BASELINE_FILE:-$SCRIPT_DIR/baseline/divine_ui_semantic_labels.txt}"
BASELINE_REPO_PATH="${DIVINE_UI_SEMANTIC_LABEL_BASELINE_REPO_PATH:-mobile/scripts/baseline/divine_ui_semantic_labels.txt}"
BASE_REF="${DIVINE_UI_SEMANTIC_LABEL_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${DIVINE_UI_SEMANTIC_LABEL_CEILING_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="DIVINE_UI_SEMANTIC_LABEL_CEILING_ALLOW_NO_BASE"
DART_BIN="${DIVINE_UI_SEMANTIC_LABEL_DART:-dart}"

NEW_HINT="Pass the app's localized semantic-label argument whenever the corresponding divine_ui control can render. See #7901 and .claude/rules/localization.md."
STALE_HINT="A file removed or localized every tracked semantic-label omission."
FOOTER="Public divine_ui semantic-label fallback omissions under mobile/lib
are frozen and may only decrease. Keep divine_ui l10n-free, and pass localized
labels from the app whenever the corresponding control can render. See #7901."

emit_current() {
  (
    cd "$MOBILE_DIR"
    "$DART_BIN" run scripts/lib/divine_ui_semantic_label_detector.dart \
      "$SCAN_DIR" --path-prefix "$PATH_PREFIX"
  ) | LC_ALL=C sort -t "$TAB" -k1,1
}

print_baseline_header() {
  cat <<EOF
# Frozen baseline: omitted localized semantic-label arguments on public
# divine_ui controls under mobile/lib, per file as a CEILING (format:
# relpath<TAB>count). Generated by
# scripts/check_divine_ui_semantic_label_defaults.sh from
# scripts/lib/divine_ui_semantic_label_detector.dart. A ceiling may only
# SHRINK; a new file, more omissions, or a raised ceiling fails CI vs
# ${BASE_REF}. The detector counts a label only when its control can render.
# Keep divine_ui l10n-free and pass app-localized strings at relevant call
# sites. Regenerate only after paying down omissions:
#   UPDATE_BASELINE=1 bash scripts/check_divine_ui_semantic_label_defaults.sh
EOF
}

# shellcheck source=lib/numeric_ratchet.sh
source "$SCRIPT_DIR/lib/numeric_ratchet.sh"
run_numeric_ratchet
