#!/usr/bin/env bash
# Raw-Icons ceiling ratchet (#4803, epic #4339): every Dart file under mobile/lib
# that still uses raw Material `Icons.*` is frozen at its current raw-icon count
# in scripts/baseline/raw_icons.txt, which acts as a per-file CEILING. A ceiling
# may only ever DECREASE. CI fails if:
#   • a baselined file GAINS raw icons past its recorded ceiling,
#   • a NEW file introduces raw Icons.* (not in the baseline),
#   • the in-branch baseline RAISES a ceiling or ADDS a file vs the base ref
#     (closes the bypass where a PR adds icons then reruns UPDATE_BASELINE).
# This freezes the deferred APPROX/NONE/param residue (#4803) so the migration
# can only shrink: new UI must use DivineIcon(icon: DivineIconName.X) from
# divine_ui, never raw Material Icons.* (rule: ui_theming.md → "Icons").
#
# Like check_file_size_ceiling.sh, this is a per-key NUMERIC ceiling (not a LIST
# ratchet): a file may drop raw icons freely while staying above zero without
# churning the baseline; only growth / a new file / a raised ceiling fails.
#
# Counting EXCLUDES full-line comments (^//, ^///) so the two dartdoc references
# (circular_icon_button.dart, rounded_icon_button.dart) don't count, and EXCLUDES
# generated code by PATH (mobile/lib/l10n/generated/) and by suffix
# (*.g.dart/*.freezed.dart/*.gr.dart/*.config.dart/*.mocks.dart). Scans mobile/lib
# only, so divine_ui's sanctioned MaterialIconSource escape hatch + its own
# Icons.refresh are out of scope by construction.
#
# Regenerate after MIGRATING raw icons to DivineIcon (never to raise a ceiling —
# that is what CI blocks):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_raw_icons_ceiling.sh
# Run (from repo root or mobile/): bash mobile/scripts/check_raw_icons_ceiling.sh
#
# Bash 3.2 compatible (no associative arrays) for local macOS runs — set
# comparisons use sort/join with LC_ALL=C, matching check_file_size_ceiling.sh.

set -euo pipefail

# Byte-wise, locale-independent ordering so sort/join agree across macOS (local)
# and Linux (CI); otherwise the baseline diff can falsely flag NEW/GROWTH.
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$MOBILE_DIR/.." && pwd)"
TAB="$(printf '\t')"

RATCHET_LABEL="raw_icons_ceiling"
SCAN_DIR="${RAW_ICONS_SCAN_DIR:-$MOBILE_DIR/lib}"
PATH_PREFIX="${RAW_ICONS_PATH_PREFIX:-$MOBILE_DIR}"
BASELINE_FILE="${RAW_ICONS_BASELINE_FILE:-$SCRIPT_DIR/baseline/raw_icons.txt}"
# Repo-relative path of the baseline as seen on the base ref, used by the
# anti-bypass check. Overridable so tests can diff against an already-committed
# baseline-format file (the real baseline isn't committed until this lands).
BASELINE_REPO_PATH="${RAW_ICONS_BASELINE_REPO_PATH:-mobile/scripts/baseline/raw_icons.txt}"
BASE_REF="${RAW_ICONS_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${RAW_ICONS_CEILING_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="RAW_ICONS_CEILING_ALLOW_NO_BASE"

NEW_HINT="Don't add raw Material Icons.* — use DivineIcon(icon: DivineIconName.X) from divine_ui (ui_theming.md → Icons, #4803). If no glyph exists, the icon is blocked on #4833."
STALE_HINT="A file dropped raw Icons.* (migrated to DivineIcon or removed)."
FOOTER="Raw Material Icons.* counts under mobile/lib are frozen and may only
decrease. Migrate to DivineIcon(icon: DivineIconName.X) rather than adding more.
See tasks/plan_4803.md and epics #4803 / #4339."

# Print "relpath<TAB>count" for every non-generated Dart file under SCAN_DIR that
# uses raw Icons.* (outside full-line comments), sorted by path (field 1) so
# join/comm behave deterministically.
emit_current() {
  find "$SCAN_DIR" \
    -type f -name '*.dart' \
    -not -path '*/l10n/generated/*' \
    -not -path '*/.dart_tool/*' \
    -not -path '*/build/*' \
    ! -name '*.g.dart' ! -name '*.freezed.dart' ! -name '*.gr.dart' \
    ! -name '*.config.dart' ! -name '*.mocks.dart' \
    -print0 2>/dev/null \
  | while IFS= read -r -d '' f; do
      count="$(grep -vE '^[[:space:]]*//' "$f" 2>/dev/null \
        | grep -oE 'Icons\.[A-Za-z_][A-Za-z0-9_]*' \
        | grep -c . || true)"
      count="${count//[[:space:]]/}"
      if [[ "${count:-0}" -gt 0 ]]; then
        printf '%s\t%s\n' "${f#"$PATH_PREFIX"/}" "$count"
      fi
    done \
  | LC_ALL=C sort -t "$TAB" -k1,1
}

print_baseline_header() {
  cat <<EOF
# Frozen baseline: Dart files under mobile/lib using raw Material Icons.*, each
# with its current raw-icon count as a CEILING (format: relpath<TAB>count).
# Generated by scripts/check_raw_icons_ceiling.sh. A ceiling may only SHRINK;
# more raw icons, a new file, or a raised ceiling fails CI vs ${BASE_REF}.
# Issues: #4803 (migration), #4339 (epic). Full-line comments are not counted.
# Regenerate after migrating: UPDATE_BASELINE=1 bash scripts/check_raw_icons_ceiling.sh
EOF
}

# Strip "# reason" trailing comments, comment lines, and blanks; sort by path.
strip_baseline() {
  sed 's/[[:space:]]*#.*//' | grep -v '^[[:space:]]*$' | LC_ALL=C sort -t "$TAB" -k1,1 || true
}

CURRENT="$(emit_current)"

if [[ "${UPDATE_BASELINE:-0}" == "1" ]]; then
  mkdir -p "$(dirname "$BASELINE_FILE")"
  { print_baseline_header; printf '%s\n' "$CURRENT" | grep -v '^[[:space:]]*$' || true; } > "$BASELINE_FILE"
  count="$(printf '%s\n' "$CURRENT" | grep -c . || true)"
  echo "OK [$RATCHET_LABEL]: wrote $count baseline entries to ${BASELINE_FILE#"$MOBILE_DIR"/}."
  exit 0
fi

CUR_F="$(mktemp)"; BASE_F="$(mktemp)"; MAIN_F="$(mktemp)"
trap 'rm -f "$CUR_F" "$BASE_F" "$MAIN_F"' EXIT

printf '%s\n' "$CURRENT" | grep -v '^[[:space:]]*$' > "$CUR_F" || true
if [[ -f "$BASELINE_FILE" ]]; then
  strip_baseline < "$BASELINE_FILE" > "$BASE_F"
else
  : > "$BASE_F"
fi

fail=0

# NEW: file uses raw Icons.* now but is absent from the baseline.
new="$(join -t "$TAB" -v1 "$CUR_F" "$BASE_F" || true)"
if [[ -n "$new" ]]; then
  echo "FAIL [$RATCHET_LABEL]: NEW file(s) using raw Icons.*, not in the baseline:"
  echo "$new" | sed 's/^/  /'
  echo "  -> $NEW_HINT"
  fail=1
fi

# GROWTH: baselined file now exceeds its recorded raw-icon ceiling.
grown="$(join -t "$TAB" "$CUR_F" "$BASE_F" | awk -F "$TAB" '$2 > $3 { printf "%s\t%s -> %s\n", $1, $3, $2 }' || true)"
if [[ -n "$grown" ]]; then
  echo "FAIL [$RATCHET_LABEL]: file(s) GAINED raw Icons.* past their frozen ceiling (was -> now):"
  echo "$grown" | sed 's/^/  /'
  echo "  -> $NEW_HINT"
  fail=1
fi

# STALE: baselined file no longer uses raw Icons.* (migrated or removed).
stale="$(join -t "$TAB" -v2 "$CUR_F" "$BASE_F" || true)"
if [[ -n "$stale" ]]; then
  echo "FAIL [$RATCHET_LABEL]: baselined file(s) no longer use raw Icons.*:"
  echo "$stale" | sed 's/^/  /'
  echo "  -> $STALE_HINT Lock the win by regenerating the baseline:"
  echo "     UPDATE_BASELINE=1 bash mobile/scripts/check_${RATCHET_LABEL}.sh"
  fail=1
fi

# Anti-bypass: the in-branch baseline must not RAISE a ceiling or ADD a file vs
# the base ref. On the commit that first introduces the baseline, skip this.
load_base_status=0
if ! git -C "$REPO_ROOT" rev-parse --verify --quiet "$BASE_REF" >/dev/null 2>&1; then
  git -C "$REPO_ROOT" fetch --quiet --depth=1 origin main 2>/dev/null || true
fi
if ! git -C "$REPO_ROOT" rev-parse --verify --quiet "$BASE_REF" >/dev/null 2>&1; then
  load_base_status=1
elif ! git -C "$REPO_ROOT" cat-file -e "$BASE_REF:$BASELINE_REPO_PATH" 2>/dev/null; then
  load_base_status=2
elif ! git -C "$REPO_ROOT" show "$BASE_REF:$BASELINE_REPO_PATH" 2>/dev/null | strip_baseline > "$MAIN_F"; then
  load_base_status=3
fi

case "$load_base_status" in
  0)
    added="$(join -t "$TAB" -v1 "$BASE_F" "$MAIN_F" || true)"
    raised="$(join -t "$TAB" "$BASE_F" "$MAIN_F" | awk -F "$TAB" '$2 > $3 { printf "%s\t%s -> %s\n", $1, $3, $2 }' || true)"
    if [[ -n "$added" || -n "$raised" ]]; then
      echo "FAIL [$RATCHET_LABEL]: baseline ADDED a file or RAISED a ceiling vs ${BASE_REF} (the ratchet may only shrink):"
      [[ -n "$added" ]] && echo "$added" | sed 's/^/  +added /'
      [[ -n "$raised" ]] && echo "$raised" | sed 's/^/  ^raised /'
      echo "  -> $NEW_HINT"
      fail=1
    fi
    ;;
  2)
    echo "NOTE [$RATCHET_LABEL]: no baseline on ${BASE_REF} yet (introducing the guard); skipping growth-vs-base check."
    ;;
  *)
    if [[ "$ALLOW_NO_BASE" == "1" ]]; then
      echo "NOTE [$RATCHET_LABEL]: ${BASE_REF} unavailable; skipping growth-vs-base check (${ALLOW_NO_BASE_VAR}=1, local opt-out)."
    else
      echo "FAIL [$RATCHET_LABEL]: could not load the baseline from ${BASE_REF}, so the"
      echo "  growth-vs-base ratchet cannot be verified — failing closed. Ensure ${BASE_REF}"
      echo "  is fetched (CI runs 'git fetch --depth=1 origin main' before this guard)."
      echo "  For a local run without a base ref, set ${ALLOW_NO_BASE_VAR}=1 to skip."
      fail=1
    fi
    ;;
esac

if [[ "$fail" -eq 0 ]]; then
  files="$(grep -c . "$CUR_F" || true)"
  total="$(awk -F "$TAB" '{ s += $2 } END { print s + 0 }' "$CUR_F" || true)"
  echo "OK [$RATCHET_LABEL]: $files file(s) / $total raw Icons.*, none grew (frozen, ratcheted vs ${BASE_REF})."
  exit 0
fi
echo ""
echo "$FOOTER"
exit 1
