#!/usr/bin/env bash
# Material-button ceiling ratchet (#6145, epic #4339): every Dart file under
# mobile/lib that constructs a direct Material button is frozen at its current
# count in scripts/baseline/material_buttons.txt, a per-file CEILING that may only
# ever DECREASE. New UI buttons must use DivineButton / DivineIconButton from
# divine_ui rather than a raw Material button (rule: ui_theming.md, self-review
# checklist → design system).
#
# Detector (occurrences, outside full-line comments):
#   \b(IconButton|ElevatedButton|TextButton|FilledButton|OutlinedButton
#      |BackButton|CloseButton)(\.(icon|filled|filledTonal|outlined|tonal))?\(
# The word boundary EXCLUDES the sanctioned/custom set — DivineButton,
# DivineIconButton(, RoundedIconButton(, CircularIconButton(, VideoEditorIconButton(
# — and named params like showBackButton:/AuthBackButton. The optional named-ctor
# group catches ElevatedButton.icon( and the other Material button constructors
# (.filled/.filledTonal/.outlined/.tonal), but NOT `.styleFrom(` — that returns a
# ButtonStyle (a style helper, legitimately used with DivineButton too), not a
# button widget, so it is intentionally not counted. divine_ui (where DivineButton
# lives) is a separate package, out of scope by construction.
#
# Per-key NUMERIC ceiling: a file may drop buttons freely while above zero without
# churning the baseline; only growth / new file / raised ceiling / drop-to-zero
# (STALE) fails. Generated code excluded by path (l10n/generated) and suffix.
#
# Regenerate after MIGRATING to DivineButton/DivineIconButton (never to raise):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_material_button_ceiling.sh
# Run (from repo root or mobile/): bash mobile/scripts/check_material_button_ceiling.sh

set -euo pipefail
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TAB="$(printf '\t')"

RATCHET_LABEL="material_button_ceiling"
SCAN_DIR="${MATERIAL_BUTTON_SCAN_DIR:-$MOBILE_DIR/lib}"
PATH_PREFIX="${MATERIAL_BUTTON_PATH_PREFIX:-$MOBILE_DIR}"
BASELINE_FILE="${MATERIAL_BUTTON_BASELINE_FILE:-$SCRIPT_DIR/baseline/material_buttons.txt}"
BASELINE_REPO_PATH="${MATERIAL_BUTTON_BASELINE_REPO_PATH:-mobile/scripts/baseline/material_buttons.txt}"
BASE_REF="${MATERIAL_BUTTON_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${MATERIAL_BUTTON_CEILING_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="MATERIAL_BUTTON_CEILING_ALLOW_NO_BASE"

DETECT_RE='\b(IconButton|ElevatedButton|TextButton|FilledButton|OutlinedButton|BackButton|CloseButton)(\.(icon|filled|filledTonal|outlined|tonal))?\('

NEW_HINT="Don't add direct Material buttons — use DivineButton / DivineIconButton from divine_ui. ui_theming.md + self-review checklist; #6145."
STALE_HINT="A file dropped its Material buttons (migrated to DivineButton or removed)."
FOOTER="Direct Material button counts under mobile/lib are frozen and may only
decrease. Use DivineButton / DivineIconButton rather than adding more.
See ui_theming.md and epics #6145 / #4339."

# Print "relpath<TAB>count" for every non-generated Dart file under SCAN_DIR that
# constructs a direct Material button (outside full-line comments), sorted by path.
emit_current() {
  find "$SCAN_DIR" \
    -type f -name '*.dart' \
    -not -path '*/l10n/generated/*' \
    -not -path '*/.dart_tool/*' \
    -not -path '*/build/*' \
    ! -name '*.g.dart' ! -name '*.freezed.dart' ! -name '*.gr.dart' \
    ! -name '*.config.dart' ! -name '*.mocks.dart' \
    -print0 2>/dev/null \
  | while IFS= read -r -d '' f; do
      count="$(grep -vE '^[[:space:]]*//' "$f" 2>/dev/null \
        | grep -oE "$DETECT_RE" \
        | grep -c . || true)"
      count="${count//[[:space:]]/}"
      if [[ "${count:-0}" -gt 0 ]]; then
        printf '%s\t%s\n' "${f#"$PATH_PREFIX"/}" "$count"
      fi
    done \
  | LC_ALL=C sort -t "$TAB" -k1,1
}

print_baseline_header() {
  cat <<EOF
# Frozen baseline: Dart files under mobile/lib constructing a direct Material
# button (IconButton/ElevatedButton/TextButton/FilledButton/OutlinedButton/
# BackButton/CloseButton, incl .icon), each with its current count as a CEILING
# (format: relpath<TAB>count). Generated by scripts/check_material_button_ceiling.sh.
# A ceiling may only SHRINK; more buttons, a new file, or a raised ceiling fails CI
# vs ${BASE_REF}. Use DivineButton / DivineIconButton. Full-line comments are not
# counted. Issue: #6145. Regenerate after migrating:
#   UPDATE_BASELINE=1 bash scripts/check_material_button_ceiling.sh
EOF
}

# shellcheck source=lib/numeric_ratchet.sh
source "$SCRIPT_DIR/lib/numeric_ratchet.sh"
run_numeric_ratchet
