#!/usr/bin/env bash
# Package CI floor (issues #3574 / #3575): every package under mobile/packages
# must carry BOTH its own analysis_options.yaml and a per-package CI workflow.
#
# Two checks:
#   1. analysis_options.yaml presence — HARD invariant, no exceptions. Without
#      a local options file the analyzer walks up to mobile/analysis_options.yaml
#      and the package silently inherits the app's relaxed config (which
#      downgrades real type errors such as invalid_assignment to ignored).
#   2. Workflow presence — shrink-only ratchet via lib/list_ratchet.sh. The
#      committed exception list (baseline/package_ci_exceptions.txt) may only
#      shrink; new packages must ship .github/workflows/<pkg>.yaml.
#      Accepted filenames: <pkg>.yaml, <pkg>.yml, <pkg>_ci.yaml, <pkg>_ci.yml
#      (models_ci.yaml and cache_sync.yml are existing precedents).
#
# Regenerate the baseline only after REMOVING an exception (never to add one):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_package_ci_floor.sh
# Usage (from the repo root or mobile/): bash mobile/scripts/check_package_ci_floor.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$MOBILE_DIR/.." && pwd)"

missing_options=""
for pubspec in "$MOBILE_DIR"/packages/*/pubspec.yaml; do
  [ -f "$pubspec" ] || continue
  pkg_dir="$(dirname "$pubspec")"
  if [ ! -f "$pkg_dir/analysis_options.yaml" ]; then
    missing_options="${missing_options}  $(basename "$pkg_dir")"$'\n'
  fi
done
if [ -n "$missing_options" ]; then
  echo "FAIL [package_ci_floor]: package(s) missing analysis_options.yaml:"
  printf '%s' "$missing_options"
  echo "  -> Without a local options file the analyzer silently inherits the"
  echo "     app's relaxed config (real type errors get downgraded). Add:"
  echo "       include: package:very_good_analysis/analysis_options.yaml"
  exit 1
fi

RATCHET_LABEL="package_ci_floor"
BASELINE_FILE="$SCRIPT_DIR/baseline/package_ci_exceptions.txt"
BASELINE_REPO_PATH="mobile/scripts/baseline/package_ci_exceptions.txt"
BASE_REF="${PACKAGE_CI_FLOOR_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${PACKAGE_CI_FLOOR_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="PACKAGE_CI_FLOOR_ALLOW_NO_BASE"
NEW_HINT="A package under mobile/packages has no per-package CI workflow. Add .github/workflows/<pkg>.yaml (copy an existing VGV flutter_package workflow and set min_coverage to the package's measured coverage)."
STALE_HINT="A baselined package gained a workflow (or was removed)."
FOOTER="Workflow-less packages are frozen and may only decrease. Add a
.github/workflows/<pkg>.yaml for new packages — do not extend the exception
list. See issues #3574 / #3575."

emit_current() {
  local pubspec pkg
  for pubspec in "$MOBILE_DIR"/packages/*/pubspec.yaml; do
    [ -f "$pubspec" ] || continue
    pkg="$(basename "$(dirname "$pubspec")")"
    if [ ! -f "$REPO_ROOT/.github/workflows/${pkg}.yaml" ] &&
      [ ! -f "$REPO_ROOT/.github/workflows/${pkg}.yml" ] &&
      [ ! -f "$REPO_ROOT/.github/workflows/${pkg}_ci.yaml" ] &&
      [ ! -f "$REPO_ROOT/.github/workflows/${pkg}_ci.yml" ]; then
      echo "$pkg"
    fi
  done | LC_ALL=C sort -u
}

print_baseline_header() {
  cat <<'EOF'
# Frozen exception list: packages under mobile/packages WITHOUT a per-package
# CI workflow in .github/workflows/. Generated by
# scripts/check_package_ci_floor.sh. The set may only SHRINK (growth fails CI
# vs origin/main). A trailing '# reason' marks why the exception exists.
# Issues: #3574 / #3575.
EOF
}

# shellcheck source=lib/list_ratchet.sh
. "$SCRIPT_DIR/lib/list_ratchet.sh"
run_list_ratchet
