#!/usr/bin/env bash
# File-size ceiling ratchet (epic #4339): every Dart file under mobile/lib whose
# length exceeds FILE_SIZE_THRESHOLD (default 800) lines is frozen at its current
# line count in scripts/baseline/file_sizes.txt, which acts as a per-file CEILING.
# A ceiling may only ever DECREASE. CI fails if:
#   • a baselined file GROWS past its recorded ceiling,
#   • a NEW file crosses the threshold,
#   • the in-branch baseline RAISES a ceiling or ADDS a file vs the base ref
#     (closes the bypass where a PR grows a file then reruns UPDATE_BASELINE).
# This stops the god-file accretion #4339 is losing the race against — there was
# no file-size gate before (only test-scoped ratchets existed).
#
# Unlike the LIST ratchets (lib/list_ratchet.sh, which freeze a SET membership),
# this is a per-key NUMERIC ceiling: a file may shrink freely while staying over
# the threshold without churning the baseline; only growth/new-file fails.
#
# Excludes generated code by PATH (mobile/lib/l10n/generated/) and by suffix
# (*.g.dart/*.freezed.dart/*.gr.dart/*.config.dart/*.mocks.dart). The l10n
# generated files lack codegen suffixes, so the PATH exclusion is required —
# without it the count is inflated by ~19 files.
#
# Regenerate after SHRINKING a file below its ceiling or below the threshold
# (never to raise a ceiling — that is what CI blocks):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_file_size_ceiling.sh
# Run (from repo root or mobile/): bash mobile/scripts/check_file_size_ceiling.sh
#
# Bash 3.2 compatible (no associative arrays) for local macOS runs — set
# comparisons use sort/join with LC_ALL=C, matching lib/list_ratchet.sh.

set -euo pipefail

# Byte-wise, locale-independent ordering so sort/join agree across macOS (local)
# and Linux (CI); otherwise the baseline diff can falsely flag NEW/GROWTH.
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$MOBILE_DIR/.." && pwd)"
TAB="$(printf '\t')"

RATCHET_LABEL="file_size_ceiling"
THRESHOLD="${FILE_SIZE_THRESHOLD:-800}"
SCAN_DIR="${FILE_SIZE_SCAN_DIR:-$MOBILE_DIR/lib}"
PATH_PREFIX="${FILE_SIZE_PATH_PREFIX:-$MOBILE_DIR}"
BASELINE_FILE="${FILE_SIZE_BASELINE_FILE:-$SCRIPT_DIR/baseline/file_sizes.txt}"
BASELINE_REPO_PATH="mobile/scripts/baseline/file_sizes.txt"
BASE_REF="${FILE_SIZE_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${FILE_SIZE_CEILING_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="FILE_SIZE_CEILING_ALLOW_NO_BASE"

NEW_HINT="Don't add a Dart file over ${THRESHOLD} lines, and don't grow a baselined one. Extract widget/class concerns into focused files (epic #4339)."
STALE_HINT="A file dropped below its ceiling or below ${THRESHOLD} lines (or was removed)."
FOOTER="File sizes over ${THRESHOLD} lines are frozen and may only decrease. Split
oversized files into focused widget/class/service units rather than growing them.
See tasks/plan_epics_4335-4339_4744_4203_570.md (PR-1) and epic #4339."

# Print "relpath<TAB>loc" for every oversized non-generated Dart file, sorted by
# path (field 1) so join/comm behave deterministically.
emit_current() {
  find "$SCAN_DIR" \
    -type f -name '*.dart' \
    -not -path '*/l10n/generated/*' \
    -not -path '*/.dart_tool/*' \
    -not -path '*/build/*' \
    ! -name '*.g.dart' ! -name '*.freezed.dart' ! -name '*.gr.dart' \
    ! -name '*.config.dart' ! -name '*.mocks.dart' \
    -print0 2>/dev/null \
  | while IFS= read -r -d '' f; do
      loc="$(wc -l < "$f" | tr -d '[:space:]')"
      if [[ "${loc:-0}" -gt "$THRESHOLD" ]]; then
        printf '%s\t%s\n' "${f#"$PATH_PREFIX"/}" "$loc"
      fi
    done \
  | LC_ALL=C sort -t "$TAB" -k1,1
}

print_baseline_header() {
  cat <<EOF
# Frozen baseline: Dart files under mobile/lib over ${THRESHOLD} lines, each with
# its current line count as a CEILING (format: relpath<TAB>loc). Generated by
# scripts/check_file_size_ceiling.sh. A ceiling may only SHRINK; growth, a new
# oversized file, or a raised ceiling fails CI vs ${BASE_REF}. Epic: #4339.
# Regenerate after shrinking: UPDATE_BASELINE=1 bash scripts/check_file_size_ceiling.sh
EOF
}

# Strip "# reason" trailing comments, comment lines, and blanks; sort by path.
strip_baseline() {
  sed 's/[[:space:]]*#.*//' | grep -v '^[[:space:]]*$' | LC_ALL=C sort -t "$TAB" -k1,1 || true
}

CURRENT="$(emit_current)"

if [[ "${UPDATE_BASELINE:-0}" == "1" ]]; then
  mkdir -p "$(dirname "$BASELINE_FILE")"
  { print_baseline_header; printf '%s\n' "$CURRENT" | grep -v '^[[:space:]]*$' || true; } > "$BASELINE_FILE"
  count="$(printf '%s\n' "$CURRENT" | grep -c . || true)"
  echo "OK [$RATCHET_LABEL]: wrote $count baseline entries to ${BASELINE_FILE#"$MOBILE_DIR"/}."
  exit 0
fi

CUR_F="$(mktemp)"; BASE_F="$(mktemp)"; MAIN_F="$(mktemp)"
trap 'rm -f "$CUR_F" "$BASE_F" "$MAIN_F"' EXIT

printf '%s\n' "$CURRENT" | grep -v '^[[:space:]]*$' > "$CUR_F" || true
if [[ -f "$BASELINE_FILE" ]]; then
  strip_baseline < "$BASELINE_FILE" > "$BASE_F"
else
  : > "$BASE_F"
fi

fail=0

# NEW: oversized file present now but absent from the baseline.
new="$(join -t "$TAB" -v1 "$CUR_F" "$BASE_F" || true)"
if [[ -n "$new" ]]; then
  echo "FAIL [$RATCHET_LABEL]: NEW file(s) over ${THRESHOLD} lines, not in the baseline:"
  echo "$new" | sed 's/^/  /'
  echo "  -> $NEW_HINT"
  fail=1
fi

# GROWTH: baselined file now exceeds its recorded ceiling.
grown="$(join -t "$TAB" "$CUR_F" "$BASE_F" | awk -F "$TAB" '$2 > $3 { printf "%s\t%s -> %s\n", $1, $3, $2 }' || true)"
if [[ -n "$grown" ]]; then
  echo "FAIL [$RATCHET_LABEL]: file(s) GREW past their frozen ceiling (was -> now):"
  echo "$grown" | sed 's/^/  /'
  echo "  -> $NEW_HINT"
  fail=1
fi

# STALE: baselined file no longer over threshold (shrank below it or removed).
stale="$(join -t "$TAB" -v2 "$CUR_F" "$BASE_F" || true)"
if [[ -n "$stale" ]]; then
  echo "FAIL [$RATCHET_LABEL]: baselined file(s) no longer over ${THRESHOLD} lines:"
  echo "$stale" | sed 's/^/  /'
  echo "  -> $STALE_HINT Lock the win by regenerating the baseline:"
  echo "     UPDATE_BASELINE=1 bash mobile/scripts/check_${RATCHET_LABEL}.sh"
  fail=1
fi

# Anti-bypass: the in-branch baseline must not RAISE a ceiling or ADD a file vs
# the base ref. On the commit that first introduces the baseline, skip this.
load_base_status=0
if ! git -C "$REPO_ROOT" rev-parse --verify --quiet "$BASE_REF" >/dev/null 2>&1; then
  git -C "$REPO_ROOT" fetch --quiet --depth=1 origin main 2>/dev/null || true
fi
if ! git -C "$REPO_ROOT" rev-parse --verify --quiet "$BASE_REF" >/dev/null 2>&1; then
  load_base_status=1
elif ! git -C "$REPO_ROOT" cat-file -e "$BASE_REF:$BASELINE_REPO_PATH" 2>/dev/null; then
  load_base_status=2
elif ! git -C "$REPO_ROOT" show "$BASE_REF:$BASELINE_REPO_PATH" 2>/dev/null | strip_baseline > "$MAIN_F"; then
  load_base_status=3
fi

case "$load_base_status" in
  0)
    added="$(join -t "$TAB" -v1 "$BASE_F" "$MAIN_F" || true)"
    raised="$(join -t "$TAB" "$BASE_F" "$MAIN_F" | awk -F "$TAB" '$2 > $3 { printf "%s\t%s -> %s\n", $1, $3, $2 }' || true)"
    if [[ -n "$added" || -n "$raised" ]]; then
      echo "FAIL [$RATCHET_LABEL]: baseline ADDED a file or RAISED a ceiling vs ${BASE_REF} (the ratchet may only shrink):"
      [[ -n "$added" ]] && echo "$added" | sed 's/^/  +added /'
      [[ -n "$raised" ]] && echo "$raised" | sed 's/^/  ^raised /'
      echo "  -> $NEW_HINT"
      fail=1
    fi
    ;;
  2)
    echo "NOTE [$RATCHET_LABEL]: no baseline on ${BASE_REF} yet (introducing the guard); skipping growth-vs-base check."
    ;;
  *)
    if [[ "$ALLOW_NO_BASE" == "1" ]]; then
      echo "NOTE [$RATCHET_LABEL]: ${BASE_REF} unavailable; skipping growth-vs-base check (${ALLOW_NO_BASE_VAR}=1, local opt-out)."
    else
      echo "FAIL [$RATCHET_LABEL]: could not load the baseline from ${BASE_REF}, so the"
      echo "  growth-vs-base ratchet cannot be verified — failing closed. Ensure ${BASE_REF}"
      echo "  is fetched (CI runs 'git fetch --depth=1 origin main' before this guard)."
      echo "  For a local run without a base ref, set ${ALLOW_NO_BASE_VAR}=1 to skip."
      fail=1
    fi
    ;;
esac

if [[ "$fail" -eq 0 ]]; then
  count="$(grep -c . "$CUR_F" || true)"
  echo "OK [$RATCHET_LABEL]: $count file(s) over ${THRESHOLD} lines, none grew (frozen, ratcheted vs ${BASE_REF})."
  exit 0
fi
echo ""
echo "$FOOTER"
exit 1
