#!/usr/bin/env bash
# Production Future.delayed-ceiling ratchet (epic #4339): executable call sites
# under mobile/lib are frozen as per-file numeric ceilings in
# scripts/baseline/future_delayed_production.txt and may only ever SHRINK.
# `Future.delayed` in app code encodes wall-clock timing and is a frequent source
# of races and flaky behavior; the project rule (.claude/CLAUDE.md) is to avoid it
# in app code in favor of explicit async coordination (AnimatedSwitcher /
# animation controllers / stream listeners / completers).
#
# This is the PRODUCTION counterpart to check_future_delayed_ceiling.sh (which is
# TEST-scoped under epic #4337, WS-2). They are deliberately separate baselines:
# this one guards mobile/lib, that one guards mobile/test. Do not conflate them.
#
# The detector scopes to mobile/lib/**/*.dart and EXCLUDES:
#   • generated files (*.g.dart / *.freezed.dart / *.gr.dart / *.config.dart /
#     *.mocks.dart) and the l10n generated dir (mobile/lib/l10n/generated/),
#   • build / .dart_tool artifacts.
#
# It counts CODE ONLY: each file is piped through lib/dart_code_only.awk first,
# so comments and string-literal bodies are stripped before the match. This
# matches the seven sibling ratchets that already do it (raw colors, raw
# TextStyle, Material buttons, raw dialogs, implicit font color, unsafe back
# pop, profile read/write split). Without it a file that merely *mentions*
# Future.delayed counts as an offender — which is how lib/utils/async_utils.dart
# (8 mentions, all doc examples of what NOT to write) and the dartdoc reference
# on _reorderAnimController in video_editor_timeline_clip_strip.dart (which
# documents that the file deliberately does NOT use it) both sat in the baseline,
# making the stated goal of reaching zero unreachable by construction (#6934).
#
# Regenerate after removing a Future.delayed call site (never to add one):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_future_delayed_production_ceiling.sh
# Usage:
#   bash mobile/scripts/check_future_delayed_production_ceiling.sh
#   (cd mobile && bash scripts/check_future_delayed_production_ceiling.sh)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TAB="$(printf '\t')"

RATCHET_LABEL="future_delayed_production_ceiling"
BASELINE_FILE="$SCRIPT_DIR/baseline/future_delayed_production.txt"
BASELINE_REPO_PATH="mobile/scripts/baseline/future_delayed_production.txt"
BASE_REF="${FUTURE_DELAYED_PROD_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${FUTURE_DELAYED_PROD_CEILING_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="FUTURE_DELAYED_PROD_CEILING_ALLOW_NO_BASE"
LEGACY_LIST_BASELINE_MIGRATION=1
REQUIRE_BASELINE_UPDATE_ON_DECREASE=1
NEW_HINT="Don't add Future.delayed to app code — use explicit async coordination (AnimatedSwitcher / animation controllers / stream listeners / completers), not a wall-clock wait. See .claude/CLAUDE.md and epic #4339."
STALE_HINT="A production Future.delayed call was removed."
FOOTER="Future.delayed in mobile/lib is frozen and may only decrease. Replace it
with explicit async coordination rather than a longer wall-clock wait. See
.claude/CLAUDE.md and epic #4339."

emit_current() {
  find "$MOBILE_DIR/lib" \
    -not -path "*/l10n/generated/*" \
    -not -path "*/.dart_tool/*" -not -path "*/build/*" \
    -name "*.dart" \
    ! -name "*.g.dart" ! -name "*.freezed.dart" ! -name "*.gr.dart" \
    ! -name "*.config.dart" ! -name "*.mocks.dart" \
    -print0 2>/dev/null \
  | while IFS= read -r -d '' f; do
      # The final grep -c consumes the whole stream. `-q` would exit on the first
      # match, so awk would die of SIGPIPE; under pipefail the pipeline would
      # report 141 — silently dropping every file whose match lands before awk
      # finishes writing. Undercounting is the dangerous direction here.
      count="$(awk -f "$SCRIPT_DIR/lib/dart_code_only.awk" "$f" 2>/dev/null \
        | grep -oE "Future\.delayed" | grep -c . || true)"
      count="${count//[[:space:]]/}"
      if [[ "${count:-0}" -gt 0 ]]; then
        printf '%s\t%s\n' "${f#"$MOBILE_DIR"/}" "$count"
      fi
    done | LC_ALL=C sort -t "$TAB" -k1,1 || true
}

print_baseline_header() {
  cat <<'EOF'
# Frozen baseline: executable Future.delayed call sites under
# mobile/lib/**/*.dart, stored as relpath<TAB>count per file. Generated by
# scripts/check_future_delayed_production_ceiling.sh. Each ceiling may only
# SHRINK (growth fails CI vs origin/main). Replace Future.delayed with explicit
# async coordination. Epic: #4339 (production counterpart of the test-scoped
# #4337 WS-2 ratchet).
EOF
}

# shellcheck source=lib/numeric_ratchet.sh
source "$SCRIPT_DIR/lib/numeric_ratchet.sh"
run_numeric_ratchet
