#!/usr/bin/env bash
# Shared-channel raw-install ratchet (#5738). The runtime heal-and-blame tearDown
# (test/flutter_test_config.dart + test/helpers/shared_channel_override.dart) is
# the PRIMARY guard for the merged-isolate leak class; this static ratchet is
# belt-and-suspenders. It freezes the set of test files that raw-install one of
# the five setupTestEnvironment-owned MethodChannels via setMockMethodCallHandler
# WITHOUT routing through the sanctioned helpers (overrideSharedChannel /
# restoreSharedChannelDefaults). The set may only ever SHRINK: a new raw
# shared-channel install fails CI. See lib/list_ratchet.sh for NEW/STALE/GROWTH
# semantics and .claude/rules/testing.md (VGV merged isolate).
#
# Detector (grep proxy): a *_test.dart / test helper .dart under mobile/test that
# references one of the five shared channel NAME literals AND calls
# setMockMethodCallHandler AND does NOT use a harness-aware API
# (overrideSharedChannel / restoreSharedChannelDefaults / restoreSharedChannel).
# The two harness-owning files (test_setup.dart, shared_channel_override.dart)
# are excluded — they install the canonical handlers by design. Being a grep
# proxy it cannot prove intent; the sanctioned helper is the canonical fix and
# the baseline is the escape hatch for pre-existing, runtime-safe installs.
#
# Regenerate ONLY after REMOVING a raw install (never to add one):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_shared_channel_overrides.sh
# Usage (from the repo root or mobile/):
#   bash mobile/scripts/check_shared_channel_overrides.sh

set -euo pipefail
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

RATCHET_LABEL="shared_channel_overrides"
BASELINE_FILE="$SCRIPT_DIR/baseline/shared_channel_raw_installs.txt"
BASELINE_REPO_PATH="mobile/scripts/baseline/shared_channel_raw_installs.txt"
BASE_REF="${SHARED_CHANNEL_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${SHARED_CHANNEL_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="SHARED_CHANNEL_ALLOW_NO_BASE"
NEW_HINT="A test raw-installs a shared MethodChannel (flutter_secure_storage / openvine.secure_storage / device_info / path_provider / image_picker) via setMockMethodCallHandler without the sanctioned helper. Use overrideSharedChannel(channel, handler) (auto-restores) or, for a full reset, restoreSharedChannelDefaults(). See .claude/rules/testing.md (VGV merged isolate) and #5738."
STALE_HINT="A test stopped raw-installing a shared channel (migrated to overrideSharedChannel)."
FOOTER="Raw shared-channel installs are frozen and may only decrease. Route new
overrides through overrideSharedChannel(...) so the heal-and-blame tearDown
leaves them in place for your scope and auto-restores the canonical handler.
See test/helpers/shared_channel_override.dart and #5738."

_SHARED_CHANNEL_NAMES='plugins.it_nomads.com/flutter_secure_storage|openvine.secure_storage|plugins.flutter.io/device_info|plugins.flutter.io/path_provider|plugins.flutter.io/image_picker'
_HARNESS_AWARE='overrideSharedChannel|restoreSharedChannelDefaults|restoreSharedChannel\('

emit_current() {
  local f rel
  for f in $(grep -rlE "$_SHARED_CHANNEL_NAMES" "$MOBILE_DIR/test" \
      --include='*.dart' 2>/dev/null | LC_ALL=C sort); do
    rel="${f#"$MOBILE_DIR"/}"
    case "$rel" in
      test/test_setup.dart | test/helpers/shared_channel_override.dart) continue ;;
    esac
    if grep -qE 'setMockMethodCallHandler' "$f" \
        && ! grep -qE "$_HARNESS_AWARE" "$f"; then
      printf '%s\n' "$rel"
    fi
  done
}

print_baseline_header() {
  cat <<'EOF'
# Frozen baseline (#5738): test files that raw-install a setupTestEnvironment-owned
# shared MethodChannel via setMockMethodCallHandler without the sanctioned helper
# (overrideSharedChannel / restoreSharedChannelDefaults). Generated by
# scripts/check_shared_channel_overrides.sh. The set may only SHRINK (growth fails
# CI vs origin/main). The runtime heal-and-blame tearDown is the primary guard;
# this ratchet just stops new raw installs from accruing. Migrate an entry by
# routing it through overrideSharedChannel(...), then shrink this baseline.
EOF
}

# shellcheck source=lib/list_ratchet.sh
source "$SCRIPT_DIR/lib/list_ratchet.sh"
run_list_ratchet
