#!/usr/bin/env bash
# Dependency-provenance guard (issues #3655 / #3363 AC3): the set of
# dependencies resolved from somewhere other than pub.dev — git sources, path
# sources, hosted packages from non-pub.dev registries, and
# dependency_overrides — is frozen in
# scripts/baseline/dependency_provenance.txt and may only ever SHRINK. See
# lib/list_ratchet.sh for the NEW/STALE/GROWTH semantics.
#
# Two detectors, because neither file alone sees everything:
#   • pubspec.lock  — git, path, and hosted registry sources. Only the lock
#     records `resolved-ref`, which is what proves a git ref is immutable (see
#     lib/dependency_provenance.awk).
#   • pubspec.yaml  — `dependency_overrides` entries. A version-only override
#     (e.g. `device_info_plus: ^10.1.2`) still resolves to `source: hosted`, so
#     it leaves no trace in the lock at all.
#
# A MUTABLE git ref FAILS UNCONDITIONALLY, even if baselined. The baseline
# sanctions *which* dependencies may come from a non-pub source; it never
# sanctions a movable ref, because the whole point is that the build cannot be
# changed underneath us. This is the AC3 clause "CI should reject mutable git
# refs" — the allowlist applies only to the "unexpected path overrides" clause.
#
# Note the detectors read the lockfile and git-tracked pubspecs, never the
# filesystem layout: mobile/overrides/ carries untracked leftovers from removed
# vendored forks, and a directory-existence check would flag those forever.
#
# Regenerate only after REMOVING an entry (never to add one):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_dependency_provenance.sh
# Usage (from the repo root or mobile/): bash mobile/scripts/check_dependency_provenance.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$MOBILE_DIR/.." && pwd)"

# Overridable so the detector can be driven against fixtures from a test.
LOCKFILE="${PROVENANCE_LOCKFILE:-$MOBILE_DIR/pubspec.lock}"
PUBSPEC_LIST="${PROVENANCE_PUBSPEC_LIST:-}"
PUBSPEC_ROOT="${PROVENANCE_PUBSPEC_ROOT:-$REPO_ROOT}"

RATCHET_LABEL="dependency_provenance"
BASELINE_FILE="${DEPENDENCY_PROVENANCE_BASELINE_FILE:-$SCRIPT_DIR/baseline/dependency_provenance.txt}"
BASELINE_REPO_PATH="${DEPENDENCY_PROVENANCE_BASELINE_REPO_PATH:-mobile/scripts/baseline/dependency_provenance.txt}"
BASE_REF="${DEPENDENCY_PROVENANCE_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${DEPENDENCY_PROVENANCE_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="DEPENDENCY_PROVENANCE_ALLOW_NO_BASE"
NEW_HINT="A dependency now resolves from a git source, a local path, a non-pub.dev hosted registry, or a dependency_overrides entry that is not in the baseline. Prefer a published pub.dev version. If the override is genuinely required, add it to the baseline with a trailing '# reason' naming its tracking issue."
STALE_HINT="A baselined dependency returned to a plain pub.dev source."
FOOTER="Non-pub dependency sources are frozen and may only decrease. They weaken
supply-chain reproducibility: a path override bypasses registry provenance, and
a git ref or hosted registry can change underneath the build. See issues
#3655 / #3363."

_tracked_pubspecs() {
  if [ -n "$PUBSPEC_LIST" ]; then
    cat "$PUBSPEC_LIST"
  else
    git -C "$REPO_ROOT" ls-files '*pubspec.yaml'
  fi
}

# Emit `override:<repo-relative pubspec>:<package>` for each dependency_overrides
# entry. Keys are the 2-space-indented children of the block; a nested `path:` or
# `git:` line sits deeper and must not be mistaken for an entry.
_emit_overrides() {
  local rel abs
  while IFS= read -r rel; do
    [ -n "$rel" ] || continue
    abs="$PUBSPEC_ROOT/$rel"
    if [ ! -f "$abs" ]; then
      echo "FAIL [$RATCHET_LABEL]: listed pubspec not found: $rel" >&2
      return 1
    fi
    awk -v file="$rel" '
      /^dependency_overrides:[[:space:]]*$/ { inblock = 1; next }
      inblock && /^[A-Za-z]/ { inblock = 0 }
      inblock && /^  [A-Za-z0-9_]+:/ {
        key = $0
        sub(/^  /, "", key)
        sub(/:.*$/, "", key)
        print "override:" file ":" key
      }
    ' "$abs"
  done < <(_tracked_pubspecs)
}

emit_current() {
  local current_file
  current_file="$(mktemp)"
  if [ ! -f "$LOCKFILE" ]; then
    echo "FAIL [$RATCHET_LABEL]: lockfile not found: $LOCKFILE" >&2
    rm -f "$current_file"
    return 1
  fi
  awk -f "$SCRIPT_DIR/lib/dependency_provenance.awk" "$LOCKFILE" > "$current_file"
  if ! _emit_overrides >> "$current_file"; then
    rm -f "$current_file"
    return 1
  fi
  grep -v '^$' "$current_file" | LC_ALL=C sort -u || true
  rm -f "$current_file"
}

print_baseline_header() {
  cat <<'EOF'
# Frozen baseline: dependencies resolved from somewhere other than pub.dev —
# git sources (git:<pkg>:<url>:PINNED), path sources (path:<pkg>:<path>),
# hosted packages from other registries (hosted:<pkg>:<url>), and
# dependency_overrides entries (override:<pubspec>:<pkg>). Generated by
# scripts/check_dependency_provenance.sh. The set may only SHRINK (growth fails
# CI vs origin/main). Every entry carries a trailing '# reason' naming the
# tracking issue that owns its removal.
#
# A git:<pkg>:<url>:MUTABLE entry can never be baselined — the guard rejects a
# movable git ref unconditionally. Issues: #3655 / #3363.
EOF
}

CURRENT="$(emit_current)"

# AC3's "reject mutable git refs" clause — enforced before, and independently of,
# the allowlist, so it cannot be silenced by regenerating the baseline.
mutable="$(printf '%s\n' "$CURRENT" | grep ':MUTABLE$' || true)"
if [ -n "$mutable" ]; then
  echo "FAIL [$RATCHET_LABEL]: git dependenc(y/ies) pinned to a MOVABLE ref:"
  echo "$mutable" | sed 's/^/  /'
  echo "  -> A branch or tag can be repointed, so the build is not reproducible."
  echo "     Pin the full 40-character commit SHA instead, keeping the tag in a"
  echo "     trailing comment:  ref: <sha> # tag v1.2.3"
  echo ""
  echo "$FOOTER"
  exit 1
fi

emit_current() {
  printf '%s\n' "$CURRENT"
}

# shellcheck source=lib/list_ratchet.sh
source "$SCRIPT_DIR/lib/list_ratchet.sh"
run_list_ratchet
