#!/usr/bin/env bash
# Raw-TextStyle ceiling ratchet (#6145, epic #4339): every Dart file under
# mobile/lib that constructs a raw `TextStyle(...)` is frozen at its current
# count in scripts/baseline/raw_textstyle.txt, which acts as a per-file CEILING.
# A ceiling may only ever DECREASE. New UI text styling must go through a
# VineTheme font helper (VineTheme.bodyMediumFont(), titleLargeFont(), …) rather
# than an inline TextStyle constructor (rule: ui_theming.md → "Typography").
#
# Detector: `\bTextStyle\(` (occurrences), in code only — comments and string
# literals are stripped first (see lib/dart_code_only.awk). The word
# boundary EXCLUDES DefaultTextStyle( / AnimatedDefaultTextStyle( / setTextStyle(
# (legitimate Flutter widgets, not inline-style drift). `.copyWith()` on an
# existing theme style is not a `TextStyle(` token, so building on VineTheme
# styles stays free. divine_ui (where the font helpers live) is a separate
# package, so its own TextStyle definitions are out of scope by construction.
#
# Like check_raw_icons_ceiling.sh this is a per-key NUMERIC ceiling; a file may
# drop styles freely while staying above zero without churning the baseline —
# only growth / a new file / a raised ceiling / a drop-to-zero (STALE) fails.
# Generated code is excluded by path (l10n/generated) and suffix.
#
# Regenerate after MIGRATING styles to VineTheme (never to raise a ceiling):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_raw_textstyle_ceiling.sh
# Run (from repo root or mobile/): bash mobile/scripts/check_raw_textstyle_ceiling.sh

set -euo pipefail
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TAB="$(printf '\t')"

RATCHET_LABEL="raw_textstyle_ceiling"
SCAN_DIR="${RAW_TEXTSTYLE_SCAN_DIR:-$MOBILE_DIR/lib}"
PATH_PREFIX="${RAW_TEXTSTYLE_PATH_PREFIX:-$MOBILE_DIR}"
BASELINE_FILE="${RAW_TEXTSTYLE_BASELINE_FILE:-$SCRIPT_DIR/baseline/raw_textstyle.txt}"
BASELINE_REPO_PATH="${RAW_TEXTSTYLE_BASELINE_REPO_PATH:-mobile/scripts/baseline/raw_textstyle.txt}"
BASE_REF="${RAW_TEXTSTYLE_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${RAW_TEXTSTYLE_CEILING_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="RAW_TEXTSTYLE_CEILING_ALLOW_NO_BASE"

DETECT_RE='\bTextStyle\('

NEW_HINT="Don't add raw TextStyle(...) — use a VineTheme font helper (VineTheme.bodyMediumFont(), titleLargeFont(), …). ui_theming.md → Typography; #6145. Build on a theme style with .copyWith(...) if you need a variant. Only real code counts (comments and string literals are stripped)."
STALE_HINT="A file dropped its raw TextStyle( (migrated to VineTheme or removed)."
FOOTER="Raw TextStyle( counts under mobile/lib are frozen and may only decrease.
Migrate inline styles to VineTheme.*Font() helpers rather than adding more.
See ui_theming.md (Typography) and epics #6145 / #4339."

# Print "relpath<TAB>count" for every non-generated Dart file under SCAN_DIR that
# constructs a raw TextStyle( (in code only), sorted by path.
emit_current() {
  find "$SCAN_DIR" \
    -type f -name '*.dart' \
    -not -path '*/l10n/generated/*' \
    -not -path '*/.dart_tool/*' \
    -not -path '*/build/*' \
    ! -name '*.g.dart' ! -name '*.freezed.dart' ! -name '*.gr.dart' \
    ! -name '*.config.dart' ! -name '*.mocks.dart' \
    -print0 2>/dev/null \
  | while IFS= read -r -d '' f; do
      count="$(awk -f "$SCRIPT_DIR/lib/dart_code_only.awk" "$f" 2>/dev/null \
        | grep -oE "$DETECT_RE" \
        | grep -c . || true)"
      count="${count//[[:space:]]/}"
      if [[ "${count:-0}" -gt 0 ]]; then
        printf '%s\t%s\n' "${f#"$PATH_PREFIX"/}" "$count"
      fi
    done \
  | LC_ALL=C sort -t "$TAB" -k1,1
}

print_baseline_header() {
  cat <<EOF
# Frozen baseline: Dart files under mobile/lib constructing a raw TextStyle(,
# each with its current count as a CEILING (format: relpath<TAB>count).
# Generated by scripts/check_raw_textstyle_ceiling.sh. A ceiling may only SHRINK;
# more raw styles, a new file, or a raised ceiling fails CI vs ${BASE_REF}.
# Use VineTheme.*Font() helpers instead. Comments and string literals are not
# counted.
# Issue: #6145. Regenerate after migrating:
#   UPDATE_BASELINE=1 bash scripts/check_raw_textstyle_ceiling.sh
EOF
}

# shellcheck source=lib/numeric_ratchet.sh
source "$SCRIPT_DIR/lib/numeric_ratchet.sh"
run_numeric_ratchet
