#!/usr/bin/env bash
# Prefs-key classification ratchet (#8314, epic #4335): the set of fixed-string
# preference keys the app stores under that NO account-cleanup path clears is
# frozen in scripts/baseline/prefs_key_classification.txt and may only ever
# SHRINK. See lib/list_ratchet.sh for the NEW/STALE/GROWTH semantics.
#
# Why this exists. UserDataCleanupService.userSpecificKeys guards the
# account-switch privacy boundary, and for nine months it named keys by copied
# string literal. A copy has no referent, so nothing detected divergence in
# either direction: eleven listed keys rotted into no-ops when their owning
# service was renamed or deleted, and fourteen live keys were never listed at
# all. Two of those were a real cross-account leak (#6985) — the incoming
# account inherited the previous account's moderation subscriptions.
#
# The sweep list now references the constants its writing services own, so a
# RENAME is a compile error. This guard covers the other direction, which the
# compiler cannot see: a NEW key that nobody adds to the sweep.
#
# Detector: scripts/lib/prefs_key_classification_detector.dart — a Dart AST,
# not a grep, for the reason every detector here is: 'content_filter_prefs'
# appears in comments, dartdoc and log strings without storing anything, and
# dart format wraps argument lists so column position tells you nothing.
#
# NOT reported, and each exclusion is load-bearing:
#   * a key whose value is not a fixed string — 'following_list_$pubkey' or
#     SavedSoundsService.accountStorageKey(pubkey) embeds the owner, so it
#     cannot carry one account's value into another's session;
#   * a key matched by UserDataCleanupService.identityChangePrefixes;
#   * a key listed in any `deviceScopedPrefsKeys` declaration — that is how a
#     setting is declared to deliberately survive an account switch. Declare it
#     next to the constant, NOT here: this baseline may only shrink, and a
#     legitimate new device setting must be free to grow.
#   * anything under a package's test tree — a test's own fixture key is not
#     app storage.
#
# BASELINE ENTRIES ARE A WORKLIST, NOT EXEMPTIONS. Each is a key that is
# probably a device setting but has never been declared as one. Resolving one
# means deciding which it is and saying so in code — either add it to the
# sweep, or declare it device-scoped.
#
# List the current set with reasons:
#   cd mobile && dart run scripts/lib/prefs_key_classification_detector.dart \
#     lib packages --detail
#
# Regenerate ONLY after genuinely classifying a key (never to add one):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_prefs_key_classification.sh
# Usage (from repo root or mobile/): bash mobile/scripts/check_prefs_key_classification.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

RATCHET_LABEL="prefs_key_classification"
BASELINE_FILE="$SCRIPT_DIR/baseline/prefs_key_classification.txt"
BASELINE_REPO_PATH="mobile/scripts/baseline/prefs_key_classification.txt"
BASE_REF="${PREFS_KEY_CLASSIFICATION_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${PREFS_KEY_CLASSIFICATION_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="PREFS_KEY_CLASSIFICATION_ALLOW_NO_BASE"
NEW_HINT="A preference key is stored under, but no account-cleanup path clears it
and nothing declares it device-scoped. Decide which it is:
  * holds one account's data -> reference its constant from
    UserDataCleanupService.userSpecificKeys, so a rename becomes a compile error;
  * deliberately survives an account switch -> add it to a
    'static const List<String> deviceScopedPrefsKeys' beside the constant itself;
  * gates per-account data (a migration flag) -> clear it WITH the data it gates,
    never alone — see ContentFilterService.filterMigratedStorageKey.
Do not add it to this baseline."
STALE_HINT="A baselined key is now classified (swept or declared device-scoped)."
FOOTER="This set may only shrink. Entries are unclassified keys — a worklist, not
exemptions. See .claude/rules/data_foundation.md and #8314."

emit_current() {
  (cd "$MOBILE_DIR" && dart run scripts/lib/prefs_key_classification_detector.dart \
    lib packages) | LC_ALL=C sort -u
}

print_baseline_header() {
  cat <<'EOF'
# Frozen baseline: fixed-string preference keys the app stores under that no
# account-cleanup path clears and nothing declares device-scoped (#8314).
# Generated by scripts/check_prefs_key_classification.sh. The set may only
# SHRINK — any NEW unclassified key fails CI vs origin/main.
#
# These are a WORKLIST, not exemptions. Most are device settings that have
# simply never been declared as such; a few are genuinely ambiguous and are
# noted below. Resolve one by classifying it in CODE — add it to the sweep, or
# declare it in a `deviceScopedPrefsKeys` list beside its constant. Never add a
# new key here.
#
# Epic: #4335. Origin: #8314 / #6985.
EOF
}

# shellcheck source=lib/list_ratchet.sh
source "$SCRIPT_DIR/lib/list_ratchet.sh"
run_list_ratchet
