#!/usr/bin/env bash
# Production Future.delayed-ceiling ratchet (epic #4339): the set of files under
# mobile/lib that use `Future.delayed` is frozen in
# scripts/baseline/future_delayed_production.txt and may only ever SHRINK.
# `Future.delayed` in app code encodes wall-clock timing and is a frequent source
# of races and flaky behavior; the project rule (.claude/CLAUDE.md) is to avoid it
# in app code in favor of explicit async coordination (AnimatedSwitcher /
# animation controllers / stream listeners / completers).
#
# This is the PRODUCTION counterpart to check_future_delayed_ceiling.sh (which is
# TEST-scoped under epic #4337, WS-2). They are deliberately separate baselines:
# this one guards mobile/lib, that one guards mobile/test. Do not conflate them.
#
# The detector scopes to mobile/lib/**/*.dart and EXCLUDES:
#   • generated files (*.g.dart / *.freezed.dart / *.gr.dart / *.config.dart /
#     *.mocks.dart) and the l10n generated dir (mobile/lib/l10n/generated/),
#   • build / .dart_tool artifacts.
#
# Regenerate after MIGRATING a file off Future.delayed (never to add one):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_future_delayed_production_ceiling.sh
# Usage:
#   bash mobile/scripts/check_future_delayed_production_ceiling.sh
#   (cd mobile && bash scripts/check_future_delayed_production_ceiling.sh)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

RATCHET_LABEL="future_delayed_production_ceiling"
BASELINE_FILE="$SCRIPT_DIR/baseline/future_delayed_production.txt"
BASELINE_REPO_PATH="mobile/scripts/baseline/future_delayed_production.txt"
BASE_REF="${FUTURE_DELAYED_PROD_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${FUTURE_DELAYED_PROD_CEILING_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="FUTURE_DELAYED_PROD_CEILING_ALLOW_NO_BASE"
NEW_HINT="Don't add Future.delayed to app code — use explicit async coordination (AnimatedSwitcher / animation controllers / stream listeners / completers), not a wall-clock wait. See .claude/CLAUDE.md and epic #4339."
STALE_HINT="A production file was migrated off Future.delayed."
FOOTER="Future.delayed in mobile/lib is frozen and may only decrease. Replace it
with explicit async coordination rather than a longer wall-clock wait. See
.claude/CLAUDE.md and epic #4339."

emit_current() {
  find "$MOBILE_DIR/lib" \
    -not -path "*/l10n/generated/*" \
    -not -path "*/.dart_tool/*" -not -path "*/build/*" \
    -name "*.dart" \
    ! -name "*.g.dart" ! -name "*.freezed.dart" ! -name "*.gr.dart" \
    ! -name "*.config.dart" ! -name "*.mocks.dart" \
    -print0 2>/dev/null \
    | xargs -0 grep -lE "Future\.delayed" 2>/dev/null \
    | sed "s#^$MOBILE_DIR/##" | LC_ALL=C sort -u || true
}

print_baseline_header() {
  cat <<'EOF'
# Frozen baseline: files under mobile/lib/**/*.dart that use Future.delayed.
# Generated by scripts/check_future_delayed_production_ceiling.sh. The baseline
# may only SHRINK (growth fails CI vs origin/main). Replace Future.delayed with
# explicit async coordination. Epic: #4339 (production counterpart of the
# test-scoped #4337 WS-2 ratchet).
EOF
}

# shellcheck source=lib/list_ratchet.sh
source "$SCRIPT_DIR/lib/list_ratchet.sh"
run_list_ratchet
