#!/usr/bin/env bash
# Service god-file ceiling ratchet (epic #4338): oversized Dart files under
# mobile/lib/services are frozen at their current line count in
# scripts/baseline/service_god_file_sizes.txt. A service file's ceiling may only
# ever DECREASE. CI fails if:
#   * a baselined service file grows past its recorded ceiling,
#   * a NEW service file crosses the oversized threshold,
#   * the branch baseline adds a service file or raises a ceiling vs origin/main.
#
# This deliberately does not replace check_file_size_ceiling.sh. The broad
# 800-line app-wide file-size check remains advisory per the #4339 team
# decision; this guard is the hard architecture ratchet for service-layer
# god-files that otherwise re-accumulate work while extraction lanes pause.
# If the same file appears in both baselines, this hard service baseline is the
# authoritative one for service god-file ceilings.
#
# Regenerate after shrinking/removing a service god-file (never to raise a
# ceiling):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_service_god_file_ceiling.sh
# Usage:
#   bash mobile/scripts/check_service_god_file_ceiling.sh
#   (cd mobile && bash scripts/check_service_god_file_ceiling.sh)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TAB="$(printf '\t')"

RATCHET_LABEL="service_god_file_ceiling"
THRESHOLD="${SERVICE_GOD_FILE_THRESHOLD:-1500}"
SCAN_DIR="${SERVICE_GOD_FILE_SCAN_DIR:-$MOBILE_DIR/lib/services}"
PATH_PREFIX="${SERVICE_GOD_FILE_PATH_PREFIX:-$MOBILE_DIR}"
BASELINE_FILE="${SERVICE_GOD_FILE_BASELINE_FILE:-$SCRIPT_DIR/baseline/service_god_file_sizes.txt}"
BASELINE_REPO_PATH="${SERVICE_GOD_FILE_BASELINE_REPO_PATH:-mobile/scripts/baseline/service_god_file_sizes.txt}"
BASE_REF="${SERVICE_GOD_FILE_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${SERVICE_GOD_FILE_CEILING_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="SERVICE_GOD_FILE_CEILING_ALLOW_NO_BASE"

NEW_HINT="Do not grow service-layer god files under mobile/lib/services. Extract responsibilities behind repository/client boundaries, or keep the change out of the oversized service file. If this is an in-tree move of a still-oversized service, UPDATE_BASELINE alone cannot approve it; shrink/extract first or complete rename-aware ratchet support. See epic #4338."
STALE_HINT="A service god-file was removed, renamed, or dropped below the oversized threshold. If this is paired with a NEW key for an in-tree move, UPDATE_BASELINE alone cannot approve the moved oversized service."
FOOTER="Service-layer god-file sizes are frozen and may only decrease. Keep new
work out of oversized services and continue the UI -> BLoC/Cubit -> Repository
-> Client extraction path from epic #4338."

emit_current() {
  find "$SCAN_DIR" \
    -type f -name '*.dart' \
    -not -path '*/.dart_tool/*' \
    -not -path '*/build/*' \
    ! -name '*.g.dart' ! -name '*.freezed.dart' ! -name '*.gr.dart' \
    ! -name '*.config.dart' ! -name '*.mocks.dart' \
    -print0 2>/dev/null \
  | while IFS= read -r -d '' f; do
      loc="$(wc -l < "$f" | tr -d '[:space:]')"
      if [[ "${loc:-0}" -gt "$THRESHOLD" ]]; then
        printf '%s\t%s\n' "${f#"$PATH_PREFIX"/}" "$loc"
      fi
    done \
  | LC_ALL=C sort -t "$TAB" -k1,1
}

print_baseline_header() {
  cat <<EOF
# Frozen baseline: Dart files under mobile/lib/services over ${THRESHOLD} lines,
# each with its current line count as a CEILING (format: relpath<TAB>loc).
# Generated by scripts/check_service_god_file_ceiling.sh. A ceiling may only
# SHRINK; more lines, a new oversized service file, or a raised ceiling fails CI
# vs ${BASE_REF}. Epic: #4338.
# This hard service baseline is authoritative over the advisory file_sizes.txt
# baseline for service god-file ceilings.
# Regenerate after shrinking/removing: UPDATE_BASELINE=1 bash scripts/check_service_god_file_ceiling.sh
EOF
}

# shellcheck source=lib/numeric_ratchet.sh
source "$SCRIPT_DIR/lib/numeric_ratchet.sh"
run_numeric_ratchet
