#!/usr/bin/env bash
# Raw-colors ceiling ratchet (#6145, epic #4339): every Dart file under
# mobile/lib that uses a raw color (Material `Colors.*` or a `Color(...)` /
# `Color.fromARGB(` / `Color.fromRGBO(` / `HSVColor` / `HSLColor` constructor) is
# frozen at its current count in scripts/baseline/raw_colors.txt, a per-file
# CEILING that may only ever DECREASE. New UI color must come from VineTheme
# (apply transparency via .withValues(alpha:) on a theme color) rather than a raw
# literal (rule: ui_theming.md → "Colors").
#
# Detector (occurrences, outside full-line comments):
#   \bColors\.[A-Za-z_] | \bColor\( | \bColor\.fromARGB\( | \bColor\.fromRGBO\(
#   | \bHSVColor | \bHSLColor
# The word boundary EXCLUDES custom color classes (e.g. SomeColor(, MaterialColors.)
# and the alternatives are disjoint (no double counting). Scope is deliberately
# strict — Colors.transparent and the lib/theme + lib/constants color homes are
# frozen too, so new growth anywhere is intentional. divine_ui / VineTheme (the
# sanctioned color source) is a separate package, out of scope by construction.
#
# Per-key NUMERIC ceiling: a file may drop colors freely while above zero without
# churning the baseline; only growth / new file / raised ceiling / drop-to-zero
# (STALE) fails. Generated code excluded by path (l10n/generated) and suffix.
#
# Regenerate after MIGRATING to VineTheme (never to raise a ceiling):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_raw_colors_ceiling.sh
# Run (from repo root or mobile/): bash mobile/scripts/check_raw_colors_ceiling.sh

set -euo pipefail
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TAB="$(printf '\t')"

RATCHET_LABEL="raw_colors_ceiling"
SCAN_DIR="${RAW_COLORS_SCAN_DIR:-$MOBILE_DIR/lib}"
PATH_PREFIX="${RAW_COLORS_PATH_PREFIX:-$MOBILE_DIR}"
BASELINE_FILE="${RAW_COLORS_BASELINE_FILE:-$SCRIPT_DIR/baseline/raw_colors.txt}"
BASELINE_REPO_PATH="${RAW_COLORS_BASELINE_REPO_PATH:-mobile/scripts/baseline/raw_colors.txt}"
BASE_REF="${RAW_COLORS_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${RAW_COLORS_CEILING_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="RAW_COLORS_CEILING_ALLOW_NO_BASE"

DETECT_RE='\bColors\.[A-Za-z_]|\bColor\(|\bColor\.fromARGB\(|\bColor\.fromRGBO\(|\bHSVColor|\bHSLColor'

NEW_HINT="Don't add raw colors — use a VineTheme color (apply alpha with .withValues(alpha:) on a theme color). ui_theming.md → Colors; #6145."
STALE_HINT="A file dropped its raw colors (migrated to VineTheme or removed)."
FOOTER="Raw color counts under mobile/lib are frozen and may only decrease.
Use VineTheme colors (+ .withValues(alpha:)) rather than adding more literals.
See ui_theming.md (Colors) and epics #6145 / #4339."

# Print "relpath<TAB>count" for every non-generated Dart file under SCAN_DIR that
# uses a raw color (outside full-line comments), sorted by path.
emit_current() {
  find "$SCAN_DIR" \
    -type f -name '*.dart' \
    -not -path '*/l10n/generated/*' \
    -not -path '*/.dart_tool/*' \
    -not -path '*/build/*' \
    ! -name '*.g.dart' ! -name '*.freezed.dart' ! -name '*.gr.dart' \
    ! -name '*.config.dart' ! -name '*.mocks.dart' \
    -print0 2>/dev/null \
  | while IFS= read -r -d '' f; do
      count="$(grep -vE '^[[:space:]]*//' "$f" 2>/dev/null \
        | grep -oE "$DETECT_RE" \
        | grep -c . || true)"
      count="${count//[[:space:]]/}"
      if [[ "${count:-0}" -gt 0 ]]; then
        printf '%s\t%s\n' "${f#"$PATH_PREFIX"/}" "$count"
      fi
    done \
  | LC_ALL=C sort -t "$TAB" -k1,1
}

print_baseline_header() {
  cat <<EOF
# Frozen baseline: Dart files under mobile/lib using a raw color (Colors.* or a
# Color(/Color.fromARGB(/Color.fromRGBO(/HSVColor/HSLColor constructor), each with
# its current count as a CEILING (format: relpath<TAB>count). Generated by
# scripts/check_raw_colors_ceiling.sh. A ceiling may only SHRINK; more raw colors,
# a new file, or a raised ceiling fails CI vs ${BASE_REF}. Use VineTheme colors.
# Full-line comments are not counted. Issue: #6145. Regenerate after migrating:
#   UPDATE_BASELINE=1 bash scripts/check_raw_colors_ceiling.sh
EOF
}

# shellcheck source=lib/numeric_ratchet.sh
source "$SCRIPT_DIR/lib/numeric_ratchet.sh"
run_numeric_ratchet
