#!/usr/bin/env bash
# Untested-services floor ratchet (epic #4337, WS-3): the set of service classes
# under mobile/lib/services that have NO same-named *_test.dart is frozen in
# scripts/baseline/untested_services.txt and may only ever SHRINK. See
# lib/list_ratchet.sh for the NEW/STALE/GROWTH semantics.
#
# Detector: set-difference of basenames —
#   {lib/services/*.dart (ex generated)} \ {test/**/*_test.dart}
# This is a v1 existence check (a same-named test exists), NOT a coverage
# threshold; "meaningful coverage" is a documented fast-follow (see the plan).
# NEW fires when a new service ships without a test, OR a service's test is
# deleted. STALE fires when a baselined service gains a test (shrink the floor).
#
# Some baseline entries are intentionally permanent (stubs / models / mixins /
# platform shims) or deferred to a reshaping epic — annotated with a trailing
# '# reason' (e.g. '# noise: web shim', '# defer: #4338'). The ratchet never
# forces testing them; it only prevents the list from growing.
#
# Regenerate after ADDING a service's test (never to add a new untested service):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_untested_services_floor.sh
# Usage (from the repo root or mobile/): bash mobile/scripts/check_untested_services_floor.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

RATCHET_LABEL="untested_services_floor"
BASELINE_FILE="$SCRIPT_DIR/baseline/untested_services.txt"
BASELINE_REPO_PATH="mobile/scripts/baseline/untested_services.txt"
BASE_REF="${UNTESTED_SERVICES_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${UNTESTED_SERVICES_FLOOR_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="UNTESTED_SERVICES_FLOOR_ALLOW_NO_BASE"
NEW_HINT="A service under lib/services has no same-named *_test.dart (new service without a test, or a deleted test). Write the test, or delete the dead service. See tasks/plan_4337.md (WS-3)."
STALE_HINT="A service gained a same-named test."
FOOTER="Untested services are frozen and may only decrease. Add a same-named
*_test.dart for the service (or delete the service if it is dead) — do not ship
new untested services. See tasks/plan_4337.md (WS-3)."

emit_current() {
  comm -23 \
    <(find "$MOBILE_DIR/lib/services" -name '*.dart' \
        ! -name '*.g.dart' ! -name '*.freezed.dart' \
        -exec basename {} .dart \; 2>/dev/null | LC_ALL=C sort -u) \
    <(find "$MOBILE_DIR/test" -name '*_test.dart' \
        -exec basename {} _test.dart \; 2>/dev/null | LC_ALL=C sort -u) \
    || true
}

print_baseline_header() {
  cat <<'EOF'
# Frozen baseline: service classes under mobile/lib/services with NO same-named
# *_test.dart. Generated by scripts/check_untested_services_floor.sh. The set may
# only SHRINK (growth fails CI vs origin/main). A trailing '# reason' marks
# intentionally-permanent entries (noise: stub/model/mixin/shim) or '# defer: #NNNN'
# for services a reshaping epic owns. Epic: #4337.
EOF
}

# shellcheck source=lib/list_ratchet.sh
source "$SCRIPT_DIR/lib/list_ratchet.sh"
run_list_ratchet
