#!/usr/bin/env bash
# Singleton-service floor ratchet (#4743, epic #4338): the set of classes under
# mobile/lib that hand every caller the same instance through static state is
# frozen in scripts/baseline/singleton_services.txt and may only ever SHRINK.
# See lib/list_ratchet.sh for the NEW/STALE/GROWTH semantics.
#
# Detector: a class declaring one of
#   factory <Name>() => _instance;          the classic self-returning factory
#   static final <Name> _instance = ...;    a lazy-static holder
#   static <Name>? _instance;               the nullable ??= variant
# plus a top-level `final <Name> alias = <Name>.instance;` global, which is the
# same reach-through wearing a lowercase name and is what hid two of the five
# services #4743 audited from a `.instance` grep.
#
# Why this exists: #4743's own issue body listed 14 services that were already
# down to 5 by the time anyone re-read it, and #3623 before it listed 13. The
# set drifts because nothing watches it, so each audit re-discovers a different
# number. A ratchet is how this repo makes that kind of win stick.
#
# NOT counted: `*_platform_interface.dart`, where `static X _instance` is the
# federated-plugin pattern Flutter itself prescribes, and the instance is
# settable precisely so a test can replace it.
#
# There is no sanctioned way to add one. If a dependency genuinely cannot be
# constructor-injected (a static utility class with no instances), give it an
# assignable seam that app_bootstrap sets, as VideoThumbnailService does — that
# is injectable and mockable, and this detector does not count it.
#
# Regenerate only after REMOVING a singleton:
#   UPDATE_BASELINE=1 bash mobile/scripts/check_singleton_services.sh
# Usage (from the repo root or mobile/): bash mobile/scripts/check_singleton_services.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

RATCHET_LABEL="singleton_services"
BASELINE_FILE="$SCRIPT_DIR/baseline/singleton_services.txt"
BASELINE_REPO_PATH="mobile/scripts/baseline/singleton_services.txt"
BASE_REF="${SINGLETON_SERVICES_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${SINGLETON_SERVICES_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="SINGLETON_SERVICES_ALLOW_NO_BASE"
NEW_HINT="A class now hands every caller the same instance through static state. Take the dependency through the constructor and expose it with a Riverpod provider (see lib/providers/service_providers.dart, or DeviceScope when it is needed before a container exists)."
STALE_HINT="A singleton was removed."
FOOTER="Singleton services are frozen and may only decrease. Constructor-inject
the dependency instead of adding a new one; for a static utility with no
instances, use an assignable reporter-style seam that app_bootstrap sets. See
#4743."

emit_current() {
  {
    grep -rnE '^\s*factory [A-Z][A-Za-z0-9_]*\(\) *=> *_instance;' \
      "$MOBILE_DIR/lib" --include='*.dart' 2>/dev/null || true
    grep -rnE '^\s*static (final )?[A-Z][A-Za-z0-9_]*\??? _instance' \
      "$MOBILE_DIR/lib" --include='*.dart' 2>/dev/null || true
    grep -rnE '^final [A-Z][A-Za-z0-9_]* [a-z][A-Za-z0-9_]* =$|^final [A-Z][A-Za-z0-9_]* [a-z][A-Za-z0-9_]* = [A-Z][A-Za-z0-9_]*\.instance;' \
      "$MOBILE_DIR/lib" --include='*.dart' 2>/dev/null || true
  } \
    | grep -v '_platform_interface\.dart' \
    | sed "s|^$MOBILE_DIR/|mobile/|" \
    | cut -d: -f1 \
    | LC_ALL=C sort -u
}

print_baseline_header() {
  cat <<'EOF'
# Frozen baseline: files under mobile/lib declaring a self-returning factory, a
# lazy-static `_instance` holder, or a top-level alias to one. Generated by
# scripts/check_singleton_services.sh. The set may only SHRINK (growth fails CI
# vs origin/main). Federated-plugin `*_platform_interface.dart` files are
# excluded — there the settable static IS the test seam. Issue: #4743.
EOF
}

# shellcheck source=lib/list_ratchet.sh
source "$SCRIPT_DIR/lib/list_ratchet.sh"
run_list_ratchet
