#!/usr/bin/env bash
# Fails CI when a NEW test file gains a test-level skip (`skip: true` or
# `skip: '<reason>'`), or when the frozen baseline grows. This is the
# skip-debt ratchet for epic #4337 (WS-1): the set of skipped test files may
# only ever SHRINK.
#
# What counts as a skip here (the pinned detector):
#   a line matching  [(, ]skip: (true|'|")  under mobile/test/**/*_test.dart
# This is the UNCONDITIONAL, test-level skip form passed to
# test()/testWidgets()/group()/testGoldens(). It deliberately EXCLUDES:
#   • platform-conditional skips (`skip: !kIsWeb`, `skip: !Platform.isX`) —
#     intentional gates, not debt; excluded because the value is not true/quote.
#   • argument-noise (`skipOffstage:`, `skipCache:`, …) — the literal token is
#     `skipOffstage:` etc., which does not contain `skip: ` (skip-colon-space).
#   • main_video_cache_startup_test.dart — its `skip: true` is an argument to the
#     function under test (configureVideoPlayerCacheForStartup), not a test skip;
#     those tests actually run. Excluded by path (the only such false positive).
#
# True ratchet (compares against origin/main, not just the in-branch baseline):
#   Pre-existing skips are frozen in scripts/baseline/skip_tests.txt.
#   The guard fails on:
#     • NEW    — a current skipped file not declared in the (in-branch) baseline.
#     • STALE  — a baselined file that no longer skips (fixed; the baseline must
#                shrink to lock the win in).
#     • GROWTH — the in-branch baseline contains entries not present in the
#                baseline on the base ref (default origin/main). This closes the
#                bypass where a PR adds a skip, reruns UPDATE_BASELINE, and commits
#                the grown baseline: the baseline may only ever shrink.
#   On the commit that first introduces the baseline (absent on the base ref),
#   the GROWTH check is skipped (bootstrap).
#
# Baseline file format: one mobile-relative path per line; an optional trailing
# "# reason" documents intent. Regenerate after FIXING/DELETING a skip (never to
# add a new skip — that fails GROWTH):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_skip_ceiling.sh
#
# Env overrides:
#   SKIP_BASELINE_BASE_REF      git ref to compare the baseline against (default origin/main).
#   SKIP_CEILING_ALLOW_NO_BASE=1  skip the growth check when the base ref cannot be
#                               loaded. Intended for local/offline runs only — the
#                               guard otherwise FAILS CLOSED (CI must never silently
#                               skip it).
#
# Usage:
#   bash mobile/scripts/check_skip_ceiling.sh
#   (run from the repository root or from mobile/)

set -euo pipefail

# Byte-wise, locale-independent ordering so sort/comm agree across macOS (local)
# and Linux (CI); otherwise the baseline diff can falsely flag NEW/STALE/GROWTH.
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$MOBILE_DIR/.." && pwd)"
BASELINE_FILE="$SCRIPT_DIR/baseline/skip_tests.txt"
BASELINE_REPO_PATH="mobile/scripts/baseline/skip_tests.txt"
BASE_REF="${SKIP_BASELINE_BASE_REF:-origin/main}"

# A test-level skip: optional `(`/`,`/space, then `skip: ` then true or a quote
# (single or double). Matches single-line and trailing-comma multi-line forms.
SKIP_RE="[(, ]skip: (true|'|\")"

GLOBAL_EXCLUDES=(
  -not -path "*/.dart_tool/*"
  -not -path "*/build/*"
  -not -name "*.g.dart"
  -not -name "*.freezed.dart"
  -not -name "*.mocks.dart"
  # False positive: `skip:` is an argument to the function under test, not a
  # test skip — those tests run and assert. Only known such file.
  -not -name "main_video_cache_startup_test.dart"
)

# Current test files, emitted as absolute paths (NUL-delimited).
test_dart_files() {
  find "$MOBILE_DIR/test" \
    "${GLOBAL_EXCLUDES[@]}" \
    -name "*_test.dart" \
    -print0 2>/dev/null
}

# Current skipped test files, emitted as mobile-relative paths.
current_skips() {
  test_dart_files | xargs -0 grep -lE "$SKIP_RE" 2>/dev/null \
    | sed "s#^$MOBILE_DIR/##" | LC_ALL=C sort -u || true
}

# Strip trailing "# reason" comments and blank lines from a baseline stream.
strip_baseline() {
  sed 's/[[:space:]]*#.*//; s/[[:space:]]*$//' | grep -v '^$' | LC_ALL=C sort || true
}

baseline_paths() {
  [[ -f "$BASELINE_FILE" ]] && strip_baseline < "$BASELINE_FILE" || true
}

baseline_header() {
  cat <<'EOF'
# Frozen baseline: test files under mobile/test/**/*_test.dart that carry a
# test-level skip (`skip: true` / `skip: '<reason>'`). Generated by
# scripts/check_skip_ceiling.sh. The baseline may only SHRINK (growth fails CI
# vs origin/main). A trailing '# reason' marks intent. Skip-debt epic: #4337.
EOF
}

write_baseline() {
  local reasons_file
  reasons_file="$(mktemp)"

  if [[ -f "$BASELINE_FILE" ]]; then
    awk '
      /^[[:space:]]*#/ || /^[[:space:]]*$/ { next }
      {
        path = $0
        comment = ""
        if (match(path, /[[:space:]]+#.*/)) {
          comment = substr(path, RSTART)
          path = substr(path, 1, RSTART - 1)
          sub(/[[:space:]]+$/, "", path)
        }
        if (comment != "") {
          print path "\t" comment
        }
      }
    ' "$BASELINE_FILE" > "$reasons_file"
  fi

  {
    baseline_header
    while IFS= read -r path; do
      [[ -z "$path" ]] && continue
      reason="$(awk -F '\t' -v target="$path" '$1 == target { print $2; exit }' "$reasons_file")"
      if [[ -n "$reason" ]]; then
        printf '%s %s\n' "$path" "$reason"
      else
        printf '%s\n' "$path"
      fi
    done <<< "$CURRENT"
  } > "$BASELINE_FILE"

  rm -f "$reasons_file"
}

CURRENT="$(current_skips)"

# ---------------------------------------------------------------------------
# Regenerate mode.
# ---------------------------------------------------------------------------
if [[ "${UPDATE_BASELINE:-0}" == "1" ]]; then
  mkdir -p "$(dirname "$BASELINE_FILE")"
  write_baseline
  count="$(printf '%s\n' "$CURRENT" | grep -c . || true)"
  echo "OK: wrote $count baseline entries to ${BASELINE_FILE#"$MOBILE_DIR"/}."
  exit 0
fi

BASELINE="$(baseline_paths)"

# Baseline on the base ref (origin/main), for the GROWTH ratchet check.
# Return codes:
#   0 — loaded; MAIN_BASELINE set.
#   2 — base ref resolves but the baseline file is absent on it (bootstrap: the
#       commit that introduces the guard). Growth check not applicable.
#   1 — base ref cannot be resolved (fetch/ref failure).
#   3 — base ref + file exist but the blob could not be read (unexpected).
# Callers MUST fail closed on 1/3 — the ratchet cannot be verified.
MAIN_BASELINE=""
load_base_baseline() {
  if ! git -C "$REPO_ROOT" rev-parse --verify --quiet "$BASE_REF" >/dev/null 2>&1; then
    git -C "$REPO_ROOT" fetch --quiet --depth=1 origin main 2>/dev/null || true
  fi
  if ! git -C "$REPO_ROOT" rev-parse --verify --quiet "$BASE_REF" >/dev/null 2>&1; then
    return 1
  fi
  if ! git -C "$REPO_ROOT" cat-file -e "$BASE_REF:$BASELINE_REPO_PATH" 2>/dev/null; then
    return 2
  fi
  local raw
  if ! raw="$(git -C "$REPO_ROOT" show "$BASE_REF:$BASELINE_REPO_PATH" 2>/dev/null)"; then
    return 3
  fi
  MAIN_BASELINE="$(printf '%s\n' "$raw" | strip_baseline)"
  return 0
}

fail=0

# NEW: current skipped files not declared in the in-branch baseline.
NEW="$(comm -13 <(printf '%s\n' "$BASELINE") <(printf '%s\n' "$CURRENT") | grep -v '^$' || true)"
if [[ -n "$NEW" ]]; then
  echo "FAIL [skip_ceiling]: NEW skipped test file(s) not in the baseline:"
  echo "$NEW" | sed 's/^/  /'
  echo "  -> Don't add 'skip: true' to silence a failing test. Fix or delete it."
  echo "     (epic #4337 mandate: delete dead/low-value tests, never re-skip.)"
  fail=1
fi

# STALE: baselined files that no longer skip.
STALE="$(comm -23 <(printf '%s\n' "$BASELINE") <(printf '%s\n' "$CURRENT") | grep -v '^$' || true)"
if [[ -n "$STALE" ]]; then
  echo "FAIL [skip_ceiling]: baseline entries that no longer carry a skip:"
  echo "$STALE" | sed 's/^/  /'
  echo "  -> A skip was removed (fixed/deleted). Lock the win by shrinking the baseline:"
  echo "     UPDATE_BASELINE=1 bash mobile/scripts/check_skip_ceiling.sh"
  fail=1
fi

# GROWTH: in-branch baseline must not add entries vs the base ref's baseline.
set +e
load_base_baseline
base_status=$?
set -e
case "$base_status" in
  0)
    GROWTH="$(comm -23 <(printf '%s\n' "$BASELINE") <(printf '%s\n' "$MAIN_BASELINE") | grep -v '^$' || true)"
    if [[ -n "$GROWTH" ]]; then
      echo "FAIL [skip_ceiling]: baseline GREW vs ${BASE_REF} (the ratchet may only shrink):"
      echo "$GROWTH" | sed 's/^/  /'
      echo "  -> New skips are not allowed. Fix or delete the test instead of"
      echo "     adding it to the baseline."
      fail=1
    fi
    ;;
  2)
    echo "NOTE [skip_ceiling]: no baseline on ${BASE_REF} yet (introducing the guard); skipping growth check."
    ;;
  *)
    # Base baseline could not be loaded (status 1/3) — FAIL CLOSED so the growth
    # ratchet can never silently degrade to best-effort in CI. Soft-skip only
    # when a human explicitly opts out for a local/offline run.
    if [[ "${SKIP_CEILING_ALLOW_NO_BASE:-0}" == "1" ]]; then
      echo "NOTE [skip_ceiling]: ${BASE_REF} unavailable; skipping growth check (SKIP_CEILING_ALLOW_NO_BASE=1, local opt-out)."
    else
      echo "FAIL [skip_ceiling]: could not load the baseline from ${BASE_REF}, so the"
      echo "  growth ratchet cannot be verified — failing closed. Ensure ${BASE_REF} is"
      echo "  fetched (CI runs 'git fetch --depth=1 origin main' before this guard)."
      echo "  For a local run without a base ref, set SKIP_CEILING_ALLOW_NO_BASE=1 to skip."
      fail=1
    fi
    ;;
esac

if [[ "$fail" -eq 0 ]]; then
  echo "OK: No new skipped tests (baseline frozen, ratcheted vs ${BASE_REF})."
else
  echo ""
  echo "Skipped tests are frozen and may only decrease. Fix, delete, or properly"
  echo "quarantine (tag) the test — do not add 'skip: true' + a generic TODO."
  echo "See tasks/plan_4337.md (WS-1) and .claude/rules/agent_workflow.md (rule #5)."
  exit 1
fi
