#!/usr/bin/env bash
# Ungrouped-test ceiling ratchet (#3615, test-org epic #4337): every test file
# under mobile/test, mobile/integration_test and mobile/packages/*/test that
# declares a `test` / `testWidgets` / `blocTest` / `patrolTest` outside any
# `group(...)` is frozen at its current count in
# scripts/baseline/ungrouped_tests.txt, a per-file CEILING that may only ever
# DECREASE.
#
# Why: a flat list of test declarations gives the runner nothing to nest, so
# failures print as an undifferentiated wall of descriptions, a file cannot be
# run a slice at a time (`--plain-name 'FooRepository fetch'`), and a reader has
# to infer the subject of each case from prose. The audit behind #3615 counted
# 25 fully flat files in April 2026; by August there were 108 — the shape
# re-accretes on its own, which is what a ratchet is for.
#
# The fix is `.claude/rules/testing.md`: group by method name for repositories,
# services and clients; by event name for blocs and cubits; by
# renders / interactions / navigation for widgets. Wrap the declarations only —
# a top-level `setUp` already applies to nested groups, so it does not move.
#
# Detector: scripts/lib/ungrouped_test_detector.dart (a real Dart AST — nesting
# is the whole question, and `dart format` wraps long argument lists, so column
# position does not track group depth; braces also appear inside strings,
# comments and `${}` interpolations). Pinned by
# test/tools/ungrouped_test_detector_test.dart.
#
# Baselined files are NOT flat — those were cleared in #3615. Each is a file
# with real group structure that left a declaration or two outside it. Run the
# detector with --detail on one to see which. Use --path-prefix . so the
# reported paths match scripts/baseline/ungrouped_tests.txt.
#
# Per-key NUMERIC ceiling: a file may drop sites freely while above zero without
# churning the baseline; only growth / a new file / a raised ceiling /
# drop-to-zero (STALE) fails.
#
# Regenerate after GROUPING sites (never to raise):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_ungrouped_tests.sh
# Run (from repo root or mobile/): bash mobile/scripts/check_ungrouped_tests.sh
# List the individual sites in a file:
#   dart run scripts/lib/ungrouped_test_detector.dart test integration_test packages --path-prefix . --detail

set -euo pipefail
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TAB="$(printf '\t')"

RATCHET_LABEL="ungrouped_tests"
BASELINE_FILE="${UNGROUPED_TESTS_BASELINE_FILE:-$SCRIPT_DIR/baseline/ungrouped_tests.txt}"
BASELINE_REPO_PATH="${UNGROUPED_TESTS_BASELINE_REPO_PATH:-mobile/scripts/baseline/ungrouped_tests.txt}"
BASE_REF="${UNGROUPED_TESTS_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${UNGROUPED_TESTS_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="UNGROUPED_TESTS_ALLOW_NO_BASE"
DART_BIN="${UNGROUPED_TESTS_DART:-dart}"

# Scan roots, relative to MOBILE_DIR. `packages` is scanned whole and filtered
# to test/ and integration_test/ segments by the detector, so a package's own
# nested test dirs are covered without listing each package here.
SCAN_DIRS="${UNGROUPED_TESTS_SCAN_DIRS:-test integration_test packages}"

NEW_HINT="A test declaration must live inside a group(). Group by method name for repositories/services/clients, by event name for blocs/cubits, and by renders / interactions / navigation for widgets — see .claude/rules/testing.md. Leave setUp/tearDown and helpers at main() level; they already apply to nested groups."
STALE_HINT="A file grouped every declaration it had loose."
FOOTER="Ungrouped test declarations are frozen per file and may only decrease.
See .claude/rules/testing.md and issue #3615 (test-org epic #4337). Inspect a
file's loose declarations with:
  dart run scripts/lib/ungrouped_test_detector.dart test integration_test packages --path-prefix . --detail"

# Print "relpath<TAB>count" for every test file with at least one declaration
# outside a group. Runs from MOBILE_DIR so the detector resolves
# package:analyzer from the app's package config.
emit_current() {
  (
    cd "$MOBILE_DIR"
    # shellcheck disable=SC2086
    "$DART_BIN" run scripts/lib/ungrouped_test_detector.dart \
      $SCAN_DIRS --path-prefix "$MOBILE_DIR"
  ) | LC_ALL=C sort -t "$TAB" -k1,1
}

print_baseline_header() {
  cat <<EOF
# Frozen baseline: test files under mobile/test, mobile/integration_test and
# mobile/packages/*/test that declare a test / testWidgets / blocTest /
# patrolTest outside any group(), each with its current count as a CEILING
# (format: relpath<TAB>count). Generated by scripts/check_ungrouped_tests.sh
# from scripts/lib/ungrouped_test_detector.dart. A ceiling may only SHRINK;
# more loose declarations, a new file, or a raised ceiling fails CI vs
# ${BASE_REF}. Every entry here is a file that HAS group structure and left a
# declaration or two outside it — the fully flat files were cleared in #3615.
# Remaining paydown is tracked in #7705.
# Fix by wrapping the declaration in the group it belongs to
# (.claude/rules/testing.md). Regenerate after grouping sites:
#   UPDATE_BASELINE=1 bash scripts/check_ungrouped_tests.sh
EOF
}

# shellcheck source=lib/numeric_ratchet.sh
source "$SCRIPT_DIR/lib/numeric_ratchet.sh"
run_numeric_ratchet
