#!/usr/bin/env bash
# Service-sentinel ceiling ratchet (epic #4336): the count of `return null;` /
# `return false;` error-sentinels in the three high-risk god-services is frozen
# per file in scripts/baseline/service_sentinels.txt and may only ever DECREASE.
# These services return sentinels instead of throwing typed exceptions, so
# callers can't distinguish "no result" from "it failed" and nothing reaches the
# per-layer failure contract (.claude/rules/error_handling.md). The migration
# target is typed exceptions (+ Reportable per the matrix); LocalKeySigner is the
# kickoff (plan PR-D4 / DoD criterion 7).
#
# Scoped to exactly three files so the coarse sentinel grep doesn't flood the
# repo. A NET increase per file fails; refactors that don't add net sentinels
# pass. If a file is renamed/extracted (e.g. #4741), it drops out (STALE) and the
# baseline is regenerated.
#
# Regenerate after removing sentinels (never to add):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_service_sentinel_ceiling.sh
# Usage (from repo root or mobile/):
#   bash mobile/scripts/check_service_sentinel_ceiling.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TAB="$(printf '\t')"

RATCHET_LABEL="service_sentinel_ceiling"
BASELINE_FILE="$SCRIPT_DIR/baseline/service_sentinels.txt"
BASELINE_REPO_PATH="mobile/scripts/baseline/service_sentinels.txt"
BASE_REF="${SERVICE_SENTINEL_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${SERVICE_SENTINEL_CEILING_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="SERVICE_SENTINEL_CEILING_ALLOW_NO_BASE"
NEW_HINT="Don't add return-null/return-false sentinels to these god-services — throw a typed exception (wrap with Reportable per the matrix). See .claude/rules/error_handling.md; epic #4336 (LocalKeySigner migration is plan PR-D4)."
STALE_HINT="A tracked service was removed/renamed, or its sentinel count dropped."
FOOTER="Error-sentinel counts in these services are frozen and may only decrease.
Replace return-null/return-false with typed exceptions surfaced via addError /
Reportable. See .claude/rules/error_handling.md and epic #4336."

# The three high-risk services this ratchet guards (relative to mobile/).
SENTINEL_FILES="lib/services/auth_service.dart
lib/services/video_event_publisher.dart
lib/services/local_key_signer.dart"

emit_current() {
  while IFS= read -r rel; do
    [[ -z "$rel" ]] && continue
    local abs="$MOBILE_DIR/$rel"
    [[ -f "$abs" ]] || continue
    local c
    c="$(grep -cE 'return (null|false);' "$abs" || true)"
    printf '%s\t%s\n' "$rel" "$c"
  done <<< "$SENTINEL_FILES" | LC_ALL=C sort -t "$TAB" -k1,1
}

print_baseline_header() {
  cat <<'EOF'
# Frozen baseline: count of `return null;` / `return false;` error-sentinels in
# the high-risk god-services (format: relpath<TAB>count). Generated by
# scripts/check_service_sentinel_ceiling.sh. A count may only SHRINK; a net
# increase fails CI vs origin/main. Migrate to typed exceptions + Reportable.
# Epic: #4336.
EOF
}

# shellcheck source=lib/numeric_ratchet.sh
source "$SCRIPT_DIR/lib/numeric_ratchet.sh"
run_numeric_ratchet
