#!/usr/bin/env bash
# Fails CI when a NEW file in the UI layer imports the service layer
# (package:openvine/services/... or a relative ../services/...), bypassing
# the BLoC/Cubit layer.
#
# UI layer scoped here:
#   • mobile/lib/**/{screens,widgets,view,views}/**
# This catches both the classic app-layer roots (lib/screens, lib/widgets) and
# co-located presentation directories such as features/**/view and
# notifications/view. Non-presentation code (providers, services, models,
# startup, etc.) is intentionally NOT guarded — it legitimately wires services.
#
# Rule: presentation must reach data through a BLoC/Cubit, never import a
# service directly (UI -> BLoC/Cubit -> Repository -> Client; see
# .claude/rules/architecture.md and docs/BLOC_UI_MIGRATION_PRD.md).
#
# True ratchet (compares against origin/main, not just the in-branch baseline):
#   Pre-existing violators are frozen in scripts/baseline/ui_service_imports.txt.
#   The guard fails on:
#     • NEW    — a current violation not declared in the (in-branch) baseline.
#     • STALE  — a baselined file that no longer imports services (fixed; the
#                baseline must shrink to lock the win in).
#     • GROWTH — the in-branch baseline contains entries not present in the
#                baseline on the base ref (default origin/main). This closes the
#                bypass where a PR adds a violation, reruns UPDATE_BASELINE, and
#                commits the grown baseline: the baseline may only ever shrink.
#   On the commit that first introduces the baseline (absent on the base ref),
#   the GROWTH check is skipped (bootstrap).
#
# Baseline file format: one mobile-relative path per line; an optional trailing
# "# reason" documents intent. Regenerate after FIXING a file (never to add a
# new violation — that fails GROWTH):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_ui_service_boundary.sh
#
# Env overrides:
#   BASELINE_BASE_REF       git ref to compare the baseline against (default origin/main).
#   UI_SERVICE_ALLOW_NO_BASE=1  skip the growth check when the base ref cannot be
#                           loaded. Intended for local/offline runs only — the guard
#                           otherwise FAILS CLOSED (CI must never silently skip it).
#
# Usage:
#   bash mobile/scripts/check_ui_service_boundary.sh
#   (run from the repository root or from mobile/)

set -euo pipefail

# Byte-wise, locale-independent ordering so sort/comm agree across macOS (local)
# and Linux (CI); otherwise the baseline diff can falsely flag NEW/STALE/GROWTH.
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$MOBILE_DIR/.." && pwd)"
BASELINE_FILE="$SCRIPT_DIR/baseline/ui_service_imports.txt"
BASELINE_REPO_PATH="mobile/scripts/baseline/ui_service_imports.txt"
BASE_REF="${BASELINE_BASE_REF:-origin/main}"

# A service import: `import` + ws + quote + (package:openvine/services/ OR a
# relative ../services/ path). Matches single- and double-quoted forms.
IMPORT_RE="^import[[:space:]]+['\"](package:openvine/services/|(\.\./)+services/)"

GLOBAL_EXCLUDES=(
  -not -path "*/.dart_tool/*"
  -not -path "*/build/*"
  -not -name "*.g.dart"
  -not -name "*.freezed.dart"
  -not -name "*.mocks.dart"
)

# Current UI-layer dart files, emitted as absolute paths.
ui_dart_files() {
  find "$MOBILE_DIR/lib" \
    "${GLOBAL_EXCLUDES[@]}" \
    -name "*.dart" \
    \( -path "*/screens/*" -o -path "*/widgets/*" -o -path "*/view/*" -o -path "*/views/*" \) \
    -print0 2>/dev/null
}

# Current violators across the UI layer, emitted as mobile-relative paths.
current_violations() {
  ui_dart_files | xargs -0 grep -lE "$IMPORT_RE" 2>/dev/null \
    | sed "s#^$MOBILE_DIR/##" | LC_ALL=C sort -u || true
}

# Strip trailing "# reason" comments and blank lines from a baseline stream.
strip_baseline() {
  sed 's/[[:space:]]*#.*//; s/[[:space:]]*$//' | grep -v '^$' | LC_ALL=C sort || true
}

baseline_paths() {
  [[ -f "$BASELINE_FILE" ]] && strip_baseline < "$BASELINE_FILE" || true
}

baseline_header() {
  cat <<'EOF'
# Frozen baseline: UI files in lib/**/{screens,widgets,view,views}/**
# that import the service layer directly, bypassing BLoC. Generated by
# scripts/check_ui_service_boundary.sh. The baseline may only SHRINK
# (growth fails CI vs origin/main). A trailing '# reason' marks intent.
EOF
}

write_baseline() {
  local reasons_file
  reasons_file="$(mktemp)"

  if [[ -f "$BASELINE_FILE" ]]; then
    awk '
      /^[[:space:]]*#/ || /^[[:space:]]*$/ { next }
      {
        path = $0
        comment = ""
        if (match(path, /[[:space:]]+#.*/)) {
          comment = substr(path, RSTART)
          path = substr(path, 1, RSTART - 1)
          sub(/[[:space:]]+$/, "", path)
        }
        if (comment != "") {
          print path "\t" comment
        }
      }
    ' "$BASELINE_FILE" > "$reasons_file"
  fi

  {
    baseline_header
    while IFS= read -r path; do
      [[ -z "$path" ]] && continue
      reason="$(awk -F '\t' -v target="$path" '$1 == target { print $2; exit }' "$reasons_file")"
      if [[ -n "$reason" ]]; then
        printf '%s %s\n' "$path" "$reason"
      else
        printf '%s\n' "$path"
      fi
    done <<< "$CURRENT"
  } > "$BASELINE_FILE"

  rm -f "$reasons_file"
}

CURRENT="$(current_violations)"

# ---------------------------------------------------------------------------
# Regenerate mode.
# ---------------------------------------------------------------------------
if [[ "${UPDATE_BASELINE:-0}" == "1" ]]; then
  mkdir -p "$(dirname "$BASELINE_FILE")"
  write_baseline
  count="$(printf '%s\n' "$CURRENT" | grep -c . || true)"
  echo "OK: wrote $count baseline entries to ${BASELINE_FILE#"$MOBILE_DIR"/}."
  exit 0
fi

BASELINE="$(baseline_paths)"

# Baseline on the base ref (origin/main), for the GROWTH ratchet check.
# Return codes:
#   0 — loaded; MAIN_BASELINE set.
#   2 — base ref resolves but the baseline file is absent on it (bootstrap: the
#       commit that introduces the guard). Growth check not applicable.
#   1 — base ref cannot be resolved (fetch/ref failure).
#   3 — base ref + file exist but the blob could not be read (unexpected).
# Callers MUST fail closed on 1/3 — the ratchet cannot be verified.
MAIN_BASELINE=""
load_base_baseline() {
  if ! git -C "$REPO_ROOT" rev-parse --verify --quiet "$BASE_REF" >/dev/null 2>&1; then
    git -C "$REPO_ROOT" fetch --quiet --depth=1 origin main 2>/dev/null || true
  fi
  if ! git -C "$REPO_ROOT" rev-parse --verify --quiet "$BASE_REF" >/dev/null 2>&1; then
    return 1
  fi
  if ! git -C "$REPO_ROOT" cat-file -e "$BASE_REF:$BASELINE_REPO_PATH" 2>/dev/null; then
    return 2
  fi
  local raw
  if ! raw="$(git -C "$REPO_ROOT" show "$BASE_REF:$BASELINE_REPO_PATH" 2>/dev/null)"; then
    return 3
  fi
  MAIN_BASELINE="$(printf '%s\n' "$raw" | strip_baseline)"
  return 0
}

fail=0

# NEW: current violations not declared in the in-branch baseline.
NEW="$(comm -13 <(printf '%s\n' "$BASELINE") <(printf '%s\n' "$CURRENT") | grep -v '^$' || true)"
if [[ -n "$NEW" ]]; then
  echo "FAIL [ui_service_boundary]: NEW direct service-layer import(s) in the UI layer:"
  echo "$NEW" | sed 's/^/  /'
  fail=1
fi

# STALE: baselined files that no longer import services.
STALE="$(comm -23 <(printf '%s\n' "$BASELINE") <(printf '%s\n' "$CURRENT") | grep -v '^$' || true)"
if [[ -n "$STALE" ]]; then
  echo "FAIL [ui_service_boundary]: baseline entries that no longer import services:"
  echo "$STALE" | sed 's/^/  /'
  echo "  -> A UI file was fixed. Lock the win by shrinking the baseline:"
  echo "     UPDATE_BASELINE=1 bash mobile/scripts/check_ui_service_boundary.sh"
  fail=1
fi

# GROWTH: in-branch baseline must not add entries vs the base ref's baseline.
set +e
load_base_baseline
base_status=$?
set -e
case "$base_status" in
  0)
    GROWTH="$(comm -23 <(printf '%s\n' "$BASELINE") <(printf '%s\n' "$MAIN_BASELINE") | grep -v '^$' || true)"
    if [[ -n "$GROWTH" ]]; then
      echo "FAIL [ui_service_boundary]: baseline GREW vs ${BASE_REF} (the ratchet may only shrink):"
      echo "$GROWTH" | sed 's/^/  /'
      echo "  -> New UI->service imports are not allowed. Migrate the file onto a"
      echo "     BLoC/Cubit instead of adding it to the baseline."
      fail=1
    fi
    ;;
  2)
    echo "NOTE [ui_service_boundary]: no baseline on ${BASE_REF} yet (introducing the guard); skipping growth check."
    ;;
  *)
    # Base baseline could not be loaded (status 1/3) — FAIL CLOSED so the growth
    # ratchet can never silently degrade to best-effort in CI. Soft-skip only
    # when a human explicitly opts out for a local/offline run.
    if [[ "${UI_SERVICE_ALLOW_NO_BASE:-0}" == "1" ]]; then
      echo "NOTE [ui_service_boundary]: ${BASE_REF} unavailable; skipping growth check (UI_SERVICE_ALLOW_NO_BASE=1, local opt-out)."
    else
      echo "FAIL [ui_service_boundary]: could not load the baseline from ${BASE_REF}, so the"
      echo "  growth ratchet cannot be verified — failing closed. Ensure ${BASE_REF} is"
      echo "  fetched (CI runs 'git fetch --depth=1 origin main' before this guard)."
      echo "  For a local run without a base ref, set UI_SERVICE_ALLOW_NO_BASE=1 to skip."
      fail=1
    fi
    ;;
esac

if [[ "$fail" -eq 0 ]]; then
  echo "OK: No new UI -> service-layer boundary violations (baseline frozen, ratcheted vs ${BASE_REF})."
else
  echo ""
  echo "Screens/widgets/feature-UI must reach data through a BLoC/Cubit, not import"
  echo "package:openvine/services/ (or a relative ../services/) directly."
  echo "See .claude/rules/architecture.md and docs/BLOC_UI_MIGRATION_PRD.md."
  exit 1
fi
