#!/usr/bin/env bash
# Fails CI when a NEW file under mobile/lib/screens/ or mobile/lib/widgets/
# imports the service layer (package:openvine/services/...) directly, thereby
# bypassing the BLoC/Cubit layer.
#
# Rule enforced:
#   • Presentation code (screens, widgets) must reach data through a
#     BLoC/Cubit, not import package:openvine/services/ directly.
#     (UI -> BLoC/Cubit -> Repository -> Client; see .claude/rules/architecture.md
#     and docs/BLOC_UI_MIGRATION_PRD.md.)
#
# Ratchet, not a clean sweep:
#   There are pre-existing direct-import violations that cannot all be fixed in
#   one PR. They are frozen in scripts/baseline/ui_service_imports.txt. This
#   guard fails only on:
#     • NEW   violations — a screen/widget not in the baseline imports services.
#     • STALE baseline entries — a baselined file no longer imports services
#       (so the win must be locked in by shrinking the baseline). The baseline
#       may only ever shrink.
#
# Baseline file (scripts/baseline/ui_service_imports.txt):
#   • One mobile-relative path per line (e.g. lib/widgets/foo.dart).
#   • An optional trailing "# reason" documents a reviewed, intentional
#     exception (e.g. a self-registering infrastructure service).
#   • Regenerate after fixing or intentionally adding a file:
#       UPDATE_BASELINE=1 bash mobile/scripts/check_ui_service_boundary.sh
#
# Known limitations (tracked for a fast-follow):
#   • Only lib/screens/ + lib/widgets/ are scoped; UI under lib/features/**
#     is not yet covered.
#   • Relative imports ("../../services/x.dart") are not detected; the codebase
#     overwhelmingly uses package: imports (very_good_analysis prefers them).
#
# Usage:
#   bash mobile/scripts/check_ui_service_boundary.sh                    # verify
#   UPDATE_BASELINE=1 bash mobile/scripts/check_ui_service_boundary.sh  # regenerate
#   (run from the repository root or from mobile/)

set -euo pipefail

# Byte-wise, locale-independent ordering so `sort`/`comm` agree across macOS
# (local) and Linux (CI) — otherwise the baseline diff can falsely flag
# NEW/STALE entries on a different collation.
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
BASELINE_FILE="$SCRIPT_DIR/baseline/ui_service_imports.txt"

GLOBAL_EXCLUDES=(
  -not -path "*/.dart_tool/*"
  -not -path "*/build/*"
  -not -name "*.g.dart"
  -not -name "*.freezed.dart"
  -not -name "*.mocks.dart"
)

# Current violators: files under lib/screens or lib/widgets with a top-level
# import of package:openvine/services/...  Emitted as mobile-relative paths.
current_violations() {
  find "$MOBILE_DIR/lib/screens" "$MOBILE_DIR/lib/widgets" \
    "${GLOBAL_EXCLUDES[@]}" \
    -name "*.dart" -print0 2>/dev/null \
  | xargs -0 grep -l -E "^import 'package:openvine/services/" 2>/dev/null \
  | sed "s#^$MOBILE_DIR/##" \
  | sort \
  || true
}

# Effective baseline paths (strip trailing "# reason" comments and blank lines).
baseline_paths() {
  if [[ -f "$BASELINE_FILE" ]]; then
    sed 's/[[:space:]]*#.*//; s/[[:space:]]*$//' "$BASELINE_FILE" \
      | grep -v '^$' \
      | sort \
      || true
  fi
}

CURRENT="$(current_violations)"

# ---------------------------------------------------------------------------
# Regenerate mode: rewrite the baseline from the current violations.
# ---------------------------------------------------------------------------
if [[ "${UPDATE_BASELINE:-0}" == "1" ]]; then
  mkdir -p "$(dirname "$BASELINE_FILE")"
  {
    echo "# Frozen baseline: UI files (lib/screens, lib/widgets) that import the"
    echo "# service layer (package:openvine/services/) directly, bypassing BLoC."
    echo "# Generated by scripts/check_ui_service_boundary.sh. The baseline may"
    echo "# only shrink. A trailing '# reason' marks a reviewed exception."
    printf '%s\n' "$CURRENT" | grep -v '^$' || true
  } > "$BASELINE_FILE"
  count="$(printf '%s\n' "$CURRENT" | grep -c . || true)"
  echo "OK: wrote $count baseline entries to ${BASELINE_FILE#"$MOBILE_DIR"/}."
  exit 0
fi

BASELINE="$(baseline_paths)"

# NEW   = present now, not in the baseline.
# STALE = in the baseline, no longer present (fixed; baseline must shrink).
NEW="$(comm -13 <(printf '%s\n' "$BASELINE") <(printf '%s\n' "$CURRENT") | grep -v '^$' || true)"
STALE="$(comm -23 <(printf '%s\n' "$BASELINE") <(printf '%s\n' "$CURRENT") | grep -v '^$' || true)"

fail=0

if [[ -n "$NEW" ]]; then
  echo "FAIL [ui_service_boundary]: NEW direct service-layer import(s) in the UI layer:"
  echo "$NEW" | sed 's/^/  /'
  fail=1
fi

if [[ -n "$STALE" ]]; then
  echo "FAIL [ui_service_boundary]: baseline entries that no longer import services:"
  echo "$STALE" | sed 's/^/  /'
  echo "  -> A UI file was fixed. Lock the win by shrinking the baseline:"
  echo "     UPDATE_BASELINE=1 bash mobile/scripts/check_ui_service_boundary.sh"
  fail=1
fi

if [[ "$fail" -eq 0 ]]; then
  echo "OK: No new UI -> service-layer boundary violations (baseline frozen)."
else
  echo ""
  echo "Screens/widgets must reach data through a BLoC/Cubit, not import"
  echo "package:openvine/services/ directly."
  echo "See .claude/rules/architecture.md and docs/BLOC_UI_MIGRATION_PRD.md."
  echo "If this import is a reviewed, intentional exception, add the file to"
  echo "scripts/baseline/ui_service_imports.txt with a trailing '# reason'."
  exit 1
fi
