#!/usr/bin/env bash
# Future.delayed-ceiling ratchet (epic #4337, WS-2): executable call sites are
# frozen as per-file numeric ceilings in
# scripts/baseline/future_delayed_tests.txt and may only ever SHRINK.
# `Future.delayed` in tests encodes wall-clock timing that
# makes suites slow and flaky; the migration target is `fakeAsync` (timer/timeout
# cases) or `pumpEventQueue` (stream-settling). See lib/numeric_ratchet.sh.
#
# The detector scopes to mobile/test/**/*.dart (tests AND hand-written
# helpers/mocks, which carry the same timing debt). It EXCLUDES:
#   • generated files (*.g.dart / *.freezed.dart / *.mocks.dart),
#   • test/temp/** fixtures,
#   • *.md / *.archived / *.disabled (not *.dart, excluded by the find name glob),
#   • integration_test/** (separate suite, separate policy — WS-6).
#
# Regenerate after removing a Future.delayed call site (never to add one):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_future_delayed_ceiling.sh
# Usage (from the repo root or mobile/): bash mobile/scripts/check_future_delayed_ceiling.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TAB="$(printf '\t')"

RATCHET_LABEL="future_delayed_ceiling"
BASELINE_FILE="$SCRIPT_DIR/baseline/future_delayed_tests.txt"
BASELINE_REPO_PATH="mobile/scripts/baseline/future_delayed_tests.txt"
BASE_REF="${FUTURE_DELAYED_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${FUTURE_DELAYED_CEILING_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="FUTURE_DELAYED_CEILING_ALLOW_NO_BASE"
LEGACY_LIST_BASELINE_MIGRATION=1
REQUIRE_BASELINE_UPDATE_ON_DECREASE=1
NEW_HINT="Don't add Future.delayed to a test — use fakeAsync (timers/timeouts) or pumpEventQueue (stream-settling). See tasks/plan_4337.md (WS-2)."
STALE_HINT="A Future.delayed call was removed."
FOOTER="Future.delayed in tests is frozen and may only decrease. Replace it with
fakeAsync (timer/timeout-driven) or pumpEventQueue (stream-settling), not a
longer wall-clock wait. See tasks/plan_4337.md (WS-2)."

emit_current() {
  find "$MOBILE_DIR/test" \
    -not -path "*/.dart_tool/*" -not -path "*/build/*" -not -path "*/temp/*" \
    -name "*.dart" \
    ! -name "*.g.dart" ! -name "*.freezed.dart" ! -name "*.mocks.dart" \
    -print0 2>/dev/null \
  | while IFS= read -r -d '' f; do
      # Code only, and the final grep -c consumes the whole stream. `-q` would
      # exit on the first match, so awk would die of SIGPIPE; under pipefail
      # the pipeline would report 141 — silently dropping every file whose
      # match lands before awk finishes writing. Undercounting is the dangerous
      # direction here.
      count="$(awk -f "$SCRIPT_DIR/lib/dart_code_only.awk" "$f" 2>/dev/null \
        | grep -oE "Future\.delayed" | grep -c . || true)"
      count="${count//[[:space:]]/}"
      if [[ "${count:-0}" -gt 0 ]]; then
        printf '%s\t%s\n' "${f#"$MOBILE_DIR"/}" "$count"
      fi
    done | LC_ALL=C sort -t "$TAB" -k1,1 || true
}

print_baseline_header() {
  cat <<'EOF'
# Frozen baseline: executable Future.delayed call sites under
# mobile/test/**/*.dart, stored as relpath<TAB>count per file. Generated by
# scripts/check_future_delayed_ceiling.sh. Each ceiling may only SHRINK (growth
# fails CI vs origin/main). Migrate to fakeAsync / pumpEventQueue. Epic: #4337.
EOF
}

# shellcheck source=lib/numeric_ratchet.sh
source "$SCRIPT_DIR/lib/numeric_ratchet.sh"
run_numeric_ratchet
