#!/usr/bin/env bash
# Empty-catch ceiling ratchet (epic #4336 / #3588): the set of files under
# mobile/lib with a single-line empty catch block `catch (...) {}` is frozen in
# scripts/baseline/empty_catches.txt and may only ever SHRINK. An empty catch
# swallows errors silently, defeating the per-layer failure contract
# (.claude/rules/error_handling.md). The fix is to log + classify (wrap with
# Reportable where the decision matrix says so) or document an intentional no-op
# (which then contains a comment, so it is no longer "empty"), then drop the file
# from the baseline.
#
# The detector matches the common single-line form `catch (...) {}`. Multi-line
# empty catches are out of scope by construction; documented no-ops contain a
# comment and so do not match.
#
# Regenerate after removing an empty catch (never to add one):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_empty_catch_ceiling.sh
# Usage (from repo root or mobile/):
#   bash mobile/scripts/check_empty_catch_ceiling.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

RATCHET_LABEL="empty_catch_ceiling"
BASELINE_FILE="$SCRIPT_DIR/baseline/empty_catches.txt"
BASELINE_REPO_PATH="mobile/scripts/baseline/empty_catches.txt"
BASE_REF="${EMPTY_CATCH_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${EMPTY_CATCH_CEILING_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="EMPTY_CATCH_CEILING_ALLOW_NO_BASE"
NEW_HINT="Don't swallow errors with an empty catch. Log + classify (wrap with Reportable per the matrix in .claude/rules/error_handling.md) or document an intentional no-op. Epic #4336 / #3588."
STALE_HINT="An empty catch was removed from a file."
FOOTER="Empty catch blocks in mobile/lib are frozen and may only decrease.
Replace them with logging + typed classification, or an explicitly documented
no-op. See .claude/rules/error_handling.md and epic #4336 (#3588)."

emit_current() {
  find "$MOBILE_DIR/lib" \
    -not -path "*/l10n/generated/*" \
    -not -path "*/.dart_tool/*" -not -path "*/build/*" \
    -name "*.dart" \
    ! -name "*.g.dart" ! -name "*.freezed.dart" ! -name "*.gr.dart" \
    ! -name "*.config.dart" ! -name "*.mocks.dart" \
    -print0 2>/dev/null \
    | xargs -0 grep -lE 'catch *\([^)]*\) *\{ *\}' 2>/dev/null \
    | sed "s#^$MOBILE_DIR/##" | LC_ALL=C sort -u || true
}

print_baseline_header() {
  cat <<'EOF'
# Frozen baseline: files under mobile/lib/**/*.dart with a single-line empty
# catch block. Generated by scripts/check_empty_catch_ceiling.sh. The baseline
# may only SHRINK (a new empty catch fails CI vs origin/main). Log + classify or
# document an intentional no-op. Epic: #4336 (#3588).
EOF
}

# shellcheck source=lib/list_ratchet.sh
source "$SCRIPT_DIR/lib/list_ratchet.sh"
run_list_ratchet
