#!/usr/bin/env bash
# Countable-but-flat ARB floor ratchet (#3633): the set of app_en.arb keys that
# look countable yet carry no ICU plural is frozen in
# scripts/baseline/countable_flat_arb_keys.txt and may only ever SHRINK. See
# lib/list_ratchet.sh for the NEW/STALE/GROWTH semantics.
#
# Why this exists: a flat countable key still compiles and still renders the
# number — it only stops inflecting the noun, so English ships "1 videos". No
# other guard catches it. arb_consistency_test checks key and placeholder
# parity; plural_arm_number_test (#7153) only fires on arms that already exist.
# And bulk translation passes (e.g. #7237) improve locales while never touching
# the template, so English silently falls behind its own translations.
#
# Detector: scripts/lib/countable_flat_arb_detector.dart — a key is an offender
# when it interpolates a placeholder that is declared numeric OR the key is
# named `...Count`, and the value has no `{x, plural, ...}` selector.
#
# MOST BASELINE ENTRIES ARE INTENTIONALLY PERMANENT and must NEVER be
# pluralized — pluralizing them would be a bug, not a fix:
#   • unit symbols   `{count}d ago`, `{count}mo`, `{seconds}s`  (units don't inflect)
#   • percentages    `{percent}% complete`
#   • ordinals       `Clip {index} of {total}`, `Recording {number}`
#   • ratios         `{connected}/{total}`
#   • detached forms `Followers: {count}`, `Add {count}` (no noun to inflect)
# Each carries a trailing '# reason'. The ratchet never forces fixing them; it
# only stops the list from growing, so a NEW countable key must either be
# pluralized or have its exemption written down and reviewed.
#
# List a file's offenders:
#   cd mobile && dart run scripts/lib/countable_flat_arb_detector.dart \
#     lib/l10n/app_en.arb --detail
# Regenerate after pluralizing a key (never to excuse a new flat one):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_countable_plural_floor.sh
# Usage (from the repo root or mobile/): bash mobile/scripts/check_countable_plural_floor.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

RATCHET_LABEL="countable_plural_floor"
BASELINE_FILE="$SCRIPT_DIR/baseline/countable_flat_arb_keys.txt"
BASELINE_REPO_PATH="mobile/scripts/baseline/countable_flat_arb_keys.txt"
BASE_REF="${COUNTABLE_PLURAL_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${COUNTABLE_PLURAL_FLOOR_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="COUNTABLE_PLURAL_FLOOR_ALLOW_NO_BASE"
NEW_HINT="An app_en.arb key interpolates a count but has no ICU plural, so it renders text like \"1 videos\". Convert it to {count, plural, =1{...} other{...}} — interpolating {count} in every arm, never a hardcoded digit (#7153). If the number is NOT a quantity (a unit symbol, a percentage, an ordinal, a ratio, or a count detached from its noun), add it to the baseline with a trailing '# reason' instead. See #3633."
STALE_HINT="A baselined key gained ICU plural arms."
FOOTER="Countable-but-flat ARB keys are frozen and may only decrease. Pluralize
the key, or record why it must stay flat with a trailing '# reason'. Pluralizing
a unit, percentage, ordinal or ratio is WRONG — check the category first. See
#3633 and .claude/rules/localization.md."

emit_current() {
  (cd "$MOBILE_DIR" && dart run scripts/lib/countable_flat_arb_detector.dart \
    lib/l10n/app_en.arb 2>/dev/null | LC_ALL=C sort -u) || true
}

print_baseline_header() {
  cat <<'EOF'
# Frozen baseline: mobile/lib/l10n/app_en.arb keys that interpolate a count but
# carry no ICU plural. Generated by scripts/check_countable_plural_floor.sh. The
# set may only SHRINK (growth fails CI vs origin/main).
#
# A flat countable key still renders the number; it just stops inflecting the
# noun, shipping "1 videos". Most entries below are intentionally PERMANENT —
# units, percentages, ordinals, ratios and counts detached from their noun must
# NEVER be pluralized. The trailing '# reason' says which. Issue: #3633.
EOF
}

# shellcheck source=lib/list_ratchet.sh
source "$SCRIPT_DIR/lib/list_ratchet.sh"
run_list_ratchet
