#!/usr/bin/env bash
# Post-close emit/add ceiling ratchet (#7370, prevention follow-up to #7293 and
# #7356): every Dart file under mobile/lib holding a bloc/cubit `emit` or `add`
# that can run after `close()` is frozen at its current count in
# scripts/baseline/post_close_emit.txt, a per-file CEILING that may only ever
# DECREASE.
#
# Why: `close()` does not cancel in-flight work. An awaited future resumes into
# a disposed cubit and `BlocBase.emit` throws `Bad state: Cannot emit new states
# after calling close`; `Bloc.close()` closes the event controller BEFORE the
# queue drains, so a pending handler's `add` throws `Bad state: Cannot add new
# events after calling close`. Both shipped as Crashlytics aggregates (#7293)
# and #7356 found the same shape at eight more call sites after nine had already
# been fixed one at a time — a recurring pattern, not a one-off defect.
#
# The fix at each site is lib/blocs/close_guard.dart:
#     class FooCubit extends Cubit<FooState> with CloseGuardedEmit<FooState>
#     ...
#     emitIfOpen(state.copyWith(...));   // instead of emit(...)
#     addIfOpen(const FooRefreshed());   // instead of add(...)
# An `if (isClosed) return;` between the suspension point and the call clears a
# site too — the guard mixin exists to stop that boilerplate being re-invented
# as a private `_emitIfOpen` in every fifth cubit.
#
# Not every counted site is a live crash: a cubit whose owner never disposes it
# mid-flight cannot reach the throw. The ceiling still only shrinks, because a
# guarded emit is never *worse* than an unguarded one and the fix is uniform.
#
# Detector: scripts/lib/post_close_emit_detector.dart (a real Dart AST — the
# `emit` parameter of an `on<Event>` handler is `Emitter.call`, which `close()`
# cancels rather than throws, so it must NOT be counted; that distinction is not
# expressible as a regex). See that file's header for the full rule.
#
# Per-key NUMERIC ceiling: a file may drop sites freely while above zero without
# churning the baseline; only growth / a new file / a raised ceiling /
# drop-to-zero (STALE) fails. Generated code excluded by path and suffix.
#
# Regenerate after GUARDING sites (never to raise):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_post_close_emit_ceiling.sh
# Run (from repo root or mobile/): bash mobile/scripts/check_post_close_emit_ceiling.sh
# List the individual sites in a file:
#   dart run scripts/lib/post_close_emit_detector.dart lib --detail

set -euo pipefail
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TAB="$(printf '\t')"

RATCHET_LABEL="post_close_emit_ceiling"
SCAN_DIR="${POST_CLOSE_EMIT_SCAN_DIR:-$MOBILE_DIR/lib}"
PATH_PREFIX="${POST_CLOSE_EMIT_PATH_PREFIX:-$MOBILE_DIR}"
BASELINE_FILE="${POST_CLOSE_EMIT_BASELINE_FILE:-$SCRIPT_DIR/baseline/post_close_emit.txt}"
BASELINE_REPO_PATH="${POST_CLOSE_EMIT_BASELINE_REPO_PATH:-mobile/scripts/baseline/post_close_emit.txt}"
BASE_REF="${POST_CLOSE_EMIT_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${POST_CLOSE_EMIT_CEILING_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="POST_CLOSE_EMIT_CEILING_ALLOW_NO_BASE"
DART_BIN="${POST_CLOSE_EMIT_DART:-dart}"

NEW_HINT="Work that resumes after close() must not reach a bare emit()/add(). Mix in CloseGuardedEmit and call emitIfOpen (or addIfOpen, from the CloseGuardedAdd extension) — both in lib/blocs/close_guard.dart — or return early on isClosed after the await. Cancelling the work is better still where it is cancellable. See #7293 / #7356."
STALE_HINT="A file guarded every post-close emit/add it had."
FOOTER="Unguarded post-close emit/add sites under mobile/lib are frozen and may only decrease.
Use emitIfOpen / addIfOpen from lib/blocs/close_guard.dart; see issues #7293,
#7356 and #7370. Inspect a file's sites with:
  dart run scripts/lib/post_close_emit_detector.dart lib --detail"

# Print "relpath<TAB>count" for every file under SCAN_DIR with at least one
# unguarded post-close emit/add. Runs from MOBILE_DIR so the detector resolves
# package:analyzer from the app's package config.
emit_current() {
  (
    cd "$MOBILE_DIR"
    "$DART_BIN" run scripts/lib/post_close_emit_detector.dart \
      "$SCAN_DIR" --path-prefix "$PATH_PREFIX"
  ) | LC_ALL=C sort -t "$TAB" -k1,1
}

print_baseline_header() {
  cat <<EOF
# Frozen baseline: Dart files under mobile/lib with a bloc/cubit emit()/add()
# that can run after close() with no isClosed guard, each with its current count
# as a CEILING (format: relpath<TAB>count). Generated by
# scripts/check_post_close_emit_ceiling.sh from
# scripts/lib/post_close_emit_detector.dart. A ceiling may only SHRINK; more
# sites, a new file, or a raised ceiling fails CI vs ${BASE_REF}. The fix is
# emitIfOpen / addIfOpen from lib/blocs/close_guard.dart, or an early return on
# isClosed after the suspension point (#7293, #7356, #7370). An on<Event>
# handler's own \`emit\` is Emitter.call, which close() cancels instead of
# throwing, and is never counted. Regenerate after guarding sites:
#   UPDATE_BASELINE=1 bash scripts/check_post_close_emit_ceiling.sh
EOF
}

# shellcheck source=lib/numeric_ratchet.sh
source "$SCRIPT_DIR/lib/numeric_ratchet.sh"
run_numeric_ratchet
