#!/usr/bin/env bash
# Unsafe-back-pop ceiling ratchet (#6481, closes the regression loop on #6112):
# every Dart file under mobile/lib that wires an app-bar back button straight to
# a raw pop (`onBackPressed: context.pop`, `onBackPressed: () => context.pop()`,
# `onBackPressed: () => Navigator.of(context).pop()`) is frozen at its current
# count in scripts/baseline/unsafe_back_pops.txt, a per-file CEILING that may
# only ever DECREASE.
#
# Why: go_router nests by route TREE, not by path string. A top-level GoRoute
# with a multi-segment path (/settings/supporter) matches as a single entry on a
# cold entry — an account swap re-seeds routerInitialLocationProvider with the
# current location — so canPop() is false and context.pop() throws
# `GoError: There is nothing to pop`, leaving the user on a dead back button.
# That crash shipped as a FATAL (Crashlytics 5c465b01…, 7 users / 16 events),
# was fixed, and REGRESSED — there was no guard. This is the guard.
#
# The fix at each site is BuildContext.safePop from
# lib/extensions/safe_pop_extension.dart, which falls back to a route instead of
# throwing:
#     onBackPressed: () => context.safePop(fallback: SettingsScreen.path),
#
# Not every counted site is a live bug: a screen only ever reached by push from
# a mounted parent always has something to pop. The ceiling still only shrinks,
# because a raw pop is never *safer* than safePop and the cheap fix is uniform.
#
# Detector (occurrences, in code only — see lib/dart_code_only.awk, then
# whitespace-collapsed so dart format line wrapping cannot hide a call):
#   onBackPressed:[[:space:]]*(\(\)[[:space:]]*=>[[:space:]]*)?
#     (context\.pop|Navigator\.of\(context\)\.pop)
#
# Per-key NUMERIC ceiling: a file may drop calls freely while above zero without
# churning the baseline; only growth / new file / raised ceiling / drop-to-zero
# (STALE) fails. Generated code excluded by path and suffix.
#
# Regenerate after MIGRATING a site to safePop (never to raise):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_unsafe_back_pop_ceiling.sh
# Run (from repo root or mobile/): bash mobile/scripts/check_unsafe_back_pop_ceiling.sh

set -euo pipefail
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TAB="$(printf '\t')"

RATCHET_LABEL="unsafe_back_pop_ceiling"
SCAN_DIR="${UNSAFE_BACK_POP_SCAN_DIR:-$MOBILE_DIR/lib}"
PATH_PREFIX="${UNSAFE_BACK_POP_PATH_PREFIX:-$MOBILE_DIR}"
BASELINE_FILE="${UNSAFE_BACK_POP_BASELINE_FILE:-$SCRIPT_DIR/baseline/unsafe_back_pops.txt}"
BASELINE_REPO_PATH="${UNSAFE_BACK_POP_BASELINE_REPO_PATH:-mobile/scripts/baseline/unsafe_back_pops.txt}"
BASE_REF="${UNSAFE_BACK_POP_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${UNSAFE_BACK_POP_CEILING_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="UNSAFE_BACK_POP_CEILING_ALLOW_NO_BASE"

DETECT_RE='onBackPressed:[[:space:]]*(\(\)[[:space:]]*=>[[:space:]]*)?(context\.pop|Navigator\.of\(context\)\.pop)'

NEW_HINT="Don't wire an app-bar back button to a raw pop — use context.safePop(fallback: …) from lib/extensions/safe_pop_extension.dart. A routed screen entered cold has a one-entry stack, and context.pop() then throws GoError: There is nothing to pop (FATAL #6112, #6481). Note: only real code counts — comments and string literals are stripped."
STALE_HINT="A file dropped its raw back-button pop (migrated to safePop or removed)."
FOOTER="Raw back-button pops under mobile/lib are frozen and may only decrease.
Use context.safePop(fallback: …) instead; see lib/extensions/safe_pop_extension.dart,
issue #6112 (FATAL, regressed) and #6481."

# Print "relpath<TAB>count" for every non-generated Dart file under SCAN_DIR that
# wires a back button to a raw pop (in code only), by path.
emit_current() {
  find "$SCAN_DIR" \
    -type f -name '*.dart' \
    -not -path '*/l10n/generated/*' \
    -not -path '*/.dart_tool/*' \
    -not -path '*/build/*' \
    ! -name '*.g.dart' ! -name '*.freezed.dart' ! -name '*.gr.dart' \
    ! -name '*.config.dart' ! -name '*.mocks.dart' \
    -print0 2>/dev/null \
  | while IFS= read -r -d '' f; do
      count="$(awk -f "$SCRIPT_DIR/lib/dart_code_only.awk" "$f" 2>/dev/null \
        | tr '\n' ' ' \
        | grep -oE "$DETECT_RE" \
        | grep -c . || true)"
      count="${count//[[:space:]]/}"
      if [[ "${count:-0}" -gt 0 ]]; then
        printf '%s\t%s\n' "${f#"$PATH_PREFIX"/}" "$count"
      fi
    done \
  | LC_ALL=C sort -t "$TAB" -k1,1
}

print_baseline_header() {
  cat <<EOF
# Frozen baseline: Dart files under mobile/lib wiring an app-bar back button to a
# raw pop (onBackPressed: context.pop / () => context.pop() /
# () => Navigator.of(context).pop()), each with its current count as a CEILING
# (format: relpath<TAB>count). Generated by
# scripts/check_unsafe_back_pop_ceiling.sh. A ceiling may only SHRINK; more raw
# pops, a new file, or a raised ceiling fails CI vs ${BASE_REF}. Use
# context.safePop(fallback: …) instead — a routed screen entered cold has a
# one-entry stack and context.pop() throws GoError there (FATAL #6112, #6481).
# Comments and string literals are not counted. Regenerate after migrating:
#   UPDATE_BASELINE=1 bash scripts/check_unsafe_back_pop_ceiling.sh
EOF
}

# shellcheck source=lib/numeric_ratchet.sh
source "$SCRIPT_DIR/lib/numeric_ratchet.sh"
run_numeric_ratchet
