#!/usr/bin/env bash
# Package coverage floor (issue #3575 follow-up): every per-package CI workflow
# delegates to VeryGood's flutter_package workflow, which gates the package on a
# `min_coverage:` floor — the value the workflow declares, or 100 when the input
# is omitted (VGV defaults it to 100). VGV fails when a package's MEASURED
# coverage drops below that floor, but nothing stops the FLOOR ITSELF from being
# lowered — so "set at measured coverage now, ratchet up later" was an
# intention, not a mechanism.
#
# An OMITTED min_coverage is an EFFECTIVE 100% floor and is locked as such, not
# skipped: otherwise a package sitting at the 100 default (e.g. follow_repository,
# content_policy, feed_tuning_repository) could later add `min_coverage: 0` and
# land as a brand-new baseline entry rather than being caught as a decrease.
#
# This guard turns each floor into a MONOTONIC ratchet:
#   1. SYNC      — the `min_coverage:` declared in .github/workflows/<pkg>.yaml
#                  must match the committed baseline
#                  (baseline/package_coverage_floors.txt). A workflow may not
#                  declare below its locked floor; raising a floor requires
#                  re-baselining so the higher value is recorded.
#   2. MONOTONIC — no baselined floor may DECREASE vs origin/main. This closes
#                  the bypass where a PR lowers a workflow's min_coverage, reruns
#                  UPDATE_BASELINE, and commits the lowered baseline.
# Floors may only ever rise. Combined with VGV's measured>=floor check, a
# package's enforced coverage can only climb over time.
#
# It does NOT force a floor up to live coverage automatically — that would
# require abandoning the shared VGV reusable-workflow pattern (you cannot append
# a coverage-comparison step to a `uses:` reusable workflow) and doubling the
# coverage run. Bumping a floor stays a deliberate, reviewed act; this guard
# guarantees the bump can never be silently undone.
#
# Raise a floor after coverage improves:
#   1. edit `min_coverage:` in .github/workflows/<pkg>.yaml to the new value
#   2. UPDATE_BASELINE=1 bash mobile/scripts/check_package_coverage_floor.sh
# Usage (from the repo root or mobile/):
#   bash mobile/scripts/check_package_coverage_floor.sh

set -euo pipefail
# Byte-wise, locale-independent ordering so sort/join/comm agree across macOS
# (local) and Linux (CI); otherwise the baseline diff can falsely flag drift.
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$MOBILE_DIR/.." && pwd)"
WF_DIR="$REPO_ROOT/.github/workflows"

BASELINE_FILE="$SCRIPT_DIR/baseline/package_coverage_floors.txt"
BASELINE_REPO_PATH="mobile/scripts/baseline/package_coverage_floors.txt"
BASE_REF="${PACKAGE_COVERAGE_FLOOR_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${PACKAGE_COVERAGE_FLOOR_ALLOW_NO_BASE:-0}"

# Emit "<pkg> <floor>" for every package under mobile/packages whose CI workflow
# delegates to VGV's flutter_package reusable workflow. The floor is the declared
# `min_coverage:`, or 100 when omitted (VGV's default). Only VGV workflows carry
# a coverage gate to ratchet, so a workflow that does not use flutter_package.yml
# is skipped. Accepted workflow filenames match check_package_ci_floor.sh:
# <pkg>.yaml, <pkg>.yml, <pkg>_ci.yaml, <pkg>_ci.yml.
emit_current() {
  local pubspec pkg cand wf mc
  for pubspec in "$MOBILE_DIR"/packages/*/pubspec.yaml; do
    [ -f "$pubspec" ] || continue
    pkg="$(basename "$(dirname "$pubspec")")"
    wf=""
    for cand in "$pkg.yaml" "$pkg.yml" "${pkg}_ci.yaml" "${pkg}_ci.yml"; do
      if [ -f "$WF_DIR/$cand" ]; then
        wf="$WF_DIR/$cand"
        break
      fi
    done
    [ -n "$wf" ] || continue
    grep -q 'flutter_package\.yml' "$wf" || continue
    mc="$(grep -oE 'min_coverage:[[:space:]]*[0-9]+' "$wf" | head -1 |
      grep -oE '[0-9]+' || true)"
    # Omitted min_coverage inherits VGV's default of 100.
    [ -n "$mc" ] || mc=100
    echo "$pkg $mc"
  done | LC_ALL=C sort
}

# Strip trailing "# reason" comments and blank/comment lines from a baseline
# stream, leaving sorted "<pkg> <floor>" pairs.
strip_baseline() {
  sed 's/[[:space:]]*#.*//; s/[[:space:]]*$//' | grep -v '^$' | LC_ALL=C sort || true
}

print_baseline_header() {
  cat <<'EOF'
# Locked per-package coverage floors. Generated by
# scripts/check_package_coverage_floor.sh. Each line is "<pkg> <min_coverage>"
# mirroring the floor declared in .github/workflows/<pkg>.yaml — or 100 when the
# workflow omits min_coverage, since VGV defaults that input to 100. Floors are a
# MONOTONIC ratchet: they may only RISE (a decrease fails CI vs origin/main). A
# trailing '# reason' documents an unusual floor. Follow-up to issue #3575.
EOF
}

# Regenerate the baseline from the current declared floors, preserving any
# trailing "# reason" comment attached to a package.
write_baseline() {
  local current="$1"
  local reasons_file
  reasons_file="$(mktemp)"
  if [ -f "$BASELINE_FILE" ]; then
    awk '
      /^[[:space:]]*#/ || /^[[:space:]]*$/ { next }
      {
        pkg = $1
        comment = ""
        if (match($0, /[[:space:]]+#.*/)) {
          comment = substr($0, RSTART)
          sub(/^[[:space:]]+/, "", comment)
        }
        if (comment != "") { print pkg "\t" comment }
      }
    ' "$BASELINE_FILE" >"$reasons_file"
  fi
  mkdir -p "$(dirname "$BASELINE_FILE")"
  {
    print_baseline_header
    while IFS= read -r line; do
      [ -z "$line" ] && continue
      pkg="${line%% *}"
      reason="$(awk -F '\t' -v t="$pkg" '$1 == t { print $2; exit }' "$reasons_file")"
      if [ -n "$reason" ]; then
        printf '%s %s\n' "$line" "$reason"
      else
        printf '%s\n' "$line"
      fi
    done <<<"$current"
  } >"$BASELINE_FILE"
  rm -f "$reasons_file"
}

# Load the baseline from the base ref into stdout (stripped). Return:
#   0 loaded; 2 base ref ok but file absent (bootstrap); 1 base ref
#   unresolvable; 3 file exists but blob unreadable.
load_base_baseline() {
  if ! git -C "$REPO_ROOT" rev-parse --verify --quiet "$BASE_REF" >/dev/null 2>&1; then
    git -C "$REPO_ROOT" fetch --quiet --depth=1 origin main 2>/dev/null || true
  fi
  if ! git -C "$REPO_ROOT" rev-parse --verify --quiet "$BASE_REF" >/dev/null 2>&1; then
    return 1
  fi
  if ! git -C "$REPO_ROOT" cat-file -e "$BASE_REF:$BASELINE_REPO_PATH" 2>/dev/null; then
    return 2
  fi
  git -C "$REPO_ROOT" show "$BASE_REF:$BASELINE_REPO_PATH" 2>/dev/null | strip_baseline
}

CURRENT="$(emit_current)"

if [ "${UPDATE_BASELINE:-0}" = "1" ]; then
  write_baseline "$CURRENT"
  count="$(printf '%s\n' "$CURRENT" | grep -c . || true)"
  echo "OK [package_coverage_floor]: wrote $count floor(s) to ${BASELINE_FILE#"$MOBILE_DIR"/}."
  exit 0
fi

if [ ! -f "$BASELINE_FILE" ]; then
  echo "FAIL [package_coverage_floor]: baseline missing ($BASELINE_REPO_PATH)."
  echo "  -> Generate it: UPDATE_BASELINE=1 bash mobile/scripts/check_package_coverage_floor.sh"
  exit 1
fi

BASELINE="$(strip_baseline <"$BASELINE_FILE")"

# --- Check 1: SYNC — declared floors must match the locked baseline. ---
cur_file="$(mktemp)"
base_file="$(mktemp)"
printf '%s\n' "$CURRENT" | grep -v '^$' >"$cur_file" || true
printf '%s\n' "$BASELINE" | grep -v '^$' >"$base_file" || true

sync_fail=0
# Packages declared in a workflow but absent from the baseline (NEW).
new_pkgs="$(join -v1 "$cur_file" "$base_file" 2>/dev/null | awk '{print $1}' || true)"
# Packages in the baseline whose workflow/floor no longer exists (STALE).
gone_pkgs="$(join -v2 "$cur_file" "$base_file" 2>/dev/null | awk '{print $1}' || true)"
# Packages in both whose declared floor differs from the locked value (DRIFT).
drift="$(join "$cur_file" "$base_file" 2>/dev/null |
  awk '$2 != $3 { print $1, "declared="$2, "locked="$3 }' || true)"

if [ -n "$new_pkgs" ]; then
  sync_fail=1
  echo "FAIL [package_coverage_floor]: workflow floor(s) not recorded in the baseline:"
  printf '%s\n' "$new_pkgs" | sed 's/^/  /'
fi
if [ -n "$gone_pkgs" ]; then
  sync_fail=1
  echo "FAIL [package_coverage_floor]: baselined package(s) no longer declare a floor:"
  printf '%s\n' "$gone_pkgs" | sed 's/^/  /'
fi
if [ -n "$drift" ]; then
  sync_fail=1
  echo "FAIL [package_coverage_floor]: declared floor(s) drift from the locked baseline:"
  printf '%s\n' "$drift" | sed 's/^/  /'
fi
rm -f "$cur_file" "$base_file"

if [ "$sync_fail" = "1" ]; then
  echo "  -> The baseline is the locked source of truth. If you intentionally"
  echo "     raised a floor (or added/removed a package workflow), re-lock it:"
  echo "       UPDATE_BASELINE=1 bash mobile/scripts/check_package_coverage_floor.sh"
  echo "     A declared value BELOW the locked floor is a floor regression — raise"
  echo "     it back to (or above) the baseline instead."
  exit 1
fi

# --- Check 2: MONOTONIC — no locked floor may decrease vs the base ref. ---
base_baseline=""
if base_baseline="$(load_base_baseline)"; then
  :
else
  case "$?" in
    2)
      echo "OK [package_coverage_floor]: baseline absent on $BASE_REF (bootstrap); monotonic check skipped."
      echo "OK [package_coverage_floor]: $(printf '%s\n' "$CURRENT" | grep -c . || true) floor(s) in sync."
      exit 0
      ;;
    *)
      if [ "$ALLOW_NO_BASE" = "1" ]; then
        echo "WARN [package_coverage_floor]: base ref $BASE_REF unavailable; monotonic check skipped (PACKAGE_COVERAGE_FLOOR_ALLOW_NO_BASE=1)."
        echo "OK [package_coverage_floor]: floors in sync with the local baseline."
        exit 0
      fi
      echo "FAIL [package_coverage_floor]: cannot load the baseline from $BASE_REF."
      echo "  -> CI must never silently skip the ratchet, so this fails closed."
      echo "     Ensure origin/main is fetched (git fetch --depth=1 origin main)."
      echo "     For an intentional offline run: PACKAGE_COVERAGE_FLOOR_ALLOW_NO_BASE=1"
      exit 1
      ;;
  esac
fi

branch_base_file="$(mktemp)"
ref_base_file="$(mktemp)"
printf '%s\n' "$BASELINE" | grep -v '^$' >"$branch_base_file" || true
printf '%s\n' "$base_baseline" | grep -v '^$' >"$ref_base_file" || true

# For packages present in both baselines, the branch floor must be >= base floor.
lowered="$(join "$branch_base_file" "$ref_base_file" 2>/dev/null |
  awk '($2 + 0) < ($3 + 0) { print $1, "was="$3, "now="$2 }' || true)"
rm -f "$branch_base_file" "$ref_base_file"

if [ -n "$lowered" ]; then
  echo "FAIL [package_coverage_floor]: coverage floor(s) LOWERED vs $BASE_REF:"
  printf '%s\n' "$lowered" | sed 's/^/  /'
  echo "  -> Floors are a monotonic ratchet — they may only rise. Restore each"
  echo "     floor to at least its origin/main value in the workflow and baseline."
  echo "     (If origin/main legitimately lowered a floor, rebase onto it rather"
  echo "     than re-running UPDATE_BASELINE against a stale checkout.)"
  exit 1
fi

echo "OK [package_coverage_floor]: $(printf '%s\n' "$CURRENT" | grep -c . || true) floor(s) locked; none lowered vs $BASE_REF."
