#!/usr/bin/env bash
# Pubkey log-encoding ratchet (#8066): pubkeys reaching a log/debug sink in one
# encoding instead of npub plus hex are frozen at zero per file in
# scripts/baseline/pubkey_log_encoding.txt — a CEILING that may only shrink.
# The baseline is intentionally EMPTY: #8066 closed every site, so any entry
# here is a regression.
#
# Why: hex is the wire and database encoding. It greps against relay logs,
# ClickHouse and funnelcake rows, which is why #3372 made us log it whole. It
# is also the one encoding nobody can use during triage — a support log names
# an author or a DM counterparty, and answering "who is that" means a manual
# bech32 conversion before you can look the account up, message the user, or
# paste it anywhere. Bug reports flow Zendesk -> GitHub one way, with no reply
# channel back to the reporter, so whatever the log carries is all we get.
#
# The fix is both encodings, never one: render through pubkeyForLogs
# (packages/nostr_sdk/lib/nip19/pubkey_for_logs.dart), which takes hex or npub
# and emits `npub1…full (…full hex)`. It never truncates either form, so the
# zero in check_nostr_id_log_truncation.sh (#3372) still holds, and it redacts
# an nsec or ncryptsec whole rather than rendering it.
#
# What this guard does NOT count:
#   • A count, length, boolean or joined string that merely mentions a pubkey —
#     `${pubkeys.length}` has no identifier left to encode.
#   • A collection. The formatter takes one value; a list needs
#     `.map(pubkeyForLogs)`, which is a rewrite this guard has no opinion about.
#   • Test trees. A test asserting on a log line is not a log support reads.
#
# Detector: scripts/lib/pubkey_log_encoding_detector.dart (a real Dart AST).
# A grep cannot do this: `// TODO: log the pubkey`, `Log.info('pubkey missing')`,
# a dartdoc `[pubkey]`, and `${pubkeys.length}` all match a text rule and none
# of them logs an identifier. See that file's header for the rule and its
# stated limits.
#
# Regenerate ONLY after an intentional, reviewed change:
#   UPDATE_BASELINE=1 bash mobile/scripts/check_pubkey_log_encoding.sh
# Run (from repo root or mobile/):
#   bash mobile/scripts/check_pubkey_log_encoding.sh
# List the individual sites:
#   dart run scripts/lib/pubkey_log_encoding_detector.dart lib packages --detail

set -euo pipefail
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TAB="$(printf '\t')"

RATCHET_LABEL="pubkey_log_encoding"
PATH_PREFIX="${PUBKEY_LOG_ENCODING_PATH_PREFIX:-$MOBILE_DIR}"
BASELINE_FILE="${PUBKEY_LOG_ENCODING_BASELINE_FILE:-$SCRIPT_DIR/baseline/pubkey_log_encoding.txt}"
BASELINE_REPO_PATH="${PUBKEY_LOG_ENCODING_BASELINE_REPO_PATH:-mobile/scripts/baseline/pubkey_log_encoding.txt}"
BASE_REF="${PUBKEY_LOG_ENCODING_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${PUBKEY_LOG_ENCODING_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="PUBKEY_LOG_ENCODING_ALLOW_NO_BASE"
DART_BIN="${PUBKEY_LOG_ENCODING_DART:-dart}"

# Space-separated roots. Production code only — app plus every workspace
# package; the detector additionally skips test trees inside those roots.
SCAN_DIR="${PUBKEY_LOG_ENCODING_SCAN_DIR:-$MOBILE_DIR/lib $MOBILE_DIR/packages}"

NEW_HINT="Render the pubkey through pubkeyForLogs so the log carries both encodings: '\${pubkeyForLogs(pubkey)}' instead of '\$pubkey'. It accepts hex or npub, never truncates either, and takes whenNull: when the call site's own wording for an absent value is itself diagnostic. For a list, map it: '\${pubkeys.map(pubkeyForLogs).join(\", \")}'. AGENTS.md → Nostr And Async Rules; #8066."
STALE_HINT="A file stopped logging a pubkey in a single encoding."
FOOTER="Pubkeys reaching a log sink in one encoding are frozen at zero.
Hex greps against relay and backend rows; npub is what a person can actually
use. A support log needs both, and Zendesk reports are one-way, so what the
log carries is all we get. See AGENTS.md (Nostr And Async Rules) and #8066.
Inspect the sites with:
  dart run scripts/lib/pubkey_log_encoding_detector.dart lib packages --detail"

# Print "relpath<TAB>count" for every file with at least one site. Runs from
# MOBILE_DIR so the detector resolves package:analyzer from the app's config.
emit_current() {
  (
    cd "$MOBILE_DIR"
    # shellcheck disable=SC2086
    "$DART_BIN" run scripts/lib/pubkey_log_encoding_detector.dart \
      $SCAN_DIR --path-prefix "$PATH_PREFIX"
  ) | LC_ALL=C sort -t "$TAB" -k1,1
}

print_baseline_header() {
  cat <<EOF
# Frozen baseline: production Dart files under mobile/lib and mobile/packages
# that interpolate a pubkey into a log/debug sink in one encoding instead of
# npub plus hex (format: relpath<TAB>count).
# The list is intentionally EMPTY — #8066 closed every site, so any entry here
# is a regression. Generated by scripts/check_pubkey_log_encoding.sh from
# scripts/lib/pubkey_log_encoding_detector.dart. Fix the log call rather than
# regenerating this file: render through pubkeyForLogs.
# Counts, booleans and collections that merely mention a pubkey are NOT counted.
# Issue: #8066.
EOF
}

# shellcheck source=lib/numeric_ratchet.sh
source "$SCRIPT_DIR/lib/numeric_ratchet.sh"
run_numeric_ratchet
