#!/usr/bin/env bash
# Empty-catch ceiling ratchet (epic #4336 / #3588, #8309): undocumented empty
# catch blocks under mobile/lib and mobile/packages/*/lib are frozen at ZERO in
# scripts/baseline/empty_catches.txt. An empty catch swallows errors silently,
# defeating the per-layer failure contract
# (.claude/rules/error_handling.md). The fix is to log + classify (wrap with
# Reportable where the decision matrix says so) or document an intentional no-op
# (which then contains a comment, so it is no longer "empty").
#
# The Dart AST detector covers single-line, multiline, typed `on Foo`, and
# stack-trace forms without matching catch-like text in strings or comments.
# A comment inside a statement-free catch documents an intentional no-op and is
# not counted. Inspect individual sites with:
#   cd mobile && dart run scripts/lib/empty_catch_detector.dart \
#     lib packages --path-prefix . --detail
#
# Frozen at zero: fix the call site rather than regenerating the baseline.
# Usage (from repo root or mobile/):
#   bash mobile/scripts/check_empty_catch_ceiling.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TAB="$(printf '\t')"

RATCHET_LABEL="empty_catch_ceiling"
BASELINE_FILE="${EMPTY_CATCH_BASELINE_FILE:-$SCRIPT_DIR/baseline/empty_catches.txt}"
BASELINE_REPO_PATH="${EMPTY_CATCH_BASELINE_REPO_PATH:-mobile/scripts/baseline/empty_catches.txt}"
BASE_REF="${EMPTY_CATCH_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${EMPTY_CATCH_CEILING_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="EMPTY_CATCH_CEILING_ALLOW_NO_BASE"
DART_BIN="${EMPTY_CATCH_DART:-dart}"
SCAN_DIRS="${EMPTY_CATCH_SCAN_DIRS:-lib packages}"
PATH_PREFIX="${EMPTY_CATCH_PATH_PREFIX:-$MOBILE_DIR}"
NEW_HINT="Don't swallow errors with an empty catch. Log + classify (wrap with Reportable per the matrix in .claude/rules/error_handling.md) or document an intentional no-op. See #8309 and epic #4336 / #3588."
STALE_HINT="An empty catch was removed from a file."
FOOTER="Empty catch blocks in mobile/lib and mobile/packages/*/lib are frozen at zero.
Replace them with logging + typed classification, or an explicitly documented
no-op. See .claude/rules/error_handling.md, #8309 and epic #4336 (#3588).
Inspect the sites with:
  cd mobile && dart run scripts/lib/empty_catch_detector.dart lib packages --path-prefix . --detail"

emit_current() {
  (
    cd "$MOBILE_DIR"
    # shellcheck disable=SC2086
    "$DART_BIN" run scripts/lib/empty_catch_detector.dart \
      $SCAN_DIRS --path-prefix "$PATH_PREFIX"
  ) | LC_ALL=C sort -t "$TAB" -k1,1
}

print_baseline_header() {
  cat <<'EOF'
# Frozen baseline: Dart files under mobile/lib and mobile/packages/*/lib holding
# undocumented empty catch bodies (format: relpath<TAB>count). Generated by
# scripts/check_empty_catch_ceiling.sh from
# scripts/lib/empty_catch_detector.dart.
#
# Frozen at ZERO (#8309; epic #4336 / #3588). Any entry is a regression: log +
# classify the failure or document why the statement-free catch is intentional.
EOF
}

# shellcheck source=lib/numeric_ratchet.sh
source "$SCRIPT_DIR/lib/numeric_ratchet.sh"
run_numeric_ratchet
