#!/usr/bin/env bash
# test/unit structure ratchet (epic #4337, WS-7): the set of test files under
# mobile/test/unit — the legacy non-mirroring accretion bucket — is frozen in
# scripts/baseline/test_unit_files.txt and may only ever SHRINK. See
# lib/list_ratchet.sh for the NEW/STALE/GROWTH semantics.
#
# Detector: every *_test.dart path under mobile/test/unit (mobile-relative).
# NEW fires when a test lands under test/unit instead of mirroring lib/ (e.g.
# lib/services/foo.dart -> test/services/foo_test.dart, NOT test/unit/...).
# STALE fires when a baselined test moves out to its lib/ mirror or is deleted —
# shrink the baseline to lock the win in.
#
# This is a structure guard, not a coverage or content check: it only prevents
# the non-mirroring test/unit tree from growing back. Draining it to zero is an
# opt-in follow-up, not required by this ratchet.
#
# Regenerate ONLY when a test legitimately leaves test/unit (never to add one):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_test_unit_structure.sh
# Usage (from repo root or mobile/): bash mobile/scripts/check_test_unit_structure.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

RATCHET_LABEL="test_unit_structure"
BASELINE_FILE="$SCRIPT_DIR/baseline/test_unit_files.txt"
BASELINE_REPO_PATH="mobile/scripts/baseline/test_unit_files.txt"
BASE_REF="${TEST_UNIT_STRUCTURE_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${TEST_UNIT_STRUCTURE_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="TEST_UNIT_STRUCTURE_ALLOW_NO_BASE"
NEW_HINT="A new test lives under test/unit. Mirror lib/ instead — put it at the
path that matches its source (e.g. lib/services/foo.dart -> test/services/foo_test.dart).
See tasks/plan_4337.md (WS-7) and .claude/rules/testing.md."
STALE_HINT="A test moved out of test/unit to its lib/ mirror (or was deleted)."
FOOTER="The test/unit bucket is frozen and may only shrink. New tests must mirror
lib/ (never test/unit/). If you intentionally moved one out, shrink the baseline:
UPDATE_BASELINE=1 bash mobile/scripts/check_test_unit_structure.sh. See
tasks/plan_4337.md (WS-7)."

# Mobile-relative paths of every *_test.dart under test/unit.
# NOTE (differs from check_skip_ceiling.sh on purpose): the '2>/dev/null ... || true'
# tail is mandatory here because test/unit can vanish once fully drained, and a
# bare 'find <absent-dir>' exits 1 — which would abort under 'set -euo pipefail'.
# Paths are mobile-relative (sed strip), NOT bare basenames, so same-name files in
# different subdirs never collapse under 'sort -u'.
emit_current() {
  find "$MOBILE_DIR/test/unit" -type f -name '*_test.dart' \
    -not -path '*/.dart_tool/*' -not -path '*/build/*' 2>/dev/null \
    | sed "s#^$MOBILE_DIR/##" | LC_ALL=C sort -u || true
}

print_baseline_header() {
  cat <<'EOF'
# Frozen baseline: test files under mobile/test/unit — the legacy non-mirroring
# accretion bucket. Generated by scripts/check_test_unit_structure.sh. The set
# may only SHRINK (any NEW file under test/unit fails CI vs origin/main). New
# tests must mirror lib/ (e.g. test/services/foo_test.dart), never test/unit/.
# Epic: #4337 (WS-7). See tasks/plan_4337.md.
EOF
}

# shellcheck source=lib/list_ratchet.sh
source "$SCRIPT_DIR/lib/list_ratchet.sh"
run_list_ratchet
