#!/usr/bin/env bash
# Package Flutter-dependency boundary ratchet (#3338). Freezes the set of
# packages under mobile/packages that declare a RUNTIME Flutter SDK dependency.
# The set may only ever SHRINK: a package re-adding `flutter: sdk: flutter` to
# its `dependencies:` fails CI. See lib/list_ratchet.sh for NEW/STALE/GROWTH
# semantics and docs/ARCHITECTURE.md ("Which packages may depend on Flutter")
# for the policy this enforces.
#
# Why this is worth a guard. Every package under mobile/packages carries its own
# analysis_options.yaml including very_good_analysis, which enables
# `depend_on_referenced_packages`. With no `flutter:` entry, a
# `package:flutter/...` import anywhere in that package's lib/ or test/ is an
# analyze failure, and each package's own CI workflow runs `flutter analyze`. So
# the entry's absence is what makes the layer boundary enforced rather than
# conventional — and re-adding it silently re-opens the boundary for every file
# in the package at once. This ratchet makes that re-opening a reviewable
# baseline edit instead of a one-line pubspec change nobody notices.
#
# Detector: a package whose pubspec `dependencies:` block contains a
# `flutter:` or `flutter_web_plugins:` key whose next line is `sdk: flutter`.
# `dev_dependencies:` is deliberately NOT scanned — `flutter_test` is fine and
# does not widen what lib/ may import; 15 of the 37 packages with no runtime
# Flutter dependency already ship that shape.
# Being a line-shape proxy it assumes the two-line `flutter:\n    sdk: flutter`
# form that every pubspec here uses and `dart format`/pub preserve.
#
# Regenerate ONLY after REMOVING a dependency (never to add one):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_package_flutter_boundary.sh
# Usage (from the repo root or mobile/):
#   bash mobile/scripts/check_package_flutter_boundary.sh

set -euo pipefail
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

RATCHET_LABEL="package_flutter_boundary"
BASELINE_FILE="$SCRIPT_DIR/baseline/package_flutter_deps.txt"
BASELINE_REPO_PATH="mobile/scripts/baseline/package_flutter_deps.txt"
BASE_REF="${PACKAGE_FLUTTER_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${PACKAGE_FLUTTER_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="PACKAGE_FLUTTER_ALLOW_NO_BASE"
NEW_HINT="A package under mobile/packages declared a runtime Flutter SDK dependency that is not in the baseline. Only three kinds of package may: a native plugin (ships or wraps a flutter: plugin: block), a presentation-layer package that exports widgets, and a consumer of a Flutter-only API with no pure-Dart substitute. A repository / client / data package is none of those — drop the dependency and use a pure-Dart equivalent (dm_repository's compute + kReleaseMode shims in lib/src/compute.dart and lib/src/build_mode.dart are the worked example). If the package genuinely belongs in one of the three groups, add it to the baseline with a trailing '# reason' and document it in docs/ARCHITECTURE.md."
STALE_HINT="A package no longer declares a runtime Flutter SDK dependency."
FOOTER="Runtime Flutter SDK dependencies under mobile/packages are frozen and may
only decrease. The policy and the current groups are in docs/ARCHITECTURE.md
('Which packages may depend on Flutter'); keep that page in step with this
baseline. flutter_test under dev_dependencies: is not counted. See #3338."

emit_current() {
  local f name
  for f in "$MOBILE_DIR"/packages/*/pubspec.yaml; do
    [[ -f "$f" ]] || continue
    name="$(basename "$(dirname "$f")")"
    awk -v name="$name" '
      /^dependencies:/ { d = 1; next }
      /^[^ #]/ { d = 0 }
      d && /^  flutter(_web_plugins)?:[[:space:]]*$/ {
        if (getline > 0 && $0 ~ /^[[:space:]]+sdk:[[:space:]]*flutter[[:space:]]*$/) {
          hit = 1
        }
      }
      END { if (hit) print name }
    ' "$f"
  done | LC_ALL=C sort -u
}

print_baseline_header() {
  cat <<'EOF'
# Frozen baseline (#3338): packages under mobile/packages that declare a RUNTIME
# Flutter SDK dependency (a `flutter:`/`flutter_web_plugins:` + `sdk: flutter`
# pair in `dependencies:`; `flutter_test` in dev_dependencies is not counted).
# Generated by scripts/check_package_flutter_boundary.sh. The set may only
# SHRINK (growth fails CI vs origin/main) — the missing entry is what makes
# `depend_on_referenced_packages` reject a package:flutter import in that
# package. Fix an entry by replacing the Flutter API with a pure-Dart
# equivalent, then shrink this baseline. Policy and per-package rationale live
# in docs/ARCHITECTURE.md ("Which packages may depend on Flutter").
#
# Each reason names the concrete Flutter surface the package uses, so the next
# person can tell a hard dependency from a removal candidate without re-deriving
# it. The three sanctioned groups are: native plugin, presentation layer, and
# consumer of a Flutter-only API with no pure-Dart substitute.
EOF
}

# shellcheck source=lib/list_ratchet.sh
source "$SCRIPT_DIR/lib/list_ratchet.sh"
run_list_ratchet
