#!/usr/bin/env bash
# Skip-ceiling ratchet (epic #4337, WS-1): the set of test files carrying an
# UNCONDITIONAL test-level skip (`skip: true` / `skip: '<reason>'`) is frozen in
# scripts/baseline/skip_tests.txt and may only ever SHRINK. See lib/list_ratchet.sh
# for the NEW/STALE/GROWTH semantics.
#
# The detector matches  [(, ]skip: (true|'|")  under mobile/test/**/*_test.dart.
# It deliberately EXCLUDES:
#   • platform-conditional skips (`skip: !kIsWeb`, `skip: !Platform.isX`) —
#     intentional gates, not debt (the value is not true/quote, so it won't match).
#   • argument-noise (`skipOffstage:`, `skipCache:`, …) — the literal token is
#     `skipOffstage:` etc., which does not contain `skip: ` (skip-colon-space).
#   • main_video_cache_startup_test.dart — its `skip: true` is an argument to the
#     function under test, not a test skip; those tests run and assert.
#
# Regenerate after FIXING/DELETING a skip (never to add one — that fails GROWTH):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_skip_ceiling.sh
# Usage (from the repo root or mobile/): bash mobile/scripts/check_skip_ceiling.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

RATCHET_LABEL="skip_ceiling"
BASELINE_FILE="$SCRIPT_DIR/baseline/skip_tests.txt"
BASELINE_REPO_PATH="mobile/scripts/baseline/skip_tests.txt"
BASE_REF="${SKIP_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${SKIP_CEILING_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="SKIP_CEILING_ALLOW_NO_BASE"
NEW_HINT="Don't add 'skip: true' to silence a failing test — fix or delete it (epic #4337: delete dead/low-value tests, never re-skip)."
STALE_HINT="A skip was removed (fixed/deleted)."
FOOTER="Skipped tests are frozen and may only decrease. Fix, delete, or properly
quarantine (tag) the test — do not add 'skip: true' + a generic TODO.
See tasks/plan_4337.md (WS-1) and .claude/rules/agent_workflow.md (rule #5)."

SKIP_RE="[(, ]skip: (true|'|\")"

emit_current() {
  find "$MOBILE_DIR/test" \
    -not -path "*/.dart_tool/*" -not -path "*/build/*" \
    -name "*_test.dart" \
    -not -name "main_video_cache_startup_test.dart" \
    -print0 2>/dev/null \
    | xargs -0 grep -lE "$SKIP_RE" 2>/dev/null \
    | sed "s#^$MOBILE_DIR/##" | LC_ALL=C sort -u || true
}

print_baseline_header() {
  cat <<'EOF'
# Frozen baseline: test files under mobile/test/**/*_test.dart that carry a
# test-level skip (`skip: true` / `skip: '<reason>'`). Generated by
# scripts/check_skip_ceiling.sh. The baseline may only SHRINK (growth fails CI
# vs origin/main). A trailing '# reason' marks intent. Skip-debt epic: #4337.
EOF
}

# shellcheck source=lib/list_ratchet.sh
source "$SCRIPT_DIR/lib/list_ratchet.sh"
run_list_ratchet
