#!/usr/bin/env bash
# ARB {error}-placeholder ceiling ratchet (epic #4336 / #3589): the number of
# user-facing strings in lib/l10n/app_en.arb that interpolate raw exception text
# via the {error} placeholder is frozen in scripts/baseline/arb_error_keys.txt
# and may only ever DECREASE. Raw exception text in UI copy bypasses
# localization-friendly messaging and leaks internal error detail to users; the
# target is a status enum mapped to a localized message (.claude/rules/
# error_handling.md + localization.md).
#
# Regenerate after removing an {error}-interpolating string (never to add):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_arb_error_ceiling.sh
# Usage (from repo root or mobile/):
#   bash mobile/scripts/check_arb_error_ceiling.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

RATCHET_LABEL="arb_error_ceiling"
BASELINE_FILE="$SCRIPT_DIR/baseline/arb_error_keys.txt"
BASELINE_REPO_PATH="mobile/scripts/baseline/arb_error_keys.txt"
BASE_REF="${ARB_ERROR_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${ARB_ERROR_CEILING_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="ARB_ERROR_CEILING_ALLOW_NO_BASE"
NEW_HINT="Don't add a user-facing ARB string that interpolates raw {error} exception text. Map a status enum to a localized message instead. See .claude/rules/error_handling.md + localization.md; epic #4336 / #3589."
STALE_HINT="An {error}-interpolating ARB string was removed."
FOOTER="The count of {error}-interpolating ARB strings is frozen and may only
decrease. Surface failures via status enums mapped to localized copy, not raw
exception text. See .claude/rules/error_handling.md and epic #4336 (#3589)."

emit_current() {
  local f="$MOBILE_DIR/lib/l10n/app_en.arb"
  [[ -f "$f" ]] || return 0
  local c
  c="$(grep -oE '\{error\}' "$f" | grep -c . || true)"
  printf 'lib/l10n/app_en.arb\t%s\n' "$c"
}

print_baseline_header() {
  cat <<'EOF'
# Frozen baseline: count of {error}-placeholder interpolations in
# lib/l10n/app_en.arb (format: relpath<TAB>count). Generated by
# scripts/check_arb_error_ceiling.sh. The count may only SHRINK; an increase
# fails CI vs origin/main. Map status enums to localized copy instead of raw
# exception text. Epic: #4336 (#3589).
EOF
}

# shellcheck source=lib/numeric_ratchet.sh
source "$SCRIPT_DIR/lib/numeric_ratchet.sh"
run_numeric_ratchet
