#!/usr/bin/env bash
# Future.delayed-ceiling ratchet (epic #4337, WS-2): the set of test files that
# use `Future.delayed` is frozen in scripts/baseline/future_delayed_tests.txt and
# may only ever SHRINK. `Future.delayed` in tests encodes wall-clock timing that
# makes suites slow and flaky; the migration target is `fakeAsync` (timer/timeout
# cases) or `pumpEventQueue` (stream-settling). See lib/list_ratchet.sh.
#
# The detector scopes to mobile/test/**/*.dart (tests AND hand-written
# helpers/mocks, which carry the same timing debt). It EXCLUDES:
#   • generated files (*.g.dart / *.freezed.dart / *.mocks.dart),
#   • the detector tool's own test + its temp fixtures
#     (future_delayed_detector_test.dart, test/temp/**) — they contain
#     `Future.delayed` as sample strings, not real waits,
#   • *.md / *.archived / *.disabled (not *.dart, excluded by the find name glob),
#   • integration_test/** (separate suite, separate policy — WS-6).
#
# Regenerate after MIGRATING a file off Future.delayed (never to add one):
#   UPDATE_BASELINE=1 bash mobile/scripts/check_future_delayed_ceiling.sh
# Usage (from the repo root or mobile/): bash mobile/scripts/check_future_delayed_ceiling.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

RATCHET_LABEL="future_delayed_ceiling"
BASELINE_FILE="$SCRIPT_DIR/baseline/future_delayed_tests.txt"
BASELINE_REPO_PATH="mobile/scripts/baseline/future_delayed_tests.txt"
BASE_REF="${FUTURE_DELAYED_BASELINE_BASE_REF:-origin/main}"
ALLOW_NO_BASE="${FUTURE_DELAYED_CEILING_ALLOW_NO_BASE:-0}"
ALLOW_NO_BASE_VAR="FUTURE_DELAYED_CEILING_ALLOW_NO_BASE"
NEW_HINT="Don't add Future.delayed to a test — use fakeAsync (timers/timeouts) or pumpEventQueue (stream-settling). See tasks/plan_4337.md (WS-2)."
STALE_HINT="A file was migrated off Future.delayed."
FOOTER="Future.delayed in tests is frozen and may only decrease. Replace it with
fakeAsync (timer/timeout-driven) or pumpEventQueue (stream-settling), not a
longer wall-clock wait. See tasks/plan_4337.md (WS-2)."

emit_current() {
  find "$MOBILE_DIR/test" \
    -not -path "*/.dart_tool/*" -not -path "*/build/*" -not -path "*/temp/*" \
    -name "*.dart" \
    ! -name "*.g.dart" ! -name "*.freezed.dart" ! -name "*.mocks.dart" \
    ! -name "future_delayed_detector_test.dart" \
    -print0 2>/dev/null \
    | xargs -0 grep -lE "Future\.delayed" 2>/dev/null \
    | sed "s#^$MOBILE_DIR/##" | LC_ALL=C sort -u || true
}

print_baseline_header() {
  cat <<'EOF'
# Frozen baseline: files under mobile/test/**/*.dart (tests + hand-written
# helpers/mocks) that use Future.delayed. Generated by
# scripts/check_future_delayed_ceiling.sh. The baseline may only SHRINK (growth
# fails CI vs origin/main). Migrate to fakeAsync / pumpEventQueue. Epic: #4337.
EOF
}

# shellcheck source=lib/list_ratchet.sh
source "$SCRIPT_DIR/lib/list_ratchet.sh"
run_list_ratchet
