// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/helpers/test_provider_overrides.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:io' as _i23;
import 'dart:typed_data' as _i24;
import 'dart:ui' as _i20;

import 'package:file/file.dart' as _i9;
import 'package:flutter_cache_manager/flutter_cache_manager.dart' as _i6;
import 'package:flutter_cache_manager/src/cache_store.dart' as _i7;
import 'package:flutter_cache_manager/src/web/web_helper.dart' as _i8;
import 'package:keycast_flutter/keycast_flutter.dart' as _i17;
import 'package:media_cache/src/media_cache_manager.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:models/models.dart' as _i18;
import 'package:nostr_client/nostr_client.dart' as _i4;
import 'package:nostr_sdk/nostr_sdk.dart' as _i3;
import 'package:openvine/models/known_account.dart' as _i15;
import 'package:openvine/services/auth_service.dart' as _i2;
import 'package:openvine/services/blossom_auth_service.dart' as _i22;
import 'package:openvine/services/profile_cache_service.dart' as _i19;
import 'package:openvine/services/relay_discovery_service.dart' as _i13;
import 'package:openvine/services/social_service.dart' as _i12;
import 'package:openvine/services/subscription_manager.dart' as _i21;
import 'package:openvine/services/user_profile_service.dart' as _i16;
import 'package:shared_preferences/shared_preferences.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthResult_0 extends _i1.SmartFake implements _i2.AuthResult {
  _FakeAuthResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNostrConnectSession_1 extends _i1.SmartFake
    implements _i3.NostrConnectSession {
  _FakeNostrConnectSession_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCountResult_2 extends _i1.SmartFake implements _i4.CountResult {
  _FakeCountResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCacheMetrics_3 extends _i1.SmartFake implements _i5.CacheMetrics {
  _FakeCacheMetrics_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMediaCacheConfig_4 extends _i1.SmartFake
    implements _i5.MediaCacheConfig {
  _FakeMediaCacheConfig_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfig_5 extends _i1.SmartFake implements _i6.Config {
  _FakeConfig_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCacheStore_6 extends _i1.SmartFake implements _i7.CacheStore {
  _FakeCacheStore_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebHelper_7 extends _i1.SmartFake implements _i8.WebHelper {
  _FakeWebHelper_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_8 extends _i1.SmartFake implements _i9.File {
  _FakeFile_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileInfo_9 extends _i1.SmartFake implements _i6.FileInfo {
  _FakeFileInfo_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i10.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);

  @override
  _i11.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [SocialService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocialService extends _i1.Mock implements _i12.SocialService {
  MockSocialService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i12.FollowSet> get followSets =>
      (super.noSuchMethod(
            Invocation.getter(#followSets),
            returnValue: <_i12.FollowSet>[],
          )
          as List<_i12.FollowSet>);

  @override
  Map<String, int>? getCachedFollowerStats(String? pubkey) =>
      (super.noSuchMethod(Invocation.method(#getCachedFollowerStats, [pubkey]))
          as Map<String, int>?);

  @override
  _i12.FollowSet? getFollowSetById(String? setId) =>
      (super.noSuchMethod(Invocation.method(#getFollowSetById, [setId]))
          as _i12.FollowSet?);

  @override
  bool isInFollowSet(String? setId, String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#isInFollowSet, [setId, pubkey]),
            returnValue: false,
          )
          as bool);

  @override
  _i11.Future<Map<String, int>> getFollowerStats(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowerStats, [pubkey]),
            returnValue: _i11.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i11.Future<Map<String, int>>);

  @override
  _i11.Future<_i12.FollowSet?> createFollowSet({
    required String? name,
    String? description,
    String? imageUrl,
    List<String>? initialPubkeys = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createFollowSet, [], {
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
              #initialPubkeys: initialPubkeys,
            }),
            returnValue: _i11.Future<_i12.FollowSet?>.value(),
          )
          as _i11.Future<_i12.FollowSet?>);

  @override
  _i11.Future<bool> addToFollowSet(String? setId, String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#addToFollowSet, [setId, pubkey]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> removeFromFollowSet(String? setId, String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromFollowSet, [setId, pubkey]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> updateFollowSet({
    required String? setId,
    String? name,
    String? description,
    String? imageUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateFollowSet, [], {
              #setId: setId,
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
            }),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> deleteFollowSet(String? setId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFollowSet, [setId]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<int> getUserVideoCount(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getUserVideoCount, [pubkey]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<void> publishRightToBeForgotten() =>
      (super.noSuchMethod(
            Invocation.method(#publishRightToBeForgotten, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthState get authState =>
      (super.noSuchMethod(
            Invocation.getter(#authState),
            returnValue: _i2.AuthState.unauthenticated,
          )
          as _i2.AuthState);

  @override
  _i11.Stream<_i2.AuthState> get authStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#authStateStream),
            returnValue: _i11.Stream<_i2.AuthState>.empty(),
          )
          as _i11.Stream<_i2.AuthState>);

  @override
  _i11.Stream<_i2.UserProfile?> get profileStream =>
      (super.noSuchMethod(
            Invocation.getter(#profileStream),
            returnValue: _i11.Stream<_i2.UserProfile?>.empty(),
          )
          as _i11.Stream<_i2.UserProfile?>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i2.AuthenticationSource get authenticationSource =>
      (super.noSuchMethod(
            Invocation.getter(#authenticationSource),
            returnValue: _i2.AuthenticationSource.none,
          )
          as _i2.AuthenticationSource);

  @override
  bool get isRegistered =>
      (super.noSuchMethod(Invocation.getter(#isRegistered), returnValue: false)
          as bool);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false)
          as bool);

  @override
  List<_i13.DiscoveredRelay> get userRelays =>
      (super.noSuchMethod(
            Invocation.getter(#userRelays),
            returnValue: <_i13.DiscoveredRelay>[],
          )
          as List<_i13.DiscoveredRelay>);

  @override
  bool get hasExistingProfile =>
      (super.noSuchMethod(
            Invocation.getter(#hasExistingProfile),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, dynamic> get userStats =>
      (super.noSuchMethod(
            Invocation.getter(#userStats),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  String get serviceName =>
      (super.noSuchMethod(
            Invocation.getter(#serviceName),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#serviceName),
            ),
          )
          as String);

  @override
  void registerUserRelaysDiscoveredCallback(
    _i2.UserRelaysDiscoveredCallback? callback,
  ) => super.noSuchMethod(
    Invocation.method(#registerUserRelaysDiscoveredCallback, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<bool> hasSavedKeys() =>
      (super.noSuchMethod(
            Invocation.method(#hasSavedKeys, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<String?> getSavedNpub() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedNpub, []),
            returnValue: _i11.Future<String?>.value(),
          )
          as _i11.Future<String?>);

  @override
  _i11.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i2.AuthResult> createNewIdentity({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#createNewIdentity, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i11.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(#createNewIdentity, [], {
                  #biometricPrompt: biometricPrompt,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.AuthResult>);

  @override
  _i11.Future<void> createAnonymousAccount() =>
      (super.noSuchMethod(
            Invocation.method(#createAnonymousAccount, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<List<_i15.KnownAccount>> getKnownAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#getKnownAccounts, []),
            returnValue: _i11.Future<List<_i15.KnownAccount>>.value(
              <_i15.KnownAccount>[],
            ),
          )
          as _i11.Future<List<_i15.KnownAccount>>);

  @override
  _i11.Future<void> removeKnownAccount(String? pubkeyHex) =>
      (super.noSuchMethod(
            Invocation.method(#removeKnownAccount, [pubkeyHex]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> signInForAccount(
    String? pubkeyHex,
    _i2.AuthenticationSource? authSource,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInForAccount, [pubkeyHex, authSource]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i2.AuthResult> connectWithAmber() =>
      (super.noSuchMethod(
            Invocation.method(#connectWithAmber, []),
            returnValue: _i11.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(this, Invocation.method(#connectWithAmber, [])),
            ),
          )
          as _i11.Future<_i2.AuthResult>);

  @override
  _i11.Future<_i2.AuthResult> importFromNsec(
    String? nsec, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importFromNsec,
              [nsec],
              {#biometricPrompt: biometricPrompt},
            ),
            returnValue: _i11.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(
                  #importFromNsec,
                  [nsec],
                  {#biometricPrompt: biometricPrompt},
                ),
              ),
            ),
          )
          as _i11.Future<_i2.AuthResult>);

  @override
  _i11.Future<_i2.AuthResult> importFromHex(
    String? privateKeyHex, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importFromHex,
              [privateKeyHex],
              {#biometricPrompt: biometricPrompt},
            ),
            returnValue: _i11.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(
                  #importFromHex,
                  [privateKeyHex],
                  {#biometricPrompt: biometricPrompt},
                ),
              ),
            ),
          )
          as _i11.Future<_i2.AuthResult>);

  @override
  _i11.Future<_i2.AuthResult> connectWithBunker(String? bunkerUrl) =>
      (super.noSuchMethod(
            Invocation.method(#connectWithBunker, [bunkerUrl]),
            returnValue: _i11.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(#connectWithBunker, [bunkerUrl]),
              ),
            ),
          )
          as _i11.Future<_i2.AuthResult>);

  @override
  _i11.Future<_i3.NostrConnectSession> initiateNostrConnect({
    List<String>? customRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initiateNostrConnect, [], {
              #customRelays: customRelays,
            }),
            returnValue: _i11.Future<_i3.NostrConnectSession>.value(
              _FakeNostrConnectSession_1(
                this,
                Invocation.method(#initiateNostrConnect, [], {
                  #customRelays: customRelays,
                }),
              ),
            ),
          )
          as _i11.Future<_i3.NostrConnectSession>);

  @override
  _i11.Future<_i2.AuthResult> waitForNostrConnectResponse({
    Duration? timeout = const Duration(minutes: 2),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#waitForNostrConnectResponse, [], {
              #timeout: timeout,
            }),
            returnValue: _i11.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(#waitForNostrConnectResponse, [], {
                  #timeout: timeout,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.AuthResult>);

  @override
  void cancelNostrConnect() => super.noSuchMethod(
    Invocation.method(#cancelNostrConnect, []),
    returnValueForMissingStub: null,
  );

  @override
  void onSignerCallbackReceived() => super.noSuchMethod(
    Invocation.method(#onSignerCallbackReceived, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> refreshCurrentProfile(
    _i16.UserProfileService? userProfileService,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refreshCurrentProfile, [userProfileService]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> signInWithDivineOAuth(_i17.KeycastSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithDivineOAuth, [session]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<(bool, String?)> deleteKeycastAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteKeycastAccount, []),
            returnValue: _i11.Future<(bool, String?)>.value((false, null)),
          )
          as _i11.Future<(bool, String?)>);

  @override
  _i11.Future<void> signOut({bool? deleteKeys = false}) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [], {#deleteKeys: deleteKeys}),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<String?> getPrivateKeyForSigning({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#getPrivateKeyForSigning, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i11.Future<String?>.value(),
          )
          as _i11.Future<String?>);

  @override
  _i11.Future<String?> exportNsec({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#exportNsec, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i11.Future<String?>.value(),
          )
          as _i11.Future<String?>);

  @override
  _i11.Future<_i3.Event?> createAndSignEvent({
    required int? kind,
    required String? content,
    List<List<String>>? tags,
    String? biometricPrompt,
    int? createdAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAndSignEvent, [], {
              #kind: kind,
              #content: content,
              #tags: tags,
              #biometricPrompt: biometricPrompt,
              #createdAt: createdAt,
            }),
            returnValue: _i11.Future<_i3.Event?>.value(),
          )
          as _i11.Future<_i3.Event?>);

  @override
  _i11.Future<void> acceptTerms() =>
      (super.noSuchMethod(
            Invocation.method(#acceptTerms, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void onAppBackgrounded() => super.noSuchMethod(
    Invocation.method(#onAppBackgrounded, []),
    returnValueForMissingStub: null,
  );

  @override
  void onAppResumed() => super.noSuchMethod(
    Invocation.method(#onAppResumed, []),
    returnValueForMissingStub: null,
  );

  @override
  void onExtendedBackground() => super.noSuchMethod(
    Invocation.method(#onExtendedBackground, []),
    returnValueForMissingStub: null,
  );

  @override
  void onPeriodicCleanup() => super.noSuchMethod(
    Invocation.method(#onPeriodicCleanup, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [NostrClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockNostrClient extends _i1.Mock implements _i4.NostrClient {
  MockNostrClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get publicKey =>
      (super.noSuchMethod(
            Invocation.getter(#publicKey),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#publicKey),
            ),
          )
          as String);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);

  @override
  bool get hasKeys =>
      (super.noSuchMethod(Invocation.getter(#hasKeys), returnValue: false)
          as bool);

  @override
  int get activeSubscriptionCount =>
      (super.noSuchMethod(
            Invocation.getter(#activeSubscriptionCount),
            returnValue: 0,
          )
          as int);

  @override
  List<String> get configuredRelays =>
      (super.noSuchMethod(
            Invocation.getter(#configuredRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get connectedRelays =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  int get connectedRelayCount =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelayCount),
            returnValue: 0,
          )
          as int);

  @override
  int get configuredRelayCount =>
      (super.noSuchMethod(
            Invocation.getter(#configuredRelayCount),
            returnValue: 0,
          )
          as int);

  @override
  Map<String, _i4.RelayConnectionStatus> get relayStatuses =>
      (super.noSuchMethod(
            Invocation.getter(#relayStatuses),
            returnValue: <String, _i4.RelayConnectionStatus>{},
          )
          as Map<String, _i4.RelayConnectionStatus>);

  @override
  _i11.Stream<Map<String, _i4.RelayConnectionStatus>> get relayStatusStream =>
      (super.noSuchMethod(
            Invocation.getter(#relayStatusStream),
            returnValue:
                _i11.Stream<Map<String, _i4.RelayConnectionStatus>>.empty(),
          )
          as _i11.Stream<Map<String, _i4.RelayConnectionStatus>>);

  @override
  String get primaryRelay =>
      (super.noSuchMethod(
            Invocation.getter(#primaryRelay),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#primaryRelay),
            ),
          )
          as String);

  @override
  set statisticsObserver(_i4.NostrClientStatisticsObserver? value) =>
      super.noSuchMethod(
        Invocation.setter(#statisticsObserver, value),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i3.Event?> publishEvent(
    _i3.Event? event, {
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #publishEvent,
              [event],
              {#targetRelays: targetRelays},
            ),
            returnValue: _i11.Future<_i3.Event?>.value(),
          )
          as _i11.Future<_i3.Event?>);

  @override
  _i11.Future<List<_i3.Event>> queryEvents(
    List<_i3.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    bool? sendAfterAuth = false,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queryEvents,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #relayTypes: relayTypes,
                #sendAfterAuth: sendAfterAuth,
                #useCache: useCache,
              },
            ),
            returnValue: _i11.Future<List<_i3.Event>>.value(<_i3.Event>[]),
          )
          as _i11.Future<List<_i3.Event>>);

  @override
  _i11.Future<_i4.CountResult> countEvents(
    List<_i3.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #countEvents,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #relayTypes: relayTypes,
                #timeout: timeout,
              },
            ),
            returnValue: _i11.Future<_i4.CountResult>.value(
              _FakeCountResult_2(
                this,
                Invocation.method(
                  #countEvents,
                  [filters],
                  {
                    #subscriptionId: subscriptionId,
                    #tempRelays: tempRelays,
                    #relayTypes: relayTypes,
                    #timeout: timeout,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i4.CountResult>);

  @override
  _i11.Future<_i3.Event?> fetchEventById(
    String? eventId, {
    String? relayUrl,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchEventById,
              [eventId],
              {#relayUrl: relayUrl, #useCache: useCache},
            ),
            returnValue: _i11.Future<_i3.Event?>.value(),
          )
          as _i11.Future<_i3.Event?>);

  @override
  _i11.Future<_i3.Event?> fetchProfile(
    String? pubkey, {
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProfile, [pubkey], {#useCache: useCache}),
            returnValue: _i11.Future<_i3.Event?>.value(),
          )
          as _i11.Future<_i3.Event?>);

  @override
  _i11.Stream<_i3.Event> subscribe(
    List<_i3.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<String>? targetRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    bool? sendAfterAuth = false,
    void Function()? onEose,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribe,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
                #relayTypes: relayTypes,
                #sendAfterAuth: sendAfterAuth,
                #onEose: onEose,
              },
            ),
            returnValue: _i11.Stream<_i3.Event>.empty(),
          )
          as _i11.Stream<_i3.Event>);

  @override
  _i11.Future<void> unsubscribe(String? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [subscriptionId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> closeAllSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#closeAllSubscriptions, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<bool> addRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#addRelay, [relayUrl]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<int> addRelays(List<String>? relayUrls) =>
      (super.noSuchMethod(
            Invocation.method(#addRelays, [relayUrls]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<bool> removeRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#removeRelay, [relayUrl]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  Map<String, ({int errors, int eventsReceived, int queriesSent})>
  getRelayPoolCounters() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayPoolCounters, []),
            returnValue:
                <String, ({int errors, int eventsReceived, int queriesSent})>{},
          )
          as Map<String, ({int errors, int eventsReceived, int queriesSent})>);

  @override
  _i11.Future<Map<String, dynamic>?> getRelayStats() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStats, []),
            returnValue: _i11.Future<Map<String, dynamic>?>.value(),
          )
          as _i11.Future<Map<String, dynamic>?>);

  @override
  _i11.Future<void> retryDisconnectedRelays() =>
      (super.noSuchMethod(
            Invocation.method(#retryDisconnectedRelays, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> forceReconnectAll() =>
      (super.noSuchMethod(
            Invocation.method(#forceReconnectAll, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  Map<String, bool> getRelayStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStatus, []),
            returnValue: <String, bool>{},
          )
          as Map<String, bool>);

  @override
  _i11.Future<_i3.Event?> sendLike(
    String? eventId, {
    String? content,
    String? addressableId,
    String? targetAuthorPubkey,
    int? targetKind,
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendLike,
              [eventId],
              {
                #content: content,
                #addressableId: addressableId,
                #targetAuthorPubkey: targetAuthorPubkey,
                #targetKind: targetKind,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
              },
            ),
            returnValue: _i11.Future<_i3.Event?>.value(),
          )
          as _i11.Future<_i3.Event?>);

  @override
  _i11.Future<_i3.Event?> sendProfile({
    required Map<String, dynamic>? profileContent,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendProfile, [], {
              #profileContent: profileContent,
            }),
            returnValue: _i11.Future<_i3.Event?>.value(),
          )
          as _i11.Future<_i3.Event?>);

  @override
  _i11.Future<_i3.Event?> sendRepost(
    String? eventId, {
    String? relayAddr,
    String? content = '',
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendRepost,
              [eventId],
              {
                #relayAddr: relayAddr,
                #content: content,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
              },
            ),
            returnValue: _i11.Future<_i3.Event?>.value(),
          )
          as _i11.Future<_i3.Event?>);

  @override
  _i11.Future<_i3.Event?> sendGenericRepost({
    required String? addressableId,
    required int? targetKind,
    required String? authorPubkey,
    String? eventId,
    String? content = '',
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendGenericRepost, [], {
              #addressableId: addressableId,
              #targetKind: targetKind,
              #authorPubkey: authorPubkey,
              #eventId: eventId,
              #content: content,
              #tempRelays: tempRelays,
              #targetRelays: targetRelays,
            }),
            returnValue: _i11.Future<_i3.Event?>.value(),
          )
          as _i11.Future<_i3.Event?>);

  @override
  _i11.Future<_i3.Event?> deleteEvent(
    String? eventId, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteEvent,
              [eventId],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i11.Future<_i3.Event?>.value(),
          )
          as _i11.Future<_i3.Event?>);

  @override
  _i11.Future<_i3.Event?> deleteEvents(
    List<String>? eventIds, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteEvents,
              [eventIds],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i11.Future<_i3.Event?>.value(),
          )
          as _i11.Future<_i3.Event?>);

  @override
  _i11.Future<_i3.Event?> sendContactList(
    _i3.ContactList? contacts,
    String? content, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendContactList,
              [contacts, content],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i11.Future<_i3.Event?>.value(),
          )
          as _i11.Future<_i3.Event?>);

  @override
  _i11.Stream<_i3.Event> searchVideos(
    String? query, {
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchVideos,
              [query],
              {#authors: authors, #since: since, #until: until, #limit: limit},
            ),
            returnValue: _i11.Stream<_i3.Event>.empty(),
          )
          as _i11.Stream<_i3.Event>);

  @override
  _i11.Stream<_i3.Event> searchUsers(String? query, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query], {#limit: limit}),
            returnValue: _i11.Stream<_i3.Event>.empty(),
          )
          as _i11.Stream<_i3.Event>);

  @override
  _i11.Future<List<_i3.Event>> queryUsers(String? query, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#queryUsers, [query], {#limit: limit}),
            returnValue: _i11.Future<List<_i3.Event>>.value(<_i3.Event>[]),
          )
          as _i11.Future<List<_i3.Event>>);

  @override
  _i11.Future<String?> createNip98AuthHeader({
    required String? url,
    required String? method,
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createNip98AuthHeader, [], {
              #url: url,
              #method: method,
              #payload: payload,
            }),
            returnValue: _i11.Future<String?>.value(),
          )
          as _i11.Future<String?>);

  @override
  _i11.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [UserProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileService extends _i1.Mock
    implements _i16.UserProfileService {
  MockUserProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, _i18.UserProfile> get allProfiles =>
      (super.noSuchMethod(
            Invocation.getter(#allProfiles),
            returnValue: <String, _i18.UserProfile>{},
          )
          as Map<String, _i18.UserProfile>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setFunnelcakeAvailable(bool? available) => super.noSuchMethod(
    Invocation.method(#setFunnelcakeAvailable, [available]),
    returnValueForMissingStub: null,
  );

  @override
  void setPersistentCache(_i19.ProfileCacheService? cacheService) =>
      super.noSuchMethod(
        Invocation.method(#setPersistentCache, [cacheService]),
        returnValueForMissingStub: null,
      );

  @override
  _i18.UserProfile? getCachedProfile(String? pubkey) =>
      (super.noSuchMethod(Invocation.method(#getCachedProfile, [pubkey]))
          as _i18.UserProfile?);

  @override
  bool hasProfile(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#hasProfile, [pubkey]),
            returnValue: false,
          )
          as bool);

  @override
  bool shouldSkipProfileFetch(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#shouldSkipProfileFetch, [pubkey]),
            returnValue: false,
          )
          as bool);

  @override
  void markProfileAsMissing(String? pubkey) => super.noSuchMethod(
    Invocation.method(#markProfileAsMissing, [pubkey]),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> updateCachedProfile(_i18.UserProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateCachedProfile, [profile]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i18.UserProfile?> fetchProfile(
    String? pubkey, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchProfile,
              [pubkey],
              {#forceRefresh: forceRefresh},
            ),
            returnValue: _i11.Future<_i18.UserProfile?>.value(),
          )
          as _i11.Future<_i18.UserProfile?>);

  @override
  _i11.Future<void> prefetchProfilesImmediately(List<String>? pubkeys) =>
      (super.noSuchMethod(
            Invocation.method(#prefetchProfilesImmediately, [pubkeys]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> fetchMultipleProfiles(
    List<String>? pubkeys, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchMultipleProfiles,
              [pubkeys],
              {#forceRefresh: forceRefresh},
            ),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  String getDisplayName(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getDisplayName, [pubkey]),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#getDisplayName, [pubkey]),
            ),
          )
          as String);

  @override
  void removeProfile(String? pubkey) => super.noSuchMethod(
    Invocation.method(#removeProfile, [pubkey]),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<List<_i18.UserProfile>> searchUsers(
    String? query, {
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query], {#limit: limit}),
            returnValue: _i11.Future<List<_i18.UserProfile>>.value(
              <_i18.UserProfile>[],
            ),
          )
          as _i11.Future<List<_i18.UserProfile>>);

  @override
  void handleProfileEventForTesting(_i3.Event? event) => super.noSuchMethod(
    Invocation.method(#handleProfileEventForTesting, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i20.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i20.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SubscriptionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionManager extends _i1.Mock
    implements _i21.SubscriptionManager {
  MockSubscriptionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> get activeSubscriptionIds =>
      (super.noSuchMethod(
            Invocation.getter(#activeSubscriptionIds),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  int get activeSubscriptionCount =>
      (super.noSuchMethod(
            Invocation.getter(#activeSubscriptionCount),
            returnValue: 0,
          )
          as int);

  @override
  void setCacheLookup({
    _i3.Event? Function(String)? getCachedEvent,
    bool Function(String)? hasProfileCached,
  }) => super.noSuchMethod(
    Invocation.method(#setCacheLookup, [], {
      #getCachedEvent: getCachedEvent,
      #hasProfileCached: hasProfileCached,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<String> createSubscription({
    required String? name,
    required List<_i3.Filter>? filters,
    required dynamic Function(_i3.Event)? onEvent,
    dynamic Function(dynamic)? onError,
    dynamic Function()? onComplete,
    Duration? timeout,
    int? priority = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSubscription, [], {
              #name: name,
              #filters: filters,
              #onEvent: onEvent,
              #onError: onError,
              #onComplete: onComplete,
              #timeout: timeout,
              #priority: priority,
            }),
            returnValue: _i11.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#createSubscription, [], {
                  #name: name,
                  #filters: filters,
                  #onEvent: onEvent,
                  #onError: onError,
                  #onComplete: onComplete,
                  #timeout: timeout,
                  #priority: priority,
                }),
              ),
            ),
          )
          as _i11.Future<String>);

  @override
  _i11.Future<void> cancelSubscription(String? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelSubscription, [subscriptionId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> cancelAllSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllSubscriptions, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  bool isSubscriptionActive(String? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#isSubscriptionActive, [subscriptionId]),
            returnValue: false,
          )
          as bool);

  @override
  _i11.Future<void> cancelSubscriptionsByName(String? namePattern) =>
      (super.noSuchMethod(
            Invocation.method(#cancelSubscriptionsByName, [namePattern]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [BlossomAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlossomAuthService extends _i1.Mock
    implements _i22.BlossomAuthService {
  MockBlossomAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> get cacheStats =>
      (super.noSuchMethod(
            Invocation.getter(#cacheStats),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  bool get canCreateHeaders =>
      (super.noSuchMethod(
            Invocation.getter(#canCreateHeaders),
            returnValue: false,
          )
          as bool);

  @override
  _i11.Future<String?> createGetAuthHeader({
    required String? sha256Hash,
    String? serverUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createGetAuthHeader, [], {
              #sha256Hash: sha256Hash,
              #serverUrl: serverUrl,
            }),
            returnValue: _i11.Future<String?>.value(),
          )
          as _i11.Future<String?>);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MediaCacheManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaCacheManager extends _i1.Mock implements _i5.MediaCacheManager {
  MockMediaCacheManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.CacheMetrics get metrics =>
      (super.noSuchMethod(
            Invocation.getter(#metrics),
            returnValue: _FakeCacheMetrics_3(this, Invocation.getter(#metrics)),
          )
          as _i5.CacheMetrics);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i5.MediaCacheConfig get mediaConfig =>
      (super.noSuchMethod(
            Invocation.getter(#mediaConfig),
            returnValue: _FakeMediaCacheConfig_4(
              this,
              Invocation.getter(#mediaConfig),
            ),
          )
          as _i5.MediaCacheConfig);

  @override
  _i6.Config get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeConfig_5(this, Invocation.getter(#config)),
          )
          as _i6.Config);

  @override
  _i7.CacheStore get store =>
      (super.noSuchMethod(
            Invocation.getter(#store),
            returnValue: _FakeCacheStore_6(this, Invocation.getter(#store)),
          )
          as _i7.CacheStore);

  @override
  _i8.WebHelper get webHelper =>
      (super.noSuchMethod(
            Invocation.getter(#webHelper),
            returnValue: _FakeWebHelper_7(this, Invocation.getter(#webHelper)),
          )
          as _i8.WebHelper);

  @override
  _i11.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i23.File? getCachedFileSync(String? key) =>
      (super.noSuchMethod(Invocation.method(#getCachedFileSync, [key]))
          as _i23.File?);

  @override
  _i11.Future<_i23.File?> cacheFile(
    String? url, {
    required String? key,
    Map<String, String>? authHeaders,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #cacheFile,
              [url],
              {#key: key, #authHeaders: authHeaders},
            ),
            returnValue: _i11.Future<_i23.File?>.value(),
          )
          as _i11.Future<_i23.File?>);

  @override
  _i11.Future<bool> isFileCached(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#isFileCached, [key]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<void> preCacheFiles(
    List<({String key, String url})>? items, {
    int? batchSize = 3,
    Map<String, String>? Function(String)? authHeadersProvider,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #preCacheFiles,
              [items],
              {
                #batchSize: batchSize,
                #authHeadersProvider: authHeadersProvider,
              },
            ),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> removeCachedFile(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#removeCachedFile, [key]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  Map<String, dynamic> getCacheStats() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheStats, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void resetForTesting() => super.noSuchMethod(
    Invocation.method(#resetForTesting, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<_i9.File> getSingleFile(
    String? url, {
    String? key,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSingleFile,
              [url],
              {#key: key, #headers: headers},
            ),
            returnValue: _i11.Future<_i9.File>.value(
              _FakeFile_8(
                this,
                Invocation.method(
                  #getSingleFile,
                  [url],
                  {#key: key, #headers: headers},
                ),
              ),
            ),
          )
          as _i11.Future<_i9.File>);

  @override
  _i11.Stream<_i6.FileInfo> getFile(
    String? url, {
    String? key,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFile, [url], {#key: key, #headers: headers}),
            returnValue: _i11.Stream<_i6.FileInfo>.empty(),
          )
          as _i11.Stream<_i6.FileInfo>);

  @override
  _i11.Stream<_i6.FileResponse> getFileStream(
    String? url, {
    String? key,
    Map<String, String>? headers,
    bool? withProgress = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getFileStream,
              [url],
              {#key: key, #headers: headers, #withProgress: withProgress},
            ),
            returnValue: _i11.Stream<_i6.FileResponse>.empty(),
          )
          as _i11.Stream<_i6.FileResponse>);

  @override
  _i11.Future<_i6.FileInfo> downloadFile(
    String? url, {
    String? key,
    Map<String, String>? authHeaders,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadFile,
              [url],
              {#key: key, #authHeaders: authHeaders, #force: force},
            ),
            returnValue: _i11.Future<_i6.FileInfo>.value(
              _FakeFileInfo_9(
                this,
                Invocation.method(
                  #downloadFile,
                  [url],
                  {#key: key, #authHeaders: authHeaders, #force: force},
                ),
              ),
            ),
          )
          as _i11.Future<_i6.FileInfo>);

  @override
  _i11.Future<_i6.FileInfo?> getFileFromCache(
    String? key, {
    bool? ignoreMemCache = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getFileFromCache,
              [key],
              {#ignoreMemCache: ignoreMemCache},
            ),
            returnValue: _i11.Future<_i6.FileInfo?>.value(),
          )
          as _i11.Future<_i6.FileInfo?>);

  @override
  _i11.Future<_i6.FileInfo?> getFileFromMemory(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getFileFromMemory, [key]),
            returnValue: _i11.Future<_i6.FileInfo?>.value(),
          )
          as _i11.Future<_i6.FileInfo?>);

  @override
  _i11.Future<_i9.File> putFile(
    String? url,
    _i24.Uint8List? fileBytes, {
    String? key,
    String? eTag,
    Duration? maxAge = const Duration(days: 30),
    String? fileExtension = 'file',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putFile,
              [url, fileBytes],
              {
                #key: key,
                #eTag: eTag,
                #maxAge: maxAge,
                #fileExtension: fileExtension,
              },
            ),
            returnValue: _i11.Future<_i9.File>.value(
              _FakeFile_8(
                this,
                Invocation.method(
                  #putFile,
                  [url, fileBytes],
                  {
                    #key: key,
                    #eTag: eTag,
                    #maxAge: maxAge,
                    #fileExtension: fileExtension,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i9.File>);

  @override
  _i11.Future<_i9.File> putFileStream(
    String? url,
    _i11.Stream<List<int>>? source, {
    String? key,
    String? eTag,
    Duration? maxAge = const Duration(days: 30),
    String? fileExtension = 'file',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putFileStream,
              [url, source],
              {
                #key: key,
                #eTag: eTag,
                #maxAge: maxAge,
                #fileExtension: fileExtension,
              },
            ),
            returnValue: _i11.Future<_i9.File>.value(
              _FakeFile_8(
                this,
                Invocation.method(
                  #putFileStream,
                  [url, source],
                  {
                    #key: key,
                    #eTag: eTag,
                    #maxAge: maxAge,
                    #fileExtension: fileExtension,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i9.File>);

  @override
  _i11.Future<void> removeFile(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#removeFile, [key]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> emptyCache() =>
      (super.noSuchMethod(
            Invocation.method(#emptyCache, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}
