name: hashtag_repository
description: Repository for searching hashtags via the Funnelcake API.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ^3.41.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  funnelcake_api_client:
  models:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0
