name = "openvine-website"
compatibility_date = "2024-06-01"

# Static site configuration
main = "src/index.js"

[assets]
directory = "."

[env.production]
name = "openvine-website"
routes = [
  { pattern = "openvine.co/*", zone_name = "openvine.co" }
]

[env.staging]
name = "openvine-website-staging"
routes = [
  { pattern = "staging.openvine.co/*", zone_name = "openvine.co" }
]