name: sound_service
description: >
  Services for audio playback and sound effects in the app.
  Includes countdown beep sounds and audio playback with headphone detection.
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ^3.41.1

dependencies:
  audio_session: ^0.2.1
  flutter:
    sdk: flutter
  just_audio: ^0.10.5
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
