name: Mergeability Check

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions:
  contents: read

jobs:
  mergeability:
    name: mergeability
    uses: divinevideo/.github/.github/workflows/mergeability_check.yml@d663ac7ed7c0c05c5597c22738e8f96729d4baf9
    with:
      base-ref: ${{ github.event.pull_request.base.ref }}
      base-repository: ${{ github.repository }}
      head-repository: ${{ github.event.pull_request.head.repo.full_name }}
      head-sha: ${{ github.event.pull_request.head.sha }}
      workflow-repository-ref: d663ac7ed7c0c05c5597c22738e8f96729d4baf9
